In [2]:
"""
Files On hold:

Ddata/PMS 360 Employee Report_PMS 360.xls (file corrupted)
Ddata/Probation Confirmation Report.xls (file corrupted)

Files Cleaned:

Performance Goal Report 25-26.xlsx (already exists)
Goal Status Report 2025-26 All.xlsx (already exists)
Historical Ratings and Other Information.xlsx
Performance 360 degree Feedback participants status - All.xlsx
PIP Transaction Report.xls
PMS Q2 25-26 Rating report - all.xlsx
PMS Task Status Report All.xlsx

"""

'\nFiles On hold:\n\nDdata/PMS 360 Employee Report_PMS 360.xls (file corrupted)\nDdata/Probation Confirmation Report.xls (file corrupted)\n\nFiles Cleaned:\n\nPerformance Goal Report 25-26.xlsx (already exists)\nGoal Status Report 2025-26 All.xlsx (already exists)\nHistorical Ratings and Other Information.xlsx\nPerformance 360 degree Feedback participants status - All.xlsx\nPIP Transaction Report.xls\nPMS Q2 25-26 Rating report - all.xlsx\nPMS Task Status Report All.xlsx\n\n'

In [3]:
import os
from dotenv import load_dotenv
from pymongo import MongoClient

load_dotenv()

MONGO_URI = os.getenv("MONGODB_URI")
if not MONGO_URI:
    raise RuntimeError("MONGO_URI not found in .env")
client = MongoClient(MONGO_URI)
db = client["hr-cleaned"]

In [16]:
import os

folder_path = "C:/Users/SaptarshiBanik/Projects/Tata Play/mongo-rag/src/Ddata"
files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]

print("Files in the directory:")
for file in files:
    print(f"Ddata/{file}")

Files in the directory:
Ddata/8.Leave Transaction With Balance Report_Leave Transaction With Balance Report (3).xlsx
Ddata/Goal Detail Report.xlsx
Ddata/Goal Status Report 2025-26 All.xlsx
Ddata/Historical Ratings and Other Information.xlsx
Ddata/Output1.xls
Ddata/Performance 360 degree Feedback participants status - All.xlsx
Ddata/Performance Goal Report 25-26.xlsx
Ddata/PIP Transaction Report.xls
Ddata/PMS 360 Employee Report_PMS 360.xls
Ddata/PMS Q2 25-26 Rating report - all.xlsx
Ddata/PMS Task Status Report All.xlsx
Ddata/Probation Confirmation Report.xls

In [17]:
from datetime import datetime as dt
import pandas as pd

In [18]:
def parse_date(value):
    if pd.isna(value) or value == "":
        return None

    if isinstance(value, (dt, pd.Timestamp)):
        return value.to_pydatetime() if hasattr(value, "to_pydatetime") else value

    val = str(value).strip()

    date_formats = [
        "%Y-%m-%d",
        "%d-%m-%Y",
        "%d/%m/%Y",
        "%Y/%m/%d",
        "%d-%b-%Y",                
        "%d-%b-%Y".upper(),         
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%dT%H:%M:%S.%fZ",
        "%Y-%m-%dT%H:%M:%S.%f%z"    
    ]

    for fmt in date_formats:
        try:
            return dt.strptime(val, fmt)
        except:
            pass

    return None

In [19]:
def normalize_doc_generic(raw_doc, fields, key_renames, numeric_fields, date_fields):
    cleaned = {}

    for field in fields:
        old_key = field
        new_key = key_renames.get(field, field)

        value = raw_doc.get(old_key)

        # Missing value
        if value is None:
            if new_key in numeric_fields:
                cleaned[new_key] = None
            elif new_key in date_fields:
                cleaned[new_key] = None  
            else:
                cleaned[new_key] = "NA"
            continue

        # Date fields
        if new_key in date_fields:
            # If already MongoDB extended JSON date, keep as is
            if isinstance(value, dict) and "$date" in value:
                cleaned[new_key] = value
            else:
                cleaned[new_key] = parse_date(value)
            continue

        # Numeric fields
        if new_key in numeric_fields:
            try:
                cleaned[new_key] = int(value)
            except Exception:
                cleaned[new_key] = None
            continue

        # Default: treat as string field
        value_str = str(value).strip()
        value_str.replace("...","")
        value_str.strip()
        cleaned[new_key] = value_str if value_str else "NA"


    return cleaned

## Ddata/Historical Ratings and Other Information.xlsx

In [31]:
path="Ddata/Historical Ratings and Other Information.xlsx"
collection="historical_ratings_and-other_information"
df=pd.read_excel(path)

In [10]:
df.columns

Index(['Employee Code', 'FIRST NAME', 'LAST NAME', 'GRADE', 'Grade Level',
       'Designation', 'DEPARTMENT', 'SUB-DEPT', 'Location', 'Office', 'Region',
       'DOJ', 'Assignment Status Type', 'Final Rating  20-21',
       'Final Rating  21-22', 'Final Rating  22-23', 'Final Rating  23-24',
       'Last Promotion date', 'Rating 24-25', 'Experience Prior to Tata Play',
       'Tata Play Experience', 'Total Yrs Exp', 'Previous company', 'MT Batch',
       'Highest Qualification', 'University Name'],
      dtype='object')

In [16]:
FIELDS = [
    "Employee Code",
    "FIRST NAME",
    "LAST NAME",
    "GRADE",
    "Grade Level",
    "Designation",
    "DEPARTMENT",
    "SUB-DEPT",
    "Location",
    "Office",
    "Region",
    "DOJ",
    "Assignment Status Type",
    "Final Rating  20-21",
    "Final Rating  21-22",
    "Final Rating  22-23",
    "Final Rating  23-24",
    "Last Promotion date",
    "Rating 24-25",
    "Experience Prior to Tata Play",
    "Tata Play Experience",
    "Total Yrs Exp",
    "Previous company",
    "MT Batch",
    "Highest Qualification",
    "University Name"
]
KEY_RENAMES = {
    "Employee Code": "employee code",
    "FIRST NAME": "first name",
    "LAST NAME": "last name",
    "GRADE": "grade",
    "Grade Level": "grade level",
    "Designation": "designation",
    "DEPARTMENT": "department",
    "SUB-DEPT": "sub department",
    "Location": "location",
    "Office": "office",
    "Region": "region",
    "DOJ": "date of joining",
    "Assignment Status Type": "assignment status type",
    "Final Rating  20-21": "final rating 20-21",
    "Final Rating  21-22": "final rating 21-22",
    "Final Rating  22-23": "final rating 22-23",
    "Final Rating  23-24": "final rating 23-24",
    "Last Promotion date": "last promotion date",
    "Rating 24-25": "rating 24-25",
    "Experience Prior to Tata Play": "experience prior to tata play",
    "Tata Play Experience": "tata play experience",
    "Total Yrs Exp": "total years experience",
    "Previous company": "previous company",
    "MT Batch": "mt batch",
    "Highest Qualification": "highest qualification",
    "University Name": "university name"
}
NUMERIC_FIELDS = [
    "employee code",
    "final rating 20-21",
    "final rating 21-22",
    "final rating 22-23",
    "final rating 23-24",
    "rating 24-25",
    "experience prior to tata play",
    "tata play experience",
    "total years experience",
    "mt batch"
]
DATE_FIELDS = [
    "date of joining",
    "last promotion date"
]

In [33]:
raw_docs = []

# Convert each DF row → raw dict
for idx, row in df.iterrows():
    raw_doc = row.to_dict()


    raw_docs.append(raw_doc)

# Normalize
normalized_docs = [
    normalize_doc_generic(
        doc,
        FIELDS,
        KEY_RENAMES,
        NUMERIC_FIELDS,
        DATE_FIELDS
    )
    for doc in raw_docs
]

In [34]:
normalized_docs

[{'employee code': 1004,
  'first name': 'Gyanendra',
  'last name': 'Singh',
  'grade': 'M5',
  'grade level': 'M5a',
  'designation': 'Assistant Manager - Quality',
  'department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'location': 'Lucknow',
  'office': 'Lucknow',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 3,
  'final rating 22-23': 3,
  'final rating 23-24': 3,
  'last promotion date': None,
  'rating 24-25': 3,
  'experience prior to tata play': 13,
  'tata play experience': 19,
  'total years experience': 32,
  'previous company': 'Adonis Electronics Pvt. Ltd.',
  'mt batch': None,
  'highest qualification': 'Diploma (Electrical Engineering)',
  'university name': 'Board of Technical Education, U.P.'},
 {'employee code': 1034,
  'first name': 'Monoranjon',
  'last name': 'Dutta',
  'grade': 'M4',
  'grade level': 'M4a',
  'designation': 'Senior Manager - Field Service Delivery',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'location': 'Kolkata',
  'office': 'Kolkata',
  'region': 'East',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 4,
  'final rating 22-23': 4,
  'final rating 23-24': 3,
  'last promotion date': datetime.datetime(2014, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 8,
  'tata play experience': 19,
  'total years experience': 28,
  'previous company': 'Usha International Ltd',
  'mt batch': None,
  'highest qualification': 'BA',
  'university name': 'Guwahati University'},
 {'employee code': 1045,
  'first name': 'Metilda Molly',
  'last name': 'Thomas',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - Customer Operations',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'location': 'Bangalore',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 3,
  'final rating 22-23': 3,
  'final rating 23-24': 3,
  'last promotion date': datetime.datetime(2012, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 4,
  'tata play experience': 19,
  'total years experience': 24,
  'previous company': 'Vertebrand Management Ltd',
  'mt batch': None,
  'highest qualification': 'BA',
  'university name': 'Bangalore University'},
 {'employee code': 1060,
  'first name': 'Thangudu',
  'last name': 'Srinivasa Rao',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - Field Service Delivery',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'location': 'Bangalore',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 4,
  'final rating 21-22': 4,
  'final rating 22-23': 4,
  'final rating 23-24': 4,
  'last promotion date': datetime.datetime(2022, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 7,
  'tata play experience': 19,
  'total years experience': 26,
  'previous company': 'M.K. Manpower Services Pvt. Ltd',
  'mt batch': None,
  'highest qualification': 'National Trade Certificate',
  'university name': 'National Council for Vocational Training'},
 {'employee code': 107,
  'first name': 'Chirag P.',
  'last name': 'Thakar',
  'grade': 'M3',
  'grade level': 'M3b',
  'designation': 'Assistant General Manager - Finance',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'location': 'Mumbai',
  'office': 'Corporate',
  'region': 'Corporate',
  'date of joining': datetime.datetime(2005, 9, 20, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 3,
  'final rating 22-23': 4,
  'final rating 23-24': 3,
  'last promotion date': datetime.datetime(2019, 5, 2, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 4,
  'tata play experience': 20,
  'total years experience': 24,
  'previous company': 'ITC Ltd.',
  'mt batch': None,
  'highest qualification': 'B. Com',
  'university name': 'Mumbai University'},
 {'employee code': 1088,
  'first name': 'Arun',
  'last name': 'Dharampal',
  'grade': 'M5',
  'grade level': 'M5b',
  'designation': 'Senior Executive - Field Service Delivery',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'location': 'Delhi',
  'office': 'Noida',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 3,
  'final rating 22-23': 3,
  'final rating 23-24': 3,
  'last promotion date': datetime.datetime(2024, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 9,
  'tata play experience': 19,
  'total years experience': 28,
  'previous company': 'Prolease Staffing Services Pvt. Ltd.',
  'mt batch': None,
  'highest qualification': 'National Trade Certificate',
  'university name': 'National Council for Vocational Training'},
 {'employee code': 1107,
  'first name': 'Ravi Pratap',
  'last name': 'Singh',
  'grade': 'M5',
  'grade level': 'M5a',
  'designation': 'Assistant Manager - Field Service Delivery',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'location': 'Delhi',
  'office': 'Noida',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 4,
  'final rating 22-23': 4,
  'final rating 23-24': 4,
  'last promotion date': datetime.datetime(2022, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 3,
  'tata play experience': 19,
  'total years experience': 23,
  'previous company': 'Prolease Staffing Services Pvt. Ltd.',
  'mt batch': None,
  'highest qualification': 'Diploma (Electronics Engineering)',
  'university name': 'Board of Technical Education, U.P.'},
 {'employee code': 1130,
  'first name': 'Tanuja',
  'last name': 'S.',
  'grade': 'M5',
  'grade level': 'M5a',
  'designation': 'Assistant Manager - Customer Operations',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'location': 'Bangalore',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 4, 17, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 3,
  'final rating 22-23': 4,
  'final rating 23-24': 3,
  'last promotion date': None,
  'rating 24-25': 3,
  'experience prior to tata play': 7,
  'tata play experience': 19,
  'total years experience': 27,
  'previous company': 'Adishwar India Ltd',
  'mt batch': None,
  'highest qualification': 'B. Sc',
  'university name': 'Osmania University'},
 {'employee code': 1182,
  'first name': 'Munesh',
  'last name': 'Singh Jamwal',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - Field Service Delivery',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'location': 'Jalandhar',
  'office': 'Mohali',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 4,
  'final rating 21-22': 4,
  'final rating 22-23': 4,
  'final rating 23-24': 4,
  'last promotion date': datetime.datetime(2022, 4, 1, 0, 0),
  'rating 24-25': 4,
  'experience prior to tata play': 1,
  'tata play experience': 19,
  'total years experience': 20,
  'previous company': 'Rikhi Enterprises',
  'mt batch': None,
  'highest qualification': 'National Trade Certificate',
  'university name': 'National Council for Vocational Training'},
 {'employee code': 1187,
  'first name': 'Tajinder Pal',
  'last name': 'Singh',
  'grade': 'M2',
  'grade level': 'M2a',
  'designation': 'Senior Vice President - Head Broadcast Engineering',
  'department': 'Technology',
  'sub department': 'Broadcast/OTT Engineering',
  'location': 'Delhi',
  'office': 'Chattarpur',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 4,
  'final rating 21-22': 4,
  'final rating 22-23': 3,
  'final rating 23-24': 3,
  'last promotion date': datetime.datetime(2019, 4, 1, 0, 0),
  'rating 24-25': 4,
  'experience prior to tata play': 5,
  'tata play experience': 19,
  'total years experience': 25,
  'previous company': 'Ideal Broadcasting (I) Pvt. Ltd',
  'mt batch': None,
  'highest qualification': 'B. Tech (Electrical)',
  'university name': 'Shivaji University, Kolhapur'},
 {'employee code': 1192,
  'first name': 'Jaipal',
  'last name': 'Singh Bhandari',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - Repair Centre',
  'department': 'Technology',
  'sub department': 'Consumer Technology',
  'location': 'Delhi',
  'office': 'Chattarpur',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 4,
  'final rating 21-22': 3,
  'final rating 22-23': 3,
  'final rating 23-24': 3,
  'last promotion date': datetime.datetime(2016, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 9,
  'tata play experience': 19,
  'total years experience': 29,
  'previous company': 'Hathway Cable & Datacom Pvt. Ltd.',
  'mt batch': None,
  'highest qualification': 'National Trade Certificate',
  'university name': 'National Council for Vocational Training'},
 {'employee code': 1205,
  'first name': 'Vijay',
  'last name': 'Khera',
  'grade': 'M3',
  'grade level': 'M3a',
  'designation': 'General Manager - MIS & Business Information',
  'department': 'Field Service Delivery',
  'sub department': 'MIS & Business Information',
  'location': 'Noida',
  'office': 'Noida',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 4,
  'final rating 22-23': 3,
  'final rating 23-24': 3,
  'last promotion date': datetime.datetime(2017, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 15,
  'tata play experience': 19,
  'total years experience': 34,
  'previous company': 'Procall Pvt. Ltd.',
  'mt batch': None,
  'highest qualification': 'Post Graduate Diploma in Business Administration',
  'university name': 'Symbiosis Centre for Distance Learning, Pune'},
 {'employee code': 1213,
  'first name': 'Praveen',
  'last name': 'Singh',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - Field Service Delivery',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'location': 'Ludhiana',
  'office': 'Mohali',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 3,
  'final rating 22-23': 3,
  'final rating 23-24': 3,
  'last promotion date': datetime.datetime(2022, 4, 1, 0, 0),
  'rating 24-25': 2,
  'experience prior to tata play': 8,
  'tata play experience': 19,
  'total years experience': 27,
  'previous company': 'Raj Customer Care Centre',
  'mt batch': None,
  'highest qualification': 'BALLB',
  'university name': 'Ch. Charan Singh University, Meerut'},
 {'employee code': 1252,
  'first name': 'Soumya',
  'last name': 'Swamy',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - Field Service Delivery',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'location': 'Bangalore',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 3,
  'final rating 22-23': 3,
  'final rating 23-24': 3,
  'last promotion date': datetime.datetime(2019, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 3,
  'tata play experience': 19,
  'total years experience': 22,
  'previous company': 'Bharti Televentures Ltd.',
  'mt batch': None,
  'highest qualification': 'B. Sc',
  'university name': 'Bangalore University'},
 {'employee code': 1308,
  'first name': 'R.',
  'last name': 'Jayaprakash',
  'grade': 'M3',
  'grade level': 'M3a',
  'designation': 'General Manager - Finance',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'location': 'Bangalore',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 2, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 4,
  'final rating 22-23': 4,
  'final rating 23-24': 4,
  'last promotion date': datetime.datetime(2012, 4, 1, 0, 0),
  'rating 24-25': 4,
  'experience prior to tata play': 17,
  'tata play experience': 19,
  'total years experience': 36,
  'previous company': 'Asian Paints Ltd.',
  'mt batch': None,
  'highest qualification': 'B. Sc',
  'university name': 'Bharathiar University'},
 {'employee code': 1313,
  'first name': 'Lenin',
  'last name': 'Suresh Raj',
  'grade': 'M3',
  'grade level': 'M3b',
  'designation': 'Assistant General Manager - Business Intelligence and Forecasting',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'location': 'Bangalore',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 2, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 4,
  'final rating 21-22': 4,
  'final rating 22-23': 4,
  'final rating 23-24': 4,
  'last promotion date': datetime.datetime(2021, 4, 1, 0, 0),
  'rating 24-25': 4,
  'experience prior to tata play': 6,
  'tata play experience': 19,
  'total years experience': 25,
  'previous company': 'Hutchison Essar Ltd.',
  'mt batch': None,
  'highest qualification': 'B. Com',
  'university name': 'Bangalore University'},
 {'employee code': 1314,
  'first name': 'Ponselvam',
  'last name': 'Devasagayam',
  'grade': 'M5',
  'grade level': 'M5a',
  'designation': 'Assistant Manager - NVSD Customer Admin',
  'department': 'Customer Operations',
  'sub department': 'N.V.S.D',
  'location': 'Bangalore',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 2, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 4,
  'final rating 21-22': 4,
  'final rating 22-23': 4,
  'final rating 23-24': 4,
  'last promotion date': datetime.datetime(2023, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 3,
  'tata play experience': 19,
  'total years experience': 22,
  'previous company': 'Hutchison Essar Ltd.',
  'mt batch': None,
  'highest qualification': 'B. Sc',
  'university name': 'Bangalore University'},
 {'employee code': 1345,
  'first name': 'Jaya',
  'last name': 'N.',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - MIS & Reporting-Sales',
  'department': 'Sales',
  'sub department': 'MIS & Reporting-Sales',
  'location': 'Bangalore',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 2, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 4,
  'final rating 21-22': 3,
  'final rating 22-23': 3,
  'final rating 23-24': 4,
  'last promotion date': datetime.datetime(2019, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': None,
  'tata play experience': 19,
  'total years experience': 19,
  'previous company': 'Fresher',
  'mt batch': None,
  'highest qualification': 'B. Com',
  'university name': 'Bangalore University'},
 {'employee code': 1363,
  'first name': 'Anup P.',
  'last name': 'Lobo',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - Service Training',
  'department': 'Field Service Delivery',
  'sub department': 'Service Training - FSD',
  'location': 'Bangalore',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 8, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 4,
  'final rating 22-23': 4,
  'final rating 23-24': 4,
  'last promotion date': datetime.datetime(2023, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 9,
  'tata play experience': 19,
  'total years experience': 28,
  'previous company': 'Teletronics',
  'mt batch': None,
  'highest qualification': 'National Trade Certificate',
  'university name': 'National Council for Vocational Training'},
 {'employee code': 1377,
  'first name': 'B.P.',
  'last name': 'Tharamani',
  'grade': 'M5',
  'grade level': 'M5a',
  'designation': 'Assistant Manager - Vendor Management & Outbound Billing Operations',
  'department': 'Customer Operations',
  'sub department': 'Budgeting & AOP',
  'location': 'Bangalore',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 8, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 3,
  'final rating 22-23': 3,
  'final rating 23-24': 4,
  'last promotion date': datetime.datetime(2020, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 1,
  'tata play experience': 19,
  'total years experience': 20,
  'previous company': 'Enterprise Logic (I) Pvt. Ltd',
  'mt batch': None,
  'highest qualification': 'B. Com',
  'university name': 'Bangalore University'},
 {'employee code': 1382,
  'first name': 'C. Sheik Mehaboob',
  'last name': 'Basha',
  'grade': 'M4',
  'grade level': 'M4a',
  'designation': 'Senior Manager - Service Training',
  'department': 'Field Service Delivery',
  'sub department': 'Service Training - FSD',
  'location': 'Delhi',
  'office': 'Noida',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 5, 8, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 3,
  'final rating 21-22': 3,
  'final rating 22-23': 3,
  'final rating 23-24': 3,
  'last promotion date': datetime.datetime(2023, 4, 1, 0, 0),
  'rating 24-25': 3,
  'experience prior to tata play': 3,
  'tata play experience': 19,
  'total years experience': 22,
  'previous company': 'Manpower Services India Pvt. Ltd',
  'mt batch': None,
  'highest qualification': 'National Trade Certificate',
  'university name': 'National Council for Vocational Training'},
 {'employee code': 1404,
  'first name': 'Robin',
  'last name': 'Thomas',
  'grade': 'M4',
  'grade level': 'M4a',
  'designation': 'Senior Manager - Service Training',
  'department': 'Field Service Delivery',
  'sub department': 'Service Training - FSD',
  'location': 'Delhi',
  'office': 'Noida',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 5, 15, 0, 0),
  'assignment status type': 'ACTIVE',
  'final rating 20-21': 4,
  'final rating 21-22': 4,
  'final rating 22-23': 4,
  'final rating 23-24': 3,
  'last promotion date': datetime.datetime(2022, 4, 1, 0, 0),
  'rating 24-25': 4,
  'experience prior to tata play': 6,
  'tata play experience': 19,
  'total years experience': 25,
  'previous company': 'Samsung Authorised Service Centre',
  'mt batch': None,
  'highest qualification': 'National Trade Certificate',
  'university name': 'National Council for Vocational Training'},
 {'employee code': 1413,
  'first name': 'Tejbir',
  'last name': 'Singh',
  'grade': 'M5',
  'grade level': 'M5b',
  'designation': 'Senior Executive - Quality',
  'department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'location': 'Delhi',
  'office': 'Chattarpur',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 5, 15, 0, 0),

In [36]:
dst = db[collection]
result = dst.insert_many(normalized_docs)

## Ddata/Performance 360 degree Feedback participants status - All.xlsx

In [38]:
path="Ddata/Performance 360 degree Feedback participants status - All.xlsx"
collection="performance_360_degree_feedback_participants_status_all"
df=pd.read_excel(path)

In [39]:
df.columns

Index(['Person Number', 'Name', 'Parent Grade', 'Business Unit Name',
       'Parent Department', 'Department Name', 'Performance Document Name',
       'Participant Name', 'Role', 'Role Status', 'Participation Status'],
      dtype='object')

In [40]:
FIELDS = [
    "Person Number",
    "Name",
    "Parent Grade",
    "Business Unit Name",
    "Parent Department",
    "Department Name",
    "Performance Document Name",
    "Participant Name",
    "Role",
    "Role Status",
    "Participation Status"
]
KEY_RENAMES = {
    "Person Number": "employee code",
    "Name": "employee name",
    "Parent Grade": "grade",
    "Business Unit Name": "region",
    "Parent Department": "department",
    "Department Name": "sub department",
    "Performance Document Name": "performance document name",
    "Participant Name": "participant name",
    "Role": "role",
    "Role Status": "role status",
    "Participation Status": "participation status"
}
NUMERIC_FIELDS = [
    "employee code"
]
DATE_FIELDS = []

In [41]:
raw_docs = []

# Convert each DF row → raw dict
for idx, row in df.iterrows():
    raw_doc = row.to_dict()


    raw_docs.append(raw_doc)

# Normalize
normalized_docs = [
    normalize_doc_generic(
        doc,
        FIELDS,
        KEY_RENAMES,
        NUMERIC_FIELDS,
        DATE_FIELDS
    )
    for doc in raw_docs
]

In [42]:
normalized_docs

[{'employee code': 107,
  'employee name': 'Chirag P. Thakar',
  'grade': 'M3',
  'region': 'Corporate',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (Individual Contributor)',
  'participant name': 'Avinash Kesherwani',
  'role': 'Manager',
  'role status': 'Active',
  'participation status': 'Not Started'},
 {'employee code': 107,
  'employee name': 'Chirag P. Thakar',
  'grade': 'M3',
  'region': 'Corporate',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (Individual Contributor)',
  'participant name': 'Chirag P. Thakar',
  'role': 'Worker',
  'role status': 'Active',
  'participation status': 'Not Started'},
 {'employee code': 107,
  'employee name': 'Chirag P. Thakar',
  'grade': 'M3',
  'region': 'Corporate',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (Individual Contributor)',
  'participant name': 'Jisha Nair',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 107,
  'employee name': 'Chirag P. Thakar',
  'grade': 'M3',
  'region': 'Corporate',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (Individual Contributor)',
  'participant name': 'Manish Chopra',
  'role': 'Other',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 107,
  'employee name': 'Chirag P. Thakar',
  'grade': 'M3',
  'region': 'Corporate',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (Individual Contributor)',
  'participant name': 'Prashant Deshmukh',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 107,
  'employee name': 'Chirag P. Thakar',
  'grade': 'M3',
  'region': 'Corporate',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (Individual Contributor)',
  'participant name': 'V. Aanand',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1187,
  'employee name': 'Tajinder Pal Singh',
  'grade': 'M1',
  'region': 'North',
  'department': 'Technology',
  'sub department': 'Technology - General',
  'performance document name': 'Anchor Competency 360 Feedback - M2 - 2025 (People Manager)',
  'participant name': 'Abhishek Pathak',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1187,
  'employee name': 'Tajinder Pal Singh',
  'grade': 'M1',
  'region': 'North',
  'department': 'Technology',
  'sub department': 'Technology - General',
  'performance document name': 'Anchor Competency 360 Feedback - M2 - 2025 (People Manager)',
  'participant name': 'Anand Prakash',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1187,
  'employee name': 'Tajinder Pal Singh',
  'grade': 'M1',
  'region': 'North',
  'department': 'Technology',
  'sub department': 'Technology - General',
  'performance document name': 'Anchor Competency 360 Feedback - M2 - 2025 (People Manager)',
  'participant name': 'Harit Nagpal',
  'role': 'Manager',
  'role status': 'Active',
  'participation status': 'Not Started'},
 {'employee code': 1187,
  'employee name': 'Tajinder Pal Singh',
  'grade': 'M1',
  'region': 'North',
  'department': 'Technology',
  'sub department': 'Technology - General',
  'performance document name': 'Anchor Competency 360 Feedback - M2 - 2025 (People Manager)',
  'participant name': 'Naveen Goel',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1187,
  'employee name': 'Tajinder Pal Singh',
  'grade': 'M1',
  'region': 'North',
  'department': 'Technology',
  'sub department': 'Technology - General',
  'performance document name': 'Anchor Competency 360 Feedback - M2 - 2025 (People Manager)',
  'participant name': 'Suman Kumar Ghosh',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1187,
  'employee name': 'Tajinder Pal Singh',
  'grade': 'M1',
  'region': 'North',
  'department': 'Technology',
  'sub department': 'Technology - General',
  'performance document name': 'Anchor Competency 360 Feedback - M2 - 2025 (People Manager)',
  'participant name': 'Tajinder Pal Singh',
  'role': 'Worker',
  'role status': 'Active',
  'participation status': 'Not Started'},
 {'employee code': 1187,
  'employee name': 'Tajinder Pal Singh',
  'grade': 'M1',
  'region': 'North',
  'department': 'Technology',
  'sub department': 'Technology - General',
  'performance document name': 'Anchor Competency 360 Feedback - M2 - 2025 (People Manager)',
  'participant name': 'Vinati Malik',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1205,
  'employee name': 'Vijay Khera',
  'grade': 'M3',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'MIS & Business Information',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Arun Mishra',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1205,
  'employee name': 'Vijay Khera',
  'grade': 'M3',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'MIS & Business Information',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Ashish Jain',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1205,
  'employee name': 'Vijay Khera',
  'grade': 'M3',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'MIS & Business Information',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Gurdeep Singh Bhuie',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1205,
  'employee name': 'Vijay Khera',
  'grade': 'M3',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'MIS & Business Information',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Krishan Kansal',
  'role': 'Manager',
  'role status': 'Active',
  'participation status': 'Not Started'},
 {'employee code': 1205,
  'employee name': 'Vijay Khera',
  'grade': 'M3',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'MIS & Business Information',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Prashant Deshmukh',
  'role': 'Other',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1205,
  'employee name': 'Vijay Khera',
  'grade': 'M3',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'MIS & Business Information',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Praveen Ahuja',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1205,
  'employee name': 'Vijay Khera',
  'grade': 'M3',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'MIS & Business Information',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Vijay Khera',
  'role': 'Worker',
  'role status': 'Active',
  'participation status': 'Not Started'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Ajay Kumar',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Akash Nag M B',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Ch.S.V.R. Kumar',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Lenin Suresh Raj',
  'role': 'Worker',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Paul James Kennedy',
  'role': 'Other',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'R. Layeeq Ahmed',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Roopa S. Hiremath',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Sapthagiri N',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Vinodkumar Anandan',
  'role': 'Manager',
  'role status': 'Active',
  'participation status': 'Not Started'},
 {'employee code': 1423,
  'employee name': 'Ashok Kumar Thakur',
  'grade': 'M3',
  'region': 'North',
  'department': 'Finance',
  'sub department': 'Supply Chain Services',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (Individual Contributor)',
  'participant name': 'Ashok Kumar Thakur',
  'role': 'Worker',
  'role status': 'Active',
  'participation status': 'Not Started'},
 {'employee code': 1423,
  'employee name': 'Ashok Kumar Thakur',
  'grade': 'M3',
  'region': 'North',
  'department': 'Finance',
  'sub department': 'Supply Chain Services',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (Individual Contributor)',
  'participant name': 'Devinder Singh',
  'role': 'Manager',
  'role status': 'Active',
  'participation status': 'Not Started'},
 {'employee code': 1434,
  'employee name': 'Abdul Rahim Nazar',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'COSSG',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Abdul Rahim Nazar',
  'role': 'Worker',
  'role status': 'Active',
  'participation status': 'In progress'},
 {'employee code': 1434,
  'employee name': 'Abdul Rahim Nazar',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'COSSG',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Haripriya P',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1434,
  'employee name': 'Abdul Rahim Nazar',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'COSSG',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Kishore Kumar B.',
  'role': 'Other',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1434,
  'employee name': 'Abdul Rahim Nazar',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'COSSG',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Lenin Suresh Raj',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1434,
  'employee name': 'Abdul Rahim Nazar',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'COSSG',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Lokesh K.',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1434,
  'employee name': 'Abdul Rahim Nazar',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'COSSG',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Reema Kukreja',
  'role': 'Manager',
  'role status': 'Active',
  'participation status': 'Not Started'},
 {'employee code': 1434,
  'employee name': 'Abdul Rahim Nazar',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'COSSG',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Shrinidhi DC',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1434,
  'employee name': 'Abdul Rahim Nazar',
  'grade': 'M3',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'COSSG',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Vasumathy S.',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'grade': 'M3',
  'region': 'East',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Abhishek Das',
  'role': 'Other',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'grade': 'M3',
  'region': 'East',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Atanu Bora',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'grade': 'M3',
  'region': 'East',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Joydeep Roy',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'grade': 'M3',
  'region': 'East',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Monalisa Boruah',
  'role': 'Worker',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'grade': 'M3',
  'region': 'East',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Rishav Sarmah',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'grade': 'M3',
  'region': 'East',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Sarbojit Sarkar',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Completed'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'grade': 'M3',
  'region': 'East',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Sujit Mondal',
  'role': 'Manager',
  'role status': 'Active',
  'participation status': 'Not Started'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'grade': 'M3',
  'region': 'East',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Ujjal Kakati',
  'role': 'Direct Report',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'grade': 'M3',
  'region': 'East',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'performance document name': 'Anchor Competency 360 Feedback - M3 - 2025 (People Manager)',
  'participant name': 'Vikram Singh',
  'role': 'Peer',
  'role status': 'Active',
  'participation status': 'Awaiting Reply'},
 {'employee code': 1480,
  'employee name': 'Sanjay Mittal',
  'grade': 'M2',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',

In [43]:
dst = db[collection]
result = dst.insert_many(normalized_docs)

## Ddata/PIP Transaction Report.xls

In [59]:


path="Ddata/PIP Transaction Report.xls"
collection="pip_transaction_report"
df=pd.read_excel(path)

In [60]:
df['Assigned To'] = df['Assigned To'].fillna('')

In [61]:
df.columns

Index(['PERSON_NUMBER', 'First_Name', 'Last_Name', 'Employee_Email_ID',
       'Parent_Grade', 'Sub_grade', 'Designation', 'SUB_DEPARTMENT',
       'Office_Location', 'Region', 'DOJ', 'Manager_Number', 'MAN_EMAIL',
       'PIP Submitted Date', 'PIP Completion Date', 'RHR_NAME', 'RHR_Number',
       'RHR_EMAIL', 'Reviewer_NAME', 'Reviewer_Number', 'Reviewer_EMAIL',
       'PIP Submitted Date.1', 'PIP Completion date', 'Assigned Date',
       'Assigned To', '\t\nTask status', 'PIP Doc status'],
      dtype='object')

In [49]:
# removed 2 duplicate columns
FIELDS = [
    "PERSON_NUMBER",
    "First_Name",
    "Last_Name",
    "Employee_Email_ID",
    "Parent_Grade",
    "Sub_grade",
    "Designation",
    "SUB_DEPARTMENT",
    "Office_Location",
    "Region",
    "DOJ",
    "Manager_Number",
    "MAN_EMAIL",
    "PIP Submitted Date",
    "PIP Completion Date",
    "RHR_NAME",
    "RHR_Number",
    "RHR_EMAIL",
    "Reviewer_NAME",
    "Reviewer_Number",
    "Reviewer_EMAIL",
    "Assigned Date",
    "Assigned To",
    "\t\nTask status",
    "PIP Doc status"
]

KEY_RENAMES = {
    "PERSON_NUMBER": "employee code",
    "First_Name": "first name",
    "Last_Name": "last name",
    "Employee_Email_ID": "employee email",
    "Parent_Grade": "grade",
    "Sub_grade": "grade level",
    "Designation": "designation",
    "SUB_DEPARTMENT": "sub department",
    "Office_Location": "office",
    "Region": "region",
    "DOJ": "date of joining",
    "Manager_Number": "manager employee code",
    "MAN_EMAIL": "manager email",
    "PIP Submitted Date": "pip submitted date",
    "PIP Completion Date": "pip completion date",
    "RHR_NAME": "rhr name",
    "RHR_Number": "rhr employee code",
    "RHR_EMAIL": "rhr email",
    "Reviewer_NAME": "reviewer name",
    "Reviewer_Number": "reviewer employee code",
    "Reviewer_EMAIL": "reviewer email",
    "Assigned Date": "assigned date",
    "Assigned To": "assigned to",
    "\t\nTask status": "task status",
    "PIP Doc status": "pip document status"
}

NUMERIC_FIELDS = [
    "employee code",
    "manager employee code",
    "rhr employee code",
    "reviewer employee code"
]

DATE_FIELDS = [
    "date of joining",
    "pip submitted date",
    "pip completion date",
    "assigned date"
]

In [62]:
raw_docs = []

# Convert each DF row → raw dict
for idx, row in df.iterrows():
    raw_doc = row.to_dict()


    raw_docs.append(raw_doc)

# Normalize
normalized_docs = [
    normalize_doc_generic(
        doc,
        FIELDS,
        KEY_RENAMES,
        NUMERIC_FIELDS,
        DATE_FIELDS
    )
    for doc in raw_docs
]

In [63]:
normalized_docs

[{'employee code': 3159,
  'first name': 'Kalpesh Kumar',
  'last name': 'Sagar',
  'employee email': 'kalpeshkumar.sagar@tataplay.com',
  'grade': 'M5',
  'grade level': 'M5b',
  'designation': 'Senior Executive - Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'office': 'Ahmedabad',
  'region': 'West',
  'date of joining': datetime.datetime(2011, 7, 4, 0, 0),
  'manager employee code': 4735,
  'manager email': 'Sandesh.Patel@tataplay.com',
  'pip submitted date': datetime.datetime(2024, 11, 28, 0, 0),
  'pip completion date': datetime.datetime(2024, 8, 20, 0, 0),
  'rhr name': 'Pramatesh V. Kumar',
  'rhr employee code': 871,
  'rhr email': 'pramateshk@tataplay.com',
  'reviewer name': 'Vikas Chugh',
  'reviewer employee code': 299,
  'reviewer email': 'vikasc@tataplay.com',
  'assigned date': None,
  'assigned to': 'NA',
  'task status': 'COMPLETE',
  'pip document status': 'APPROVED'},
 {'employee code': 4015,
  'first name': 'Vivek',
  'last name': 'Chaudhry',
  'employee email': 'vivek.chaudhry@tataplay.com',
  'grade': 'M5',
  'grade level': 'M5b',
  'designation': 'Senior Broadcast Operations Engineer',
  'sub department': 'Technical Operations & RF Engineering',
  'office': 'Chattarpur',
  'region': 'North',
  'date of joining': datetime.datetime(2013, 7, 22, 0, 0),
  'manager employee code': 2424,
  'manager email': 'kamal.singh@tataplay.com',
  'pip submitted date': datetime.datetime(2025, 6, 4, 0, 0),
  'pip completion date': datetime.datetime(2024, 1, 8, 0, 0),
  'rhr name': 'Atul Singh',
  'rhr employee code': 7565,
  'rhr email': 'atul.singh@tataplay.com',
  'reviewer name': 'Chanchal Bhardwaj',
  'reviewer employee code': 2343,
  'reviewer email': 'chanchalb@tataplay.com',
  'assigned date': None,
  'assigned to': 'NA',
  'task status': 'COMPLETE',
  'pip document status': 'APPROVED'},
 {'employee code': 6689,
  'first name': 'Rajesh',
  'last name': 'R',
  'employee email': 'Rajesh.R2@tataplay.com',
  'grade': 'M5',
  'grade level': 'M5a',
  'designation': 'Assistant Manager - Trade Sales',
  'sub department': 'Trade Sales',
  'office': 'Chennai',
  'region': 'South',
  'date of joining': datetime.datetime(2021, 3, 17, 0, 0),
  'manager employee code': 5828,
  'manager email': 'Srinivasulu.Bharani@tataplay.com',
  'pip submitted date': datetime.datetime(2025, 3, 20, 0, 0),
  'pip completion date': datetime.datetime(2024, 12, 6, 0, 0),
  'rhr name': 'Atul Goyal',
  'rhr employee code': 4146,
  'rhr email': 'atul.goyal@tataplay.com',
  'reviewer name': 'Vivek Damodaran E',
  'reviewer employee code': 7494,
  'reviewer email': 'vivek.damodarane@tataplay.com',
  'assigned date': datetime.datetime(2025, 3, 20, 0, 0),
  'assigned to': 'Atul Goyal',
  'task status': 'ASSIGNED',
  'pip document status': 'PENDING'},
 {'employee code': 6689,
  'first name': 'Rajesh',
  'last name': 'R',
  'employee email': 'Rajesh.R2@tataplay.com',
  'grade': 'M5',
  'grade level': 'M5a',
  'designation': 'Assistant Manager - Trade Sales',
  'sub department': 'Trade Sales',
  'office': 'Chennai',
  'region': 'South',
  'date of joining': datetime.datetime(2021, 3, 17, 0, 0),
  'manager employee code': 5828,
  'manager email': 'Srinivasulu.Bharani@tataplay.com',
  'pip submitted date': datetime.datetime(2025, 3, 20, 0, 0),
  'pip completion date': datetime.datetime(2024, 12, 6, 0, 0),
  'rhr name': 'Atul Goyal',
  'rhr employee code': 4146,
  'rhr email': 'atul.goyal@tataplay.com',
  'reviewer name': 'Vivek Damodaran E',
  'reviewer employee code': 7494,
  'reviewer email': 'vivek.damodarane@tataplay.com',
  'assigned date': datetime.datetime(2025, 3, 20, 0, 0),
  'assigned to': 'Vivek Damodaran E',
  'task status': 'ASSIGNED',
  'pip document status': 'PENDING'},
 {'employee code': 7025,
  'first name': 'Sachin',
  'last name': 'V',
  'employee email': 'Sachin.V@tataplay.com',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - Budgeting & AOP',
  'sub department': 'Budgeting & AOP',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2021, 10, 18, 0, 0),
  'manager employee code': 5007,
  'manager email': 'Srinidhi.DC@tataplay.com',
  'pip submitted date': datetime.datetime(2024, 12, 31, 0, 0),
  'pip completion date': datetime.datetime(2024, 9, 17, 0, 0),
  'rhr name': 'Atul Goyal',
  'rhr employee code': 4146,
  'rhr email': 'atul.goyal@tataplay.com',
  'reviewer name': 'Pavan Kumar Muktapuram',
  'reviewer employee code': 2039,
  'reviewer email': 'pavankum@tataplay.com',
  'assigned date': None,
  'assigned to': 'NA',
  'task status': 'COMPLETE',
  'pip document status': 'APPROVED'},
 {'employee code': 7376,
  'first name': 'Raj',
  'last name': 'Kumar',
  'employee email': 'raj.kumar@tataplay.com',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - Trade Marketing',
  'sub department': 'Trade Marketing',
  'office': 'Jaipur',
  'region': 'North',
  'date of joining': datetime.datetime(2022, 8, 25, 0, 0),
  'manager employee code': 2382,
  'manager email': 'nishchalv@tataplay.com',
  'pip submitted date': None,
  'pip completion date': datetime.datetime(2023, 6, 6, 0, 0),
  'rhr name': 'Atul Singh',
  'rhr employee code': 7565,
  'rhr email': 'atul.singh@tataplay.com',
  'reviewer name': 'Rajeev Pathak',
  'reviewer employee code': 751,
  'reviewer email': 'rajeevp@tataplay.com',
  'assigned date': None,
  'assigned to': 'NA',
  'task status': 'INITIAL',
  'pip document status': 'DRAFT'},
 {'employee code': 7376,
  'first name': 'Raj',
  'last name': 'Kumar',
  'employee email': 'raj.kumar@tataplay.com',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - Trade Marketing',
  'sub department': 'Trade Marketing',
  'office': 'Jaipur',
  'region': 'North',
  'date of joining': datetime.datetime(2022, 8, 25, 0, 0),
  'manager employee code': 2382,
  'manager email': 'nishchalv@tataplay.com',
  'pip submitted date': None,
  'pip completion date': datetime.datetime(2023, 6, 6, 0, 0),
  'rhr name': 'Atul Singh',
  'rhr employee code': 7565,
  'rhr email': 'atul.singh@tataplay.com',
  'reviewer name': 'Rajeev Pathak',
  'reviewer employee code': 751,
  'reviewer email': 'rajeevp@tataplay.com',
  'assigned date': None,
  'assigned to': 'NA',
  'task status': 'INITIAL',
  'pip document status': 'DRAFT'},
 {'employee code': 7891,
  'first name': 'Sanjeev',
  'last name': 'Kumar Singh',
  'employee email': 'sanjeev.kumarsingh@tataplay.com',
  'grade': 'M4',
  'grade level': 'M4b',
  'designation': 'Manager - Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'office': 'Patna',
  'region': 'East',
  'date of joining': datetime.datetime(2024, 6, 14, 0, 0),
  'manager employee code': 7413,
  'manager email': 'Vikrant.Singh@tataplay.com',
  'pip submitted date': datetime.datetime(2025, 7, 18, 0, 0),
  'pip completion date': datetime.datetime(2024, 12, 14, 0, 0),
  'rhr name': 'Atul Goyal',
  'rhr employee code': 4146,
  'rhr email': 'atul.goyal@tataplay.com',
  'reviewer name': 'Sujit Mondal',
  'reviewer employee code': 3631,
  'reviewer email': 'sujit.mondal@tataplay.com',
  'assigned date': None,
  'assigned to': 'NA',
  'task status': 'COMPLETE',
  'pip document status': 'APPROVED'}]

In [65]:
dst = db[collection]
result = dst.insert_many(normalized_docs)

## Ddata/PMS 360 Employee Report_PMS 360.xls

In [74]:
path="Ddata/PMS 360 Employee Report_PMS 360.xls"
collection="pms_360_employee_report_pms_360"
df=pd.read_excel(path,engine="xlrd")

XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'Date: Tu'

## Ddata/PMS Q2 25-26 Rating report - all.xlsx

In [6]:
path="../Ddata/PMS Q2 25-26 Rating report - all.xlsx"
collection="pms_q2_25_26_rating_report_all"
df=pd.read_excel(path,skiprows=2)

In [7]:
df.columns

Index(['Employee Person Number', 'Employee Name', 'Employee E-Mail Address',
       'Manager Person Number', 'Manager Name', 'Manager E-Mail Address',
       'Business Unit Name', 'Department', 'Parent Department', 'Grade',
       'Parent Grade', 'Job', 'Location Name', 'Performance Document Name',
       'Overall Manager Rating', 'Overall Employee Rating',
       'Performance Document Status'],
      dtype='object')

In [81]:
df

,Employee Person Number,Employee Name,Employee E-Mail Address,Manager Person Number,Manager Name,Manager E-Mail Address,Business Unit Name,Department,Parent Department,Grade,Parent Grade,Job,Location Name,Performance Document Name,Overall Manager Rating,Overall Employee Rating,Performance Document Status
0,1004.0,Gyanendra Singh,gyanendras@tataplay.com,2430.0,Vishal Sethi,vishal.sethi@tataplay.com,North,Field Engineering and Audit,Technology,M5a,M5,Assistant Manager - Quality,Lucknow,2025-26 – Q2/H1 (Mid Year),3.0,NaN,Completed
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,Completed
2,1034.0,Monoranjon Dutta,manoranjand@tataplay.com,4922.0,Joydeep Roy,Joydeep.Roy@tataplay.com,East,Field Service Delivery - General,Field Service Delivery,M4a,M4,Senior Manager - Field Service Delivery,Kolkata,2025-26 – Q2/H1 (Mid Year),3.0,NaN,Completed
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Completed
4,1045.0,Metilda Molly Thomas,mollyt@tataplay.com,5922.0,Nipun Sharma,Nipun.Sharma@tataplay.com,South,Customer Operations - General,Customer Operations,M4b,M4,Manager - Customer Operations,Hebbal,2025-26 – Q2/H1 (Mid Year),3.0,NaN,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Approved
2479,950.0,Dharmesh Shah,dharmeshs@tataplay.com,941.0,Jayesh Joshi,jayeshj@tataplay.com,West,Field Service Delivery - General,Field Service Delivery,M4b,M4,Manager - Field Service Delivery,Ahmedabad,2025-26 – Q2/H1 (Mid Year),2.0,NaN,Completed
2480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Completed
2481,997.0,Ramesh Rai,rameshr@tataplay.com,6471.0,Sadashiv Sharma,Sadashiv.Sharma@tataplay.com,North,Trade Sales,Sales,M5a,M5,Assistant Manager - Trade Sales,Noida,2025-26 – Q2/H1 (Mid Year),2.0,NaN,Completed
2482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Completed

In [ ]:
import pandas as pd

col = "Performance Document Status"

# List to store incorrect pairs
mismatches = []

# Iterate in steps of 2: (0,1), (2,3), (4,5), ...
for i in range(0, len(df), 2):
    if i + 1 < len(df):  # ensure pair exists
        v1 = df.loc[i, col]
        v2 = df.loc[i+1, col]

        if pd.isna(v1) or pd.isna(v2):
            continue  # skip if data missing (optional)

        if v1 != v2:
            print()
            mismatches.append((i, i+1, v1, v2))

# Final report
if mismatches:
    print("Mismatch found in the following row pairs:")
    for r1, r2, v1, v2 in mismatches:
        print(f"Rows {r1} & {r2}: '{v1}' != '{v2}'")
else:
    print("All row pairs match for Performance Document Status.")

Mismatch found in the following row pairs:
Rows 208 & 209: 'In progress' != 'Completed'
Rows 220 & 221: 'Completed' != 'Approved'
Rows 224 & 225: 'Approved' != 'Completed'
Rows 244 & 245: 'Completed' != 'In progress'
Rows 246 & 247: 'In progress' != 'Completed'
Rows 260 & 261: 'Completed' != 'In progress'
Rows 262 & 263: 'In progress' != 'Completed'
Rows 276 & 277: 'Completed' != 'Approved'
Rows 278 & 279: 'Approved' != 'Completed'
Rows 288 & 289: 'Completed' != 'In progress'
Rows 290 & 291: 'In progress' != 'Completed'
Rows 294 & 295: 'Completed' != 'Approved'
Rows 296 & 297: 'Approved' != 'Completed'
Rows 298 & 299: 'Completed' != 'In progress'
Rows 300 & 301: 'In progress' != 'Completed'
Rows 308 & 309: 'Completed' != 'Approved'
Rows 310 & 311: 'Approved' != 'Completed'
Rows 312 & 313: 'Completed' != 'Submitted'
Rows 314 & 315: 'Submitted' != 'Completed'
Rows 318 & 319: 'Completed' != 'In progress'
Rows 320 & 321: 'In progress' != 'Completed'
Rows 330 & 331: 'Completed' != 'Approved'
Rows 332 & 333: 'Approved' != 'Completed'
Rows 334 & 335: 'Completed' != 'Approved'
Rows 336 & 337: 'Approved' != 'Completed'
Rows 348 & 349: 'Completed' != 'Approved'
Rows 350 & 351: 'Approved' != 'Completed'
Rows 352 & 353: 'Completed' != 'In progress'
Rows 402 & 403: 'In progress' != 'Completed'
Rows 408 & 409: 'Completed' != 'In progress'
Rows 412 & 413: 'In progress' != 'Approved'
Rows 414 & 415: 'Approved' != 'In progress'
Rows 416 & 417: 'In progress' != 'Approved'
Rows 418 & 419: 'Approved' != 'Completed'
Rows 444 & 445: 'Completed' != 'Approved'
Rows 446 & 447: 'Approved' != 'Completed'
Rows 460 & 461: 'Completed' != 'In progress'
Rows 462 & 463: 'In progress' != 'Completed'
Rows 470 & 471: 'Completed' != 'In progress'
Rows 506 & 507: 'In progress' != 'Approved'
Rows 508 & 509: 'Approved' != 'Completed'
Rows 510 & 511: 'Completed' != 'In progress'
Rows 512 & 513: 'In progress' != 'Completed'
Rows 530 & 531: 'Completed' != 'Approved'
Rows 532 & 533: 'Approved' != 'Completed'
Rows 536 & 537: 'Completed' != 'Approved'
Rows 538 & 539: 'Approved' != 'Completed'
Rows 540 & 541: 'Completed' != 'In progress'
Rows 604 & 605: 'In progress' != 'Completed'
Rows 634 & 635: 'Completed' != 'In progress'
Rows 658 & 659: 'In progress' != 'Approved'
Rows 660 & 661: 'Approved' != 'In progress'
Rows 676 & 677: 'In progress' != 'Approved'
Rows 678 & 679: 'Approved' != 'Completed'
Rows 684 & 685: 'Completed' != 'Approved'
Rows 688 & 689: 'Approved' != 'Completed'
Rows 692 & 693: 'Completed' != 'In progress'
Rows 694 & 695: 'In progress' != 'Completed'
Rows 720 & 721: 'Completed' != 'Approved'
Rows 722 & 723: 'Approved' != 'Completed'
Rows 730 & 731: 'Completed' != 'Approved'
Rows 732 & 733: 'Approved' != 'Completed'
Rows 742 & 743: 'Completed' != 'Approved'
Rows 744 & 745: 'Approved' != 'Completed'
Rows 754 & 755: 'Completed' != 'Approved'
Rows 756 & 757: 'Approved' != 'Completed'
Rows 760 & 761: 'Completed' != 'In progress'
Rows 796 & 797: 'In progress' != 'Completed'
Rows 798 & 799: 'Completed' != 'Approved'
Rows 802 & 803: 'Approved' != 'Completed'
Rows 808 & 809: 'Completed' != 'Approved'
Rows 810 & 811: 'Approved' != 'Completed'
Rows 818 & 819: 'Completed' != 'Submitted'
Rows 820 & 821: 'Submitted' != 'Completed'
Rows 822 & 823: 'Completed' != 'In progress'
Rows 824 & 825: 'In progress' != 'Completed'
Rows 832 & 833: 'Completed' != 'Approved'
Rows 834 & 835: 'Approved' != 'Completed'
Rows 838 & 839: 'Completed' != 'Approved'
Rows 840 & 841: 'Approved' != 'Completed'
Rows 858 & 859: 'Completed' != 'Approved'
Rows 860 & 861: 'Approved' != 'Completed'
Rows 864 & 865: 'Completed' != 'Approved'
Rows 866 & 867: 'Approved' != 'Completed'
Rows 868 & 869: 'Completed' != 'Approved'
Rows 870 & 871: 'Approved' != 'Completed'
Rows 888 & 889: 'Completed' != 'Approved'
Rows 890 & 891: 'Approved' != 'Completed'
Rows 898 & 899: 'Completed' != 'Approved'
Rows 900 & 901: 'Approved' != 'Completed'
Rows 906 & 907: 'Completed' != 'Approved'
Rows 910 & 911: 'Approved' != 'Completed'
Rows 932 & 933: 'Completed' != 'Approved'
Rows 934 & 935: 'Approved' != 'Completed'
Rows 936 & 937: 'Completed' != 'In progress'
Rows 938 & 939: 'In progress' != 'Approved'
Rows 940 & 941: 'Approved' != 'Completed'
Rows 968 & 969: 'Completed' != 'Approved'
Rows 970 & 971: 'Approved' != 'Completed'
Rows 986 & 987: 'Completed' != 'Approved'
Rows 988 & 989: 'Approved' != 'Completed'
Rows 1000 & 1001: 'Completed' != 'Submitted'
Rows 1002 & 1003: 'Submitted' != 'Completed'
Rows 1006 & 1007: 'Completed' != 'Approved'
Rows 1008 & 1009: 'Approved' != 'Completed'
Rows 1016 & 1017: 'Completed' != 'Approved'
Rows 1020 & 1021: 'Approved' != 'Completed'
Rows 1030 & 1031: 'Completed' != 'Approved'
Rows 1032 & 1033: 'Approved' != 'Completed'
Rows 1062 & 1063: 'Completed' != 'In progress'
Rows 1118 & 1119: 'In progress' != 'Completed'
Rows 1152 & 1153: 'Completed' != 'Approved'
Rows 1154 & 1155: 'Approved' != 'Completed'
Rows 1156 & 1157: 'Completed' != 'Submitted'
Rows 1158 & 1159: 'Submitted' != 'Completed'
Rows 1160 & 1161: 'Completed' != 'In progress'
Rows 1278 & 1279: 'In progress' != 'Completed'
Rows 1282 & 1283: 'Completed' != 'In progress'
Rows 1284 & 1285: 'In progress' != 'Completed'
Rows 1294 & 1295: 'Completed' != 'Approved'
Rows 1296 & 1297: 'Approved' != 'Completed'
Rows 1298 & 1299: 'Completed' != 'Approved'
Rows 1300 & 1301: 'Approved' != 'Completed'
Rows 1328 & 1329: 'Completed' != 'In progress'
Rows 1400 & 1401: 'In progress' != 'Completed'
Rows 1404 & 1405: 'Completed' != 'Approved'
Rows 1406 & 1407: 'Approved' != 'Completed'
Rows 1410 & 1411: 'Completed' != 'In progress'
Rows 1412 & 1413: 'In progress' != 'Completed'
Rows 1428 & 1429: 'Completed' != 'Submitted'
Rows 1430 & 1431: 'Submitted' != 'Completed'
Rows 1434 & 1435: 'Completed' != 'Approved'
Rows 1436 & 1437: 'Approved' != 'Completed'
Rows 1466 & 1467: 'Completed' != 'In progress'
Rows 1468 & 1469: 'In progress' != 'Completed'
Rows 1472 & 1473: 'Completed' != 'In progress'
Rows 1510 & 1511: 'In progress' != 'Completed'
Rows 1512 & 1513: 'Completed' != 'In progress'
Rows 1524 & 1525: 'In progress' != 'Completed'
Rows 1532 & 1533: 'Completed' != 'In progress'
Rows 1564 & 1565: 'In progress' != 'Completed'
Rows 1566 & 1567: 'Completed' != 'Approved'
Rows 1568 & 1569: 'Approved' != 'Completed'
Rows 1580 & 1581: 'Completed' != 'Approved'
Rows 1582 & 1583: 'Approved' != 'Completed'
Rows 1586 & 1587: 'Completed' != 'Approved'
Rows 1588 & 1589: 'Approved' != 'Completed'
Rows 1618 & 1619: 'Completed' != 'Approved'
Rows 1620 & 1621: 'Approved' != 'Completed'
Rows 1646 & 1647: 'Completed' != 'Approved'
Rows 1648 & 1649: 'Approved' != 'Completed'
Rows 1654 & 1655: 'Completed' != 'In progress'
Rows 1656 & 1657: 'In progress' != 'Completed'
Rows 1692 & 1693: 'Completed' != 'In progress'
Rows 1696 & 1697: 'In progress' != 'Completed'
Rows 1702 & 1703: 'Completed' != 'Approved'
Rows 1704 & 1705: 'Approved' != 'Completed'
Rows 1708 & 1709: 'Completed' != 'Approved'
Rows 1710 & 1711: 'Approved' != 'Completed'
Rows 1716 & 1717: 'Completed' != 'Submitted'
Rows 1718 & 1719: 'Submitted' != 'Completed'
Rows 1730 & 1731: 'Completed' != 'In progress'
Rows 1732 & 1733: 'In progress' != 'Completed'
Rows 1742 & 1743: 'Completed' != 'Approved'
Rows 1744 & 1745: 'Approved' != 'Completed'
Rows 1750 & 1751: 'Completed' != 'In progress'
Rows 1752 & 1753: 'In progress' != 'Completed'
Rows 1760 & 1761: 'Completed' != 'Approved'
Rows 1762 & 1763: 'Approved' != 'Completed'
Rows 1774 & 1775: 'Completed' != 'Approved'
Rows 1776 & 1777: 'Approved' != 'Completed'
Rows 1794 & 1795: 'Completed' != 'In progress'
Rows 1864 & 1865: 'In progress' != 'Completed'
Rows 1872 & 1873: 'Completed' != 'Approved'
Rows 1874 & 1875: 'Approved' != 'Completed'
Rows 1876 & 1877: 'Completed' != 'Approved'
Rows 1878 & 1879: 'Approved' != 'Completed'
Rows 1882 & 1883: 'Completed' != 'Approved'
Rows 1884 & 1885: 'Approved' != 'Completed'
Rows 1888 & 1889: 'Completed' != 'Approved'
Rows 1890 & 1891: 'Approved' != 'Completed'
Rows 1898 & 1899: 'Completed' != 'Approved'
Rows 1900 & 1901: 'Approved' != 'Completed'
Rows 1916 & 1917: 'Completed' != 'Approved'
Rows 1920 & 1921: 'Approved' != 'Completed'
Rows 1930 & 1931: 'Completed' != 'Approved'
Rows 1932 & 1933: 'Approved' != 'Completed'
Rows 1938 & 1939: 'Completed' != 'In progress'
Rows 1964 & 1965: 'In progress' != 'Completed'
Rows 1970 & 1971: 'Completed' != 'Approved'
Rows 1972 & 1973: 'Approved' != 'Completed'
Rows 1974 & 1975: 'Completed' != 'Approved'
Rows 1976 & 1977: 'Approved' != 'Completed'
Rows 1992 & 1993: 'Completed' != 'Approved'
Rows 1994 & 1995: 'Approved' != 'Completed'
Rows 2040 & 2041: 'Completed' != 'In progress'
Rows 2044 & 2045: 'In progress' != 'Completed'
Rows 2072 & 2073: 'Completed' != 'Approved'
Rows 2074 & 2075: 'Approved' != 'Completed'
Rows 2076 & 2077: 'Completed' != 'In progress'
Rows 2086 & 2087: 'In progress' != 'Completed'
Rows 2134 & 2135: 'Completed' != 'In progress'
Rows 2324 & 2325: 'In progress' != 'Completed'
Rows 2326 & 2327: 'Completed' != 'In progress'
Rows 2328 & 2329: 'In progress' != 'Completed'
Rows 2356 & 2357: 'Completed' != 'In progress'
Rows 2406 & 2407: 'In progress' != 'Completed'
Rows 2462 & 2463: 'Completed' != 'In progress'
Rows 2464 & 2465: 'In progress' != 'Completed'
Rows 2466 & 2467: 'Completed' != 'In progress'
Rows 2468 & 2469: 'In progress' != 'Completed'
Rows 2472 & 2473: 'Completed' != 'Approved'
Rows 2478 & 2479: 'Approved' != 'Completed'

In [91]:

row_counts = df.count(axis=1)
row_counts

# A typical main row in your screenshot has ~12–16 filled columns
# A continuation row has 1–3 filled columns
MAIN_MIN = 10          # consider row main if >= this many non-null columns
CONT_MAX = 4          # consider continuation if <= this many non-null columns
classifications = []   # will store: "main", "cont", "isolated", "unknown"

for i in range(len(df)):
    cnt = row_counts[i]

    if cnt >= MAIN_MIN:
        classifications.append("main")
    elif cnt <= CONT_MAX:
        classifications.append("cont")
    else:
        classifications.append("unknown")
merged_blocks = []
i = 0

while i < len(df):
    if classifications[i] == "main":
        block = [i]

        # collect all continuation rows after it
        j = i + 1
        while j < len(df) and classifications[j] == "cont":
            block.append(j)
            j += 1

        merged_blocks.append(block)
        i = j

    elif classifications[i] == "cont":
        merged_blocks.append([i])   # stray continuation (bad data)
        i += 1

    else:
        merged_blocks.append([i])   # unknown irregular row
        i += 1

print("\nDetected Groups:")
for block in merged_blocks:
    row_idx = block[0]
    emp_num = df.loc[row_idx, "Employee Person Number"]
    if len(block) == 1:
        print(f"Row {row_idx} (single row) — Employee Person Number: {emp_num}")
    else:
        print(f"Rows {block} form a merged multi-row block")
        row_idx1 = block[0]
        row_idx2 = block[1]
        s1 = df.loc[row_idx1, "Performance Document Status"]
        s2= df.loc[row_idx2, "Performance Document Status"]
        if s1 !=s2:
            print("Double Problem",emp_num)

Detected Groups:
Rows [0, 1] form a merged multi-row block
Rows [2, 3] form a merged multi-row block
Rows [4, 5] form a merged multi-row block
Rows [6, 7] form a merged multi-row block
Rows [8, 9] form a merged multi-row block
Rows [10, 11] form a merged multi-row block
Rows [12, 13] form a merged multi-row block
Rows [14, 15] form a merged multi-row block
Rows [16, 17] form a merged multi-row block
Rows [18, 19] form a merged multi-row block
Rows [20, 21] form a merged multi-row block
Rows [22, 23] form a merged multi-row block
Rows [24, 25] form a merged multi-row block
Rows [26, 27] form a merged multi-row block
Rows [28, 29] form a merged multi-row block
Rows [30, 31] form a merged multi-row block
Rows [32, 33] form a merged multi-row block
Rows [34, 35] form a merged multi-row block
Rows [36, 37] form a merged multi-row block
Rows [38, 39] form a merged multi-row block
Rows [40, 41] form a merged multi-row block
Rows [42, 43] form a merged multi-row block
Rows [44, 45] form a merged multi-row block
Rows [46, 47] form a merged multi-row block
Rows [48, 49] form a merged multi-row block
Rows [50, 51] form a merged multi-row block
Rows [52, 53] form a merged multi-row block
Rows [54, 55] form a merged multi-row block
Rows [56, 57] form a merged multi-row block
Rows [58, 59] form a merged multi-row block
Rows [60, 61] form a merged multi-row block
Rows [62, 63] form a merged multi-row block
Rows [64, 65] form a merged multi-row block
Rows [66, 67] form a merged multi-row block
Rows [68, 69] form a merged multi-row block
Rows [70, 71] form a merged multi-row block
Rows [72, 73] form a merged multi-row block
Rows [74, 75] form a merged multi-row block
Rows [76, 77] form a merged multi-row block
Rows [78, 79] form a merged multi-row block
Rows [80, 81] form a merged multi-row block
Rows [82, 83] form a merged multi-row block
Rows [84, 85] form a merged multi-row block
Rows [86, 87] form a merged multi-row block
Rows [88, 89] form a merged multi-row block
Rows [90, 91] form a merged multi-row block
Rows [92, 93] form a merged multi-row block
Rows [94, 95] form a merged multi-row block
Rows [96, 97] form a merged multi-row block
Rows [98, 99] form a merged multi-row block
Rows [100, 101] form a merged multi-row block
Rows [102, 103] form a merged multi-row block
Rows [104, 105] form a merged multi-row block
Rows [106, 107] form a merged multi-row block
Rows [108, 109] form a merged multi-row block
Rows [110, 111] form a merged multi-row block
Rows [112, 113] form a merged multi-row block
Rows [114, 115] form a merged multi-row block
Rows [116, 117] form a merged multi-row block
Rows [118, 119] form a merged multi-row block
Rows [120, 121] form a merged multi-row block
Rows [122, 123] form a merged multi-row block
Rows [124, 125] form a merged multi-row block
Rows [126, 127] form a merged multi-row block
Rows [128, 129] form a merged multi-row block
Rows [130, 131] form a merged multi-row block
Rows [132, 133] form a merged multi-row block
Rows [134, 135] form a merged multi-row block
Rows [136, 137] form a merged multi-row block
Rows [138, 139] form a merged multi-row block
Rows [140, 141] form a merged multi-row block
Rows [142, 143] form a merged multi-row block
Rows [144, 145] form a merged multi-row block
Rows [146, 147] form a merged multi-row block
Rows [148, 149] form a merged multi-row block
Rows [150, 151] form a merged multi-row block
Rows [152, 153] form a merged multi-row block
Rows [154, 155] form a merged multi-row block
Rows [156, 157] form a merged multi-row block
Rows [158, 159] form a merged multi-row block
Rows [160, 161] form a merged multi-row block
Rows [162, 163] form a merged multi-row block
Rows [164, 165] form a merged multi-row block
Rows [166, 167] form a merged multi-row block
Rows [168, 169] form a merged multi-row block
Rows [170, 171] form a merged multi-row block
Rows [172, 173] form a merged multi-row block
Rows [174, 175] form a merged multi-row block
Rows [176, 177] form a merged multi-row block
Rows [178, 179] form a merged multi-row block
Rows [180, 181] form a merged multi-row block
Rows [182, 183] form a merged multi-row block
Rows [184, 185] form a merged multi-row block
Rows [186, 187] form a merged multi-row block
Rows [188, 189] form a merged multi-row block
Rows [190, 191] form a merged multi-row block
Rows [192, 193] form a merged multi-row block
Rows [194, 195] form a merged multi-row block
Rows [196, 197] form a merged multi-row block
Rows [198, 199] form a merged multi-row block
Rows [200, 201] form a merged multi-row block
Rows [202, 203] form a merged multi-row block
Rows [204, 205] form a merged multi-row block
Rows [206, 207] form a merged multi-row block
Row 208 (single row) — Employee Person Number: 2220.0
Rows [209, 210] form a merged multi-row block
Rows [211, 212] form a merged multi-row block
Rows [213, 214] form a merged multi-row block
Rows [215, 216] form a merged multi-row block
Rows [217, 218] form a merged multi-row block
Rows [219, 220] form a merged multi-row block
Rows [221, 222] form a merged multi-row block
Rows [223, 224] form a merged multi-row block
Rows [225, 226] form a merged multi-row block
Rows [227, 228] form a merged multi-row block
Rows [229, 230] form a merged multi-row block
Rows [231, 232] form a merged multi-row block
Rows [233, 234] form a merged multi-row block
Rows [235, 236] form a merged multi-row block
Rows [237, 238] form a merged multi-row block
Rows [239, 240] form a merged multi-row block
Rows [241, 242] form a merged multi-row block
Rows [243, 244] form a merged multi-row block
Rows [245, 246] form a merged multi-row block
Rows [247, 248] form a merged multi-row block
Rows [249, 250] form a merged multi-row block
Rows [251, 252] form a merged multi-row block
Rows [253, 254] form a merged multi-row block
Rows [255, 256] form a merged multi-row block
Rows [257, 258] form a merged multi-row block
Rows [259, 260] form a merged multi-row block
Rows [261, 262] form a merged multi-row block
Rows [263, 264] form a merged multi-row block
Rows [265, 266] form a merged multi-row block
Rows [267, 268] form a merged multi-row block
Rows [269, 270] form a merged multi-row block
Rows [271, 272] form a merged multi-row block
Rows [273, 274] form a merged multi-row block
Rows [275, 276] form a merged multi-row block
Rows [277, 278] form a merged multi-row block
Rows [279, 280] form a merged multi-row block
Rows [281, 282] form a merged multi-row block
Rows [283, 284] form a merged multi-row block
Rows [285, 286] form a merged multi-row block
Rows [287, 288] form a merged multi-row block
Rows [289, 290] form a merged multi-row block
Rows [291, 292] form a merged multi-row block
Rows [293, 294] form a merged multi-row block
Rows [295, 296] form a merged multi-row block
Rows [297, 298] form a merged multi-row block
Rows [299, 300] form a merged multi-row block
Rows [301, 302] form a merged multi-row block
Rows [303, 304] form a merged multi-row block
Rows [305, 306] form a merged multi-row block
Rows [307, 308] form a merged multi-row block
Rows [309, 310] form a merged multi-row block
Rows [311, 312] form a merged multi-row block
Rows [313, 314] form a merged multi-row block
Rows [315, 316] form a merged multi-row block
Rows [317, 318] form a merged multi-row block
Rows [319, 320] form a merged multi-row block
Rows [321, 322] form a merged multi-row block
Rows [323, 324] form a merged multi-row block
Rows [325, 326] form a merged multi-row block
Rows [327, 328] form a merged multi-row block
Rows [329, 330] form a merged multi-row block
Rows [331, 332] form a merged multi-row block
Rows [333, 334] form a merged multi-row block
Rows [335, 336] form a merged multi-row block
Rows [337, 338] form a merged multi-row block
Rows [339, 340] form a merged multi-row block
Rows [341, 342] form a merged multi-row block
Rows [343, 344] form a merged multi-row block
Rows [345, 346] form a merged multi-row block
Rows [347, 348] form a merged multi-row block
Rows [349, 350] form a merged multi-row block
Rows [351, 352] form a merged multi-row block
Row 353 (single row) — Employee Person Number: 293.0
Rows [354, 355] form a merged multi-row block
Rows [356, 357] form a merged multi-row block
Rows [358, 359] form a merged multi-row block
Rows [360, 361] form a merged multi-row block
Rows [362, 363] form a merged multi-row block
Rows [364, 365] form a merged multi-row block
Rows [366, 367] form a merged multi-row block
Rows [368, 369] form a merged multi-row block
Rows [370, 371] form a merged multi-row block
Rows [372, 373] form a merged multi-row block
Rows [374, 375] form a merged multi-row block
Rows [376, 377] form a merged multi-row block
Rows [378, 379] form a merged multi-row block
Rows [380, 381] form a merged multi-row block
Rows [382, 383] form a merged multi-row block
Rows [384, 385] form a merged multi-row block
Rows [386, 387] form a merged multi-row block
Rows [388, 389] form a merged multi-row block
Rows [390, 391] form a merged multi-row block
Rows [392, 393] form a merged multi-row block
Rows [394, 395] form a merged multi-row block
Rows [396, 397] form a merged multi-row block
Rows [398, 399] form a merged multi-row block
Rows [400, 401] form a merged multi-row block
Row 402 (single row) — Employee Person Number: 3094.0
Rows [403, 404] form a merged multi-row block
Rows [405, 406] form a merged multi-row block
Rows [407, 408] form a merged multi-row block
Rows [409, 410] form a merged multi-row block
Rows [411, 412] form a merged multi-row block
Rows [413, 414] form a merged multi-row block
Rows [415, 416] form a merged multi-row block
Rows [417, 418] form a merged multi-row block
Rows [419, 420] form a merged multi-row block
Rows [421, 422] form a merged multi-row block
Rows [423, 424] form a merged multi-row block
Rows [425, 426] form a merged multi-row block
Rows [427, 428] form a merged multi-row block
Rows [429, 430] form a merged multi-row block
Rows [431, 432] form a merged multi-row block
Rows [433, 434] form a merged multi-row block
Rows [435, 436] form a merged multi-row block
Rows [437, 438] form a merged multi-row block
Rows [439, 440] form a merged multi-row block
Rows [441, 442] form a merged multi-row block
Rows [443, 444] form a merged multi-row block
Rows [445, 446] form a merged multi-row block
Rows [447, 448] form a merged multi-row block
Rows [449, 450] form a merged multi-row block
Rows [451, 452] form a merged multi-row block
Rows [453, 454] form a merged multi-row block
Rows [455, 456] form a merged multi-row block
Rows [457, 458] form a merged multi-row block
Rows [459, 460] form a merged multi-row block
Rows [461, 462] form a merged multi-row block
Rows [463, 464] form a merged multi-row block
Rows [465, 466] form a merged multi-row block
Rows [467, 468] form a merged multi-row block
Rows [469, 470] form a merged multi-row block
Row 471 (single row) — Employee Person Number: 3411.0
Rows [472, 473] form a merged multi-row block
Rows [474, 475] form a merged multi-row block
Rows [476, 477] form a merged multi-row block
Rows [478, 479] form a merged multi-row block
Rows [480, 481] form a merged multi-row block
Rows [482, 483] form a merged multi-row block
Rows [484, 485] form a merged multi-row block
Rows [486, 487] form a merged multi-row block
Rows [488, 489] form a merged multi-row block
Rows [490, 491] form a merged multi-row block
Rows [492, 493] form a merged multi-row block
Rows [494, 495] form a merged multi-row block
Rows [496, 497] form a merged multi-row block
Rows [498, 499] form a merged multi-row block
Rows [500, 501] form a merged multi-row block
Rows [502, 503] form a merged multi-row block
Rows [504, 505] form a merged multi-row block
Row 506 (single row) — Employee Person Number: 3633.0
Rows [507, 508] form a merged multi-row block
Rows [509, 510] form a merged multi-row block
Rows [511, 512] form a merged multi-row block
Rows [513, 514] form a merged multi-row block
Rows [515, 516] form a merged multi-row block
Rows [517, 518] form a merged multi-row block
Rows [519, 520] form a merged multi-row block
Rows [521, 522] form a merged multi-row block
Rows [523, 524] form a merged multi-row block
Rows [525, 526] form a merged multi-row block
Rows [527, 528] form a merged multi-row block
Rows [529, 530] form a merged multi-row block
Rows [531, 532] form a merged multi-row block
Rows [533, 534] form a merged multi-row block
Rows [535, 536] form a merged multi-row block
Rows [537, 538] form a merged multi-row block
Rows [539, 540] form a merged multi-row block
Row 541 (single row) — Employee Person Number: 3792.0
Rows [542, 543] form a merged multi-row block
Rows [544, 545] form a merged multi-row block
Rows [546, 547] form a merged multi-row block
Rows [548, 549] form a merged multi-row block
Rows [550, 551] form a merged multi-row block
Rows [552, 553] form a merged multi-row block
Rows [554, 555] form a merged multi-row block
Rows [556, 557] form a merged multi-row block
Rows [558, 559] form a merged multi-row block
Rows [560, 561] form a merged multi-row block
Rows [562, 563] form a merged multi-row block
Rows [564, 565] form a merged multi-row block
Rows [566, 567] form a merged multi-row block
Rows [568, 569] form a merged multi-row block
Rows [570, 571] form a merged multi-row block
Rows [572, 573] form a merged multi-row block
Rows [574, 575] form a merged multi-row block
Rows [576, 577] form a merged multi-row block
Rows [578, 579] form a merged multi-row block
Rows [580, 581] form a merged multi-row block
Rows [582, 583] form a merged multi-row block
Rows [584, 585] form a merged multi-row block
Rows [586, 587] form a merged multi-row block
Rows [588, 589] form a merged multi-row block
Rows [590, 591] form a merged multi-row block
Rows [592, 593] form a merged multi-row block
Rows [594, 595] form a merged multi-row block
Rows [596, 597] form a merged multi-row block
Rows [598, 599] form a merged multi-row block
Rows [600, 601] form a merged multi-row block
Rows [602, 603] form a merged multi-row block
Row 604 (single row) — Employee Person Number: 3996.0
Rows [605, 606] form a merged multi-row block
Rows [607, 608] form a merged multi-row block
Rows [609, 610] form a merged multi-row block
Rows [611, 612] form a merged multi-row block
Rows [613, 614] form a merged multi-row block
Rows [615, 616] form a merged multi-row block
Rows [617, 618] form a merged multi-row block
Rows [619, 620] form a merged multi-row block
Rows [621, 622] form a merged multi-row block
Rows [623, 624] form a merged multi-row block
Rows [625, 626] form a merged multi-row block
Rows [627, 628] form a merged multi-row block
Rows [629, 630] form a merged multi-row block
Rows [631, 632] form a merged multi-row block
Rows [633, 634] form a merged multi-row block
Row 635 (single row) — Employee Person Number: 4044.0
Rows [636, 637] form a merged multi-row block
Rows [638, 639] form a merged multi-row block
Rows [640, 641] form a merged multi-row block
Rows [642, 643] form a merged multi-row block
Rows [644, 645] form a merged multi-row block
Rows [646, 647] form a merged multi-row block
Rows [648, 649] form a merged multi-row block
Rows [650, 651] form a merged multi-row block
Rows [652, 653] form a merged multi-row block
Rows [654, 655] form a merged multi-row block
Rows [656, 657] form a merged multi-row block
Row 658 (single row) — Employee Person Number: 4135.0
Rows [659, 660] form a merged multi-row block
Row 661 (single row) — Employee Person Number: 4146.0
Rows [662, 663] form a merged multi-row block
Rows [664, 665] form a merged multi-row block
Rows [666, 667] form a merged multi-row block
Rows [668, 669] form a merged multi-row block
Rows [670, 671] form a merged multi-row block
Rows [672, 673] form a merged multi-row block
Rows [674, 675] form a merged multi-row block
Row 676 (single row) — Employee Person Number: 4214.0
Rows [677, 678] form a merged multi-row block
Rows [679, 680] form a merged multi-row block
Rows [681, 682] form a merged multi-row block
Rows [683, 684] form a merged multi-row block
Rows [685, 686] form a merged multi-row block
Rows [687, 688] form a merged multi-row block
Rows [689, 690] form a merged multi-row block
Rows [691, 692] form a merged multi-row block
Rows [693, 694] form a merged multi-row block
Rows [695, 696] form a merged multi-row block
Rows [697, 698] form a merged multi-row block
Rows [699, 700] form a merged multi-row block
Rows [701, 702] form a merged multi-row block
Rows [703, 704] form a merged multi-row block
Rows [705, 706] form a merged multi-row block
Rows [707, 708] form a merged multi-row block
Rows [709, 710] form a merged multi-row block
Rows [711, 712] form a merged multi-row block
Rows [713, 714] form a merged multi-row block
Rows [715, 716] form a merged multi-row block
Rows [717, 718] form a merged multi-row block
Rows [719, 720] form a merged multi-row block
Rows [721, 722] form a merged multi-row block
Rows [723, 724] form a merged multi-row block
Rows [725, 726] form a merged multi-row block
Rows [727, 728] form a merged multi-row block
Rows [729, 730] form a merged multi-row block
Rows [731, 732] form a merged multi-row block
Rows [733, 734] form a merged multi-row block
Rows [735, 736] form a merged multi-row block
Rows [737, 738] form a merged multi-row block
Rows [739, 740] form a merged multi-row block
Rows [741, 742] form a merged multi-row block
Rows [743, 744] form a merged multi-row block
Rows [745, 746] form a merged multi-row block
Rows [747, 748] form a merged multi-row block
Rows [749, 750] form a merged multi-row block
Rows [751, 752] form a merged multi-row block
Rows [753, 754] form a merged multi-row block
Rows [755, 756] form a merged multi-row block
Rows [757, 758] form a merged multi-row block
Rows [759, 760] form a merged multi-row block
Row 761 (single row) — Employee Person Number: 4614.0
Rows [762, 763] form a merged multi-row block
Rows [764, 765] form a merged multi-row block
Rows [766, 767] form a merged multi-row block
Rows [768, 769] form a merged multi-row block
Rows [770, 771] form a merged multi-row block
Rows [772, 773] form a merged multi-row block
Rows [774, 775] form a merged multi-row block
Rows [776, 777] form a merged multi-row block
Rows [778, 779] form a merged multi-row block
Rows [780, 781] form a merged multi-row block
Rows [782, 783] form a merged multi-row block
Rows [784, 785] form a merged multi-row block
Rows [786, 787] form a merged multi-row block
Rows [788, 789] form a merged multi-row block
Rows [790, 791] form a merged multi-row block
Rows [792, 793] form a merged multi-row block
Rows [794, 795] form a merged multi-row block
Row 796 (single row) — Employee Person Number: 481.0
Rows [797, 798] form a merged multi-row block
Rows [799, 800] form a merged multi-row block
Rows [801, 802] form a merged multi-row block
Rows [803, 804] form a merged multi-row block
Rows [805, 806] form a merged multi-row block
Rows [807, 808] form a merged multi-row block
Rows [809, 810] form a merged multi-row block
Rows [811, 812] form a merged multi-row block
Rows [813, 814] form a merged multi-row block
Rows [815, 816] form a merged multi-row block
Rows [817, 818] form a merged multi-row block
Rows [819, 820] form a merged multi-row block
Rows [821, 822] form a merged multi-row block
Rows [823, 824] form a merged multi-row block
Rows [825, 826] form a merged multi-row block
Rows [827, 828] form a merged multi-row block
Rows [829, 830] form a merged multi-row block
Rows [831, 832] form a merged multi-row block
Rows [833, 834] form a merged multi-row block
Rows [835, 836] form a merged multi-row block
Rows [837, 838] form a merged multi-row block
Rows [839, 840] form a merged multi-row block
Rows [841, 842] form a merged multi-row block
Rows [843, 844] form a merged multi-row block
Rows [845, 846] form a merged multi-row block
Rows [847, 848] form a merged multi-row block
Rows [849, 850] form a merged multi-row block
Rows [851, 852] form a merged multi-row block
Rows [853, 854] form a merged multi-row block

In [93]:
flattened_rows = []
cols = df.columns
for block in merged_blocks:
    # Take the first (main) row of the block
    main_idx = block[0]
    main_row = df.loc[main_idx].copy()

    # If block has more than one row, merge continuation rows
    if len(block) > 1:
        for cont_idx in block[1:]:
            cont_row = df.loc[cont_idx]

            # For each column, if continuation has value, override main
            for col in cols:
                if pd.notna(cont_row[col]):
                    main_row[col] = cont_row[col]

    # Store the assembled row
    flattened_rows.append(main_row)

In [94]:
flattened_df = pd.DataFrame(flattened_rows, columns=cols)
flattened_df.reset_index(drop=True, inplace=True)

In [95]:
flattened_df

,Employee Person Number,Employee Name,Employee E-Mail Address,Manager Person Number,Manager Name,Manager E-Mail Address,Business Unit Name,Department,Parent Department,Grade,Parent Grade,Job,Location Name,Performance Document Name,Overall Manager Rating,Overall Employee Rating,Performance Document Status
0,1004.0,Gyanendra Singh,gyanendras@tataplay.com,2430.0,Vishal Sethi,vishal.sethi@tataplay.com,North,Field Engineering and Audit,Technology,M5a,M5,Assistant Manager - Quality,Lucknow,2025-26 – Q2/H1 (Mid Year),3.0,4.0,Completed
1,1034.0,Monoranjon Dutta,manoranjand@tataplay.com,4922.0,Joydeep Roy,Joydeep.Roy@tataplay.com,East,Field Service Delivery - General,Field Service Delivery,M4a,M4,Senior Manager - Field Service Delivery,Kolkata,2025-26 – Q2/H1 (Mid Year),3.0,3.0,Completed
2,1045.0,Metilda Molly Thomas,mollyt@tataplay.com,5922.0,Nipun Sharma,Nipun.Sharma@tataplay.com,South,Customer Operations - General,Customer Operations,M4b,M4,Manager - Customer Operations,Hebbal,2025-26 – Q2/H1 (Mid Year),3.0,3.0,Approved
3,1060.0,Thangudu Srinivasa Rao,srinivasar@tataplay.com,4127.0,Ashoka B,ashoka.b@tataplay.com,South,Field Service Delivery - General,Field Service Delivery,M4b,M4,Manager - Field Service Delivery,Hebbal,2025-26 – Q2/H1 (Mid Year),4.0,4.0,Completed
4,107.0,Chirag P. Thakar,chiragt@tataplay.com,2747.0,Avinash Kesherwani,avinash.kesherwani@tataplay.com,Corporate,Finance - General,Finance,M3b,M3,Assistant General Manager - Finance,Corporate,2025-26 – Q2/H1 (Mid Year),3.0,4.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,920.0,Madhu Sharma,madhus@tataplay.com,1480.0,Sanjay Mittal,sanjaymi@tataplay.com,North,Field Service Delivery Support,Field Service Delivery,M4b,M4,Manager - Field Service Delivery Support,Noida,2025-26 – Q2/H1 (Mid Year),2.0,3.0,Approved
1255,926.0,Harihar Nath Vishwakarma,hariharnathv@tataplay.com,299.0,Vikas Chugh,vikasc@tataplay.com,Corporate,MIS & Reporting-Sales,Sales,M4b,M4,Manager - MIS & Reporting-Sales,Corporate,2025-26 – Q2/H1 (Mid Year),3.0,3.0,Approved
1256,941.0,Jayesh Joshi,jayeshj@tataplay.com,299.0,Vikas Chugh,vikasc@tataplay.com,West,Field Service Delivery - General,Field Service Delivery,M3a,M3,General Manager - Field Service Delivery,Ahmedabad,2025-26 – Q2/H1 (Mid Year),3.0,3.0,Approved
1257,950.0,Dharmesh Shah,dharmeshs@tataplay.com,941.0,Jayesh Joshi,jayeshj@tataplay.com,West,Field Service Delivery - General,Field Service Delivery,M4b,M4,Manager - Field Service Delivery,Ahmedabad,2025-26 – Q2/H1 (Mid Year),2.0,3.0,Completed
1258,997.0,Ramesh Rai,rameshr@tataplay.com,6471.0,Sadashiv Sharma,Sadashiv.Sharma@tataplay.com,North,Trade Sales,Sales,M5a,M5,Assistant Manager - Trade Sales,Noida,2025-26 – Q2/H1 (Mid Year),2.0,2.0,Completed

In [97]:
rows_with_nulls = flattened_df[df.isnull().any(axis=1)]
print("Rows containing NULL values:\n")
print(rows_with_nulls)

Rows containing NULL values:

      Employee Person Number             Employee Name  \
0                     1004.0           Gyanendra Singh
1                     1034.0          Monoranjon Dutta
2                     1045.0      Metilda Molly Thomas
3                     1060.0    Thangudu Srinivasa Rao
4                      107.0          Chirag P. Thakar
...                      ...                       ...
1254                   920.0              Madhu Sharma
1255                   926.0  Harihar Nath Vishwakarma
1256                   941.0              Jayesh Joshi
1257                   950.0             Dharmesh Shah
1258                   997.0                Ramesh Rai

        Employee E-Mail Address  Manager Person Number        Manager Name  \
0       gyanendras@tataplay.com                 2430.0        Vishal Sethi
1      manoranjand@tataplay.com                 4922.0         Joydeep Roy
2           mollyt@tataplay.com                 5922.0        Nipun Sharma
3       srinivasar@tataplay.com                 4127.0            Ashoka B
4          chiragt@tataplay.com                 2747.0  Avinash Kesherwani
...                         ...                    ...                 ...
1254        madhus@tataplay.com                 1480.0       Sanjay Mittal
1255  hariharnathv@tataplay.com                  299.0         Vikas Chugh
1256       jayeshj@tataplay.com                  299.0         Vikas Chugh
1257     dharmeshs@tataplay.com                  941.0        Jayesh Joshi
1258       rameshr@tataplay.com                 6471.0     Sadashiv Sharma

               Manager E-Mail Address Business Unit Name  \
0           vishal.sethi@tataplay.com              North
1            Joydeep.Roy@tataplay.com               East
2           Nipun.Sharma@tataplay.com              South
3               ashoka.b@tataplay.com              South
4     avinash.kesherwani@tataplay.com          Corporate
...                               ...                ...
1254            sanjaymi@tataplay.com              North
1255              vikasc@tataplay.com          Corporate
1256              vikasc@tataplay.com               West
1257             jayeshj@tataplay.com               West
1258     Sadashiv.Sharma@tataplay.com              North

                            Department       Parent Department Grade  \
0          Field Engineering and Audit              Technology   M5a
1     Field Service Delivery - General  Field Service Delivery   M4a
2        Customer Operations - General     Customer Operations   M4b
3     Field Service Delivery - General  Field Service Delivery   M4b
4                    Finance - General                 Finance   M3b
...                                ...                     ...   ...
1254    Field Service Delivery Support  Field Service Delivery   M4b
1255             MIS & Reporting-Sales                   Sales   M4b
1256  Field Service Delivery - General  Field Service Delivery   M3a
1257  Field Service Delivery - General  Field Service Delivery   M4b
1258                       Trade Sales                   Sales   M5a

     Parent Grade                                       Job Location Name  \
0              M5               Assistant Manager - Quality       Lucknow
1              M4   Senior Manager - Field Service Delivery       Kolkata
2              M4             Manager - Customer Operations        Hebbal
3              M4          Manager - Field Service Delivery        Hebbal
4              M3       Assistant General Manager - Finance     Corporate
...           ...                                       ...           ...
1254           M4  Manager - Field Service Delivery Support         Noida
1255           M4           Manager - MIS & Reporting-Sales     Corporate
1256           M3  General Manager - Field Service Delivery     Ahmedabad
1257           M4          Manager - Field Service Delivery     Ahmedabad
1258           M5           Assistant Manager - Trade Sales         Noida

       Performance Document Name  Overall Manager Rating  \
0     2025-26 – Q2/H1 (Mid Year)                     3.0
1     2025-26 – Q2/H1 (Mid Year)                     3.0
2     2025-26 – Q2/H1 (Mid Year)                     3.0
3     2025-26 – Q2/H1 (Mid Year)                     4.0
4     2025-26 – Q2/H1 (Mid Year)                     3.0
...                          ...                     ...
1254  2025-26 – Q2/H1 (Mid Year)                     2.0
1255  2025-26 – Q2/H1 (Mid Year)                     3.0
1256  2025-26 – Q2/H1 (Mid Year)                     3.0
1257  2025-26 – Q2/H1 (Mid Year)                     2.0
1258  2025-26 – Q2/H1 (Mid Year)                     2.0

      Overall Employee Rating Performance Document Status
0                         4.0                   Completed
1                         3.0                   Completed
2                         3.0                    Approved
3                         4.0                   Completed
4                         4.0                   Completed
...                       ...                         ...
1254                      3.0                    Approved
1255                      3.0                    Approved
1256                      3.0                    Approved
1257                      3.0                   Completed
1258                      2.0                   Completed

[1259 rows x 17 columns]

C:\Users\SaptarshiBanik\AppData\Local\Temp\ipykernel_14720\3470424408.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  rows_with_nulls = flattened_df[df.isnull().any(axis=1)]

In [98]:
rows_with_nulls

,Employee Person Number,Employee Name,Employee E-Mail Address,Manager Person Number,Manager Name,Manager E-Mail Address,Business Unit Name,Department,Parent Department,Grade,Parent Grade,Job,Location Name,Performance Document Name,Overall Manager Rating,Overall Employee Rating,Performance Document Status
0,1004.0,Gyanendra Singh,gyanendras@tataplay.com,2430.0,Vishal Sethi,vishal.sethi@tataplay.com,North,Field Engineering and Audit,Technology,M5a,M5,Assistant Manager - Quality,Lucknow,2025-26 – Q2/H1 (Mid Year),3.0,4.0,Completed
1,1034.0,Monoranjon Dutta,manoranjand@tataplay.com,4922.0,Joydeep Roy,Joydeep.Roy@tataplay.com,East,Field Service Delivery - General,Field Service Delivery,M4a,M4,Senior Manager - Field Service Delivery,Kolkata,2025-26 – Q2/H1 (Mid Year),3.0,3.0,Completed
2,1045.0,Metilda Molly Thomas,mollyt@tataplay.com,5922.0,Nipun Sharma,Nipun.Sharma@tataplay.com,South,Customer Operations - General,Customer Operations,M4b,M4,Manager - Customer Operations,Hebbal,2025-26 – Q2/H1 (Mid Year),3.0,3.0,Approved
3,1060.0,Thangudu Srinivasa Rao,srinivasar@tataplay.com,4127.0,Ashoka B,ashoka.b@tataplay.com,South,Field Service Delivery - General,Field Service Delivery,M4b,M4,Manager - Field Service Delivery,Hebbal,2025-26 – Q2/H1 (Mid Year),4.0,4.0,Completed
4,107.0,Chirag P. Thakar,chiragt@tataplay.com,2747.0,Avinash Kesherwani,avinash.kesherwani@tataplay.com,Corporate,Finance - General,Finance,M3b,M3,Assistant General Manager - Finance,Corporate,2025-26 – Q2/H1 (Mid Year),3.0,4.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,920.0,Madhu Sharma,madhus@tataplay.com,1480.0,Sanjay Mittal,sanjaymi@tataplay.com,North,Field Service Delivery Support,Field Service Delivery,M4b,M4,Manager - Field Service Delivery Support,Noida,2025-26 – Q2/H1 (Mid Year),2.0,3.0,Approved
1255,926.0,Harihar Nath Vishwakarma,hariharnathv@tataplay.com,299.0,Vikas Chugh,vikasc@tataplay.com,Corporate,MIS & Reporting-Sales,Sales,M4b,M4,Manager - MIS & Reporting-Sales,Corporate,2025-26 – Q2/H1 (Mid Year),3.0,3.0,Approved
1256,941.0,Jayesh Joshi,jayeshj@tataplay.com,299.0,Vikas Chugh,vikasc@tataplay.com,West,Field Service Delivery - General,Field Service Delivery,M3a,M3,General Manager - Field Service Delivery,Ahmedabad,2025-26 – Q2/H1 (Mid Year),3.0,3.0,Approved
1257,950.0,Dharmesh Shah,dharmeshs@tataplay.com,941.0,Jayesh Joshi,jayeshj@tataplay.com,West,Field Service Delivery - General,Field Service Delivery,M4b,M4,Manager - Field Service Delivery,Ahmedabad,2025-26 – Q2/H1 (Mid Year),2.0,3.0,Completed
1258,997.0,Ramesh Rai,rameshr@tataplay.com,6471.0,Sadashiv Sharma,Sadashiv.Sharma@tataplay.com,North,Trade Sales,Sales,M5a,M5,Assistant Manager - Trade Sales,Noida,2025-26 – Q2/H1 (Mid Year),2.0,2.0,Completed

In [103]:
import numpy as np

def is_iterable_but_not_string(x):
    return isinstance(x, (list, tuple, set, np.ndarray))
def looks_like_multivalue_string(x):
    if not isinstance(x, str):
        return False
    return ("," in x) or (";" in x) or ("|" in x)

mask_listlike = df.map(is_iterable_but_not_string)
rows_with_list_objects = df[mask_listlike.any(axis=1)]

mask_multi_str = df.map(looks_like_multivalue_string)
rows_with_multi_string = df[mask_multi_str.any(axis=1)]

combined_mask = mask_listlike | mask_multi_str
rows_with_any_multivalue = df[combined_mask.any(axis=1)]

print("Rows with ANY multi-value content (object or string):\n")
rows_with_any_multivalue

Rows with ANY multi-value content (object or string):

,Employee Person Number,Employee Name,Employee E-Mail Address,Manager Person Number,Manager Name,Manager E-Mail Address,Business Unit Name,Department,Parent Department,Grade,Parent Grade,Job,Location Name,Performance Document Name,Overall Manager Rating,Overall Employee Rating,Performance Document Status
374,299.0,Vikas Chugh,vikasc@tataplay.com,293.0,Bhagat Bisht,bishtb@tataplay.com,West,Field Service Delivery - General,Field Service Delivery,M2a,M2,Senior Vice President - Sales and Field Servic...,Corporate,2025-26 – Q2/H1 (Mid Year),NaN,3.0,In progress

In [105]:
flattened_df.columns

Index(['Employee Person Number', 'Employee Name', 'Employee E-Mail Address',
       'Manager Person Number', 'Manager Name', 'Manager E-Mail Address',
       'Business Unit Name', 'Department', 'Parent Department', 'Grade',
       'Parent Grade', 'Job', 'Location Name', 'Performance Document Name',
       'Overall Manager Rating', 'Overall Employee Rating',
       'Performance Document Status'],
      dtype='object')

In [111]:
FIELDS = [
    "Employee Person Number",
    "Employee Name",
    "Employee E-Mail Address",
    "Manager Person Number",
    "Manager Name",
    "Manager E-Mail Address",
    "Business Unit Name",
    "Department",
    "Parent Department",
    "Grade",
    "Parent Grade",
    "Job",
    "Location Name",
    "Performance Document Name",
    "Overall Manager Rating",
    "Overall Employee Rating",
    "Performance Document Status"
]
KEY_RENAMES = {
    "Employee Person Number": "employee code",
    "Employee Name": "employee name",
    "Employee E-Mail Address": "email",

    "Manager Person Number": "manager employee code",
    "Manager Name": "manager name",
    "Manager E-Mail Address": "manager email",

    "Business Unit Name": "region",
    "Department": "sub department",
    "Parent Department": "department",
    
    "Grade": "grade level",
    "Parent Grade": "grade",

    "Job": "designation",

    "Location Name": "location",
    "Performance Document Name": "performance document name",
    "Overall Manager Rating": "overall manager rating",
    "Overall Employee Rating": "overall employee rating",
    "Performance Document Status": "performance document status"
}
NUMERIC_FIELDS = [
    "employee code",
    "manager employee code",
    "overall manager rating",
    "overall employee rating"
]
DATE_FIELDS = []

In [112]:
raw_docs = []

# Convert each DF row → raw dict
for idx, row in flattened_df.iterrows():
    raw_doc = row.to_dict()


    raw_docs.append(raw_doc)

# Normalize
normalized_docs = [
    normalize_doc_generic(
        doc,
        FIELDS,
        KEY_RENAMES,
        NUMERIC_FIELDS,
        DATE_FIELDS
    )
    for doc in raw_docs
]

In [113]:
normalized_docs

[{'employee code': 1004,
  'employee name': 'Gyanendra Singh',
  'email': 'gyanendras@tataplay.com',
  'manager employee code': 2430,
  'manager name': 'Vishal Sethi',
  'manager email': 'vishal.sethi@tataplay.com',
  'region': 'North',
  'sub department': 'Field Engineering and Audit',
  'department': 'Technology',
  'grade level': 'M5a',
  'grade': 'M5',
  'designation': 'Assistant Manager - Quality',
  'location': 'Lucknow',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 1034,
  'employee name': 'Monoranjon Dutta',
  'email': 'manoranjand@tataplay.com',
  'manager employee code': 4922,
  'manager name': 'Joydeep Roy',
  'manager email': 'Joydeep.Roy@tataplay.com',
  'region': 'East',
  'sub department': 'Field Service Delivery - General',
  'department': 'Field Service Delivery',
  'grade level': 'M4a',
  'grade': 'M4',
  'designation': 'Senior Manager - Field Service Delivery',
  'location': 'Kolkata',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 3,
  'performance document status': 'Completed'},
 {'employee code': 1045,
  'employee name': 'Metilda Molly Thomas',
  'email': 'mollyt@tataplay.com',
  'manager employee code': 5922,
  'manager name': 'Nipun Sharma',
  'manager email': 'Nipun.Sharma@tataplay.com',
  'region': 'South',
  'sub department': 'Customer Operations - General',
  'department': 'Customer Operations',
  'grade level': 'M4b',
  'grade': 'M4',
  'designation': 'Manager - Customer Operations',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 3,
  'performance document status': 'Approved'},
 {'employee code': 1060,
  'employee name': 'Thangudu Srinivasa Rao',
  'email': 'srinivasar@tataplay.com',
  'manager employee code': 4127,
  'manager name': 'Ashoka B',
  'manager email': 'ashoka.b@tataplay.com',
  'region': 'South',
  'sub department': 'Field Service Delivery - General',
  'department': 'Field Service Delivery',
  'grade level': 'M4b',
  'grade': 'M4',
  'designation': 'Manager - Field Service Delivery',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 4,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 107,
  'employee name': 'Chirag P. Thakar',
  'email': 'chiragt@tataplay.com',
  'manager employee code': 2747,
  'manager name': 'Avinash Kesherwani',
  'manager email': 'avinash.kesherwani@tataplay.com',
  'region': 'Corporate',
  'sub department': 'Finance - General',
  'department': 'Finance',
  'grade level': 'M3b',
  'grade': 'M3',
  'designation': 'Assistant General Manager - Finance',
  'location': 'Corporate',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 1088,
  'employee name': 'Arun Dharampal',
  'email': 'arund@tataplay.com',
  'manager employee code': 4182,
  'manager name': 'Brij Mohan Singh',
  'manager email': 'brijmohan.singh@tataplay.com',
  'region': 'North',
  'sub department': 'Field Service Delivery - General',
  'department': 'Field Service Delivery',
  'grade level': 'M5b',
  'grade': 'M5',
  'designation': 'Senior Executive - Field Service Delivery',
  'location': 'Noida',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 2,
  'overall employee rating': 3,
  'performance document status': 'Completed'},
 {'employee code': 1107,
  'employee name': 'Ravi Pratap Singh',
  'email': 'raviprataps@tataplay.com',
  'manager employee code': 4182,
  'manager name': 'Brij Mohan Singh',
  'manager email': 'brijmohan.singh@tataplay.com',
  'region': 'North',
  'sub department': 'Field Service Delivery - General',
  'department': 'Field Service Delivery',
  'grade level': 'M5a',
  'grade': 'M5',
  'designation': 'Assistant Manager - Field Service Delivery',
  'location': 'Noida',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 2,
  'overall employee rating': 3,
  'performance document status': 'Completed'},
 {'employee code': 1130,
  'employee name': 'Tanuja S.',
  'email': 'tanujas@tataplay.com',
  'manager employee code': 1045,
  'manager name': 'Metilda Molly Thomas',
  'manager email': 'mollyt@tataplay.com',
  'region': 'South',
  'sub department': 'Customer Operations - General',
  'department': 'Customer Operations',
  'grade level': 'M5a',
  'grade': 'M5',
  'designation': 'Assistant Manager - Customer Operations',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 3,
  'performance document status': 'Completed'},
 {'employee code': 1182,
  'employee name': 'Munesh Singh Jamwal',
  'email': 'muneshs@tataplay.com',
  'manager employee code': 2934,
  'manager name': 'Vikrant Sehgal',
  'manager email': 'vikrant.sehgal@tataplay.com',
  'region': 'North',
  'sub department': 'Field Service Delivery - General',
  'department': 'Field Service Delivery',
  'grade level': 'M4b',
  'grade': 'M4',
  'designation': 'Manager - Field Service Delivery',
  'location': 'Mohali',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 2,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 1187,
  'employee name': 'Tajinder Pal Singh',
  'email': 'tajinderpals@tataplay.com',
  'manager employee code': 2810,
  'manager name': 'Harit Nagpal',
  'manager email': 'harit.nagpal@tataplay.com',
  'region': 'North',
  'sub department': 'Broadcast/OTT Engineering',
  'department': 'Technology',
  'grade level': 'M2a',
  'grade': 'M2',
  'designation': 'Senior Vice President - Head Broadcast Engineering',
  'location': 'Chattarpur',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': None,
  'overall employee rating': 3,
  'performance document status': 'In progress'},
 {'employee code': 1192,
  'employee name': 'Jaipal Singh Bhandari',
  'email': 'jaipals@tataplay.com',
  'manager employee code': 1760,
  'manager name': 'Rajaneesh Chaubey',
  'manager email': 'rajneeshc@tataplay.com',
  'region': 'North',
  'sub department': 'Consumer Technology',
  'department': 'Technology',
  'grade level': 'M4b',
  'grade': 'M4',
  'designation': 'Manager - Repair Centre',
  'location': 'Chattarpur',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 1205,
  'employee name': 'Vijay Khera',
  'email': 'vijaykh@tataplay.com',
  'manager employee code': 481,
  'manager name': 'Krishan Kansal',
  'manager email': 'krishank@tataplay.com',
  'region': 'North',
  'sub department': 'MIS & Business Information',
  'department': 'Field Service Delivery',
  'grade level': 'M3a',
  'grade': 'M3',
  'designation': 'General Manager - MIS & Business Information',
  'location': 'Noida',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'Approved'},
 {'employee code': 1213,
  'employee name': 'Praveen Singh',
  'email': 'praveensi@tataplay.com',
  'manager employee code': 2934,
  'manager name': 'Vikrant Sehgal',
  'manager email': 'vikrant.sehgal@tataplay.com',
  'region': 'North',
  'sub department': 'Field Service Delivery - General',
  'department': 'Field Service Delivery',
  'grade level': 'M4b',
  'grade': 'M4',
  'designation': 'Manager - Field Service Delivery',
  'location': 'Mohali',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 2,
  'overall employee rating': 3,
  'performance document status': 'Completed'},
 {'employee code': 1252,
  'employee name': 'Soumya Swamy',
  'email': 'soumyas@tataplay.com',
  'manager employee code': 4127,
  'manager name': 'Ashoka B',
  'manager email': 'ashoka.b@tataplay.com',
  'region': 'South',
  'sub department': 'Field Service Delivery - General',
  'department': 'Field Service Delivery',
  'grade level': 'M4b',
  'grade': 'M4',
  'designation': 'Manager - Field Service Delivery',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 3,
  'performance document status': 'Completed'},
 {'employee code': 1308,
  'employee name': 'R. Jayaprakash',
  'email': 'jayaprakashr@tataplay.com',
  'manager employee code': 7955,
  'manager name': 'Dinesh Patwari',
  'manager email': 'Dinesh.Patwari@tataplay.com',
  'region': 'South',
  'sub department': 'Finance - General',
  'department': 'Finance',
  'grade level': 'M3a',
  'grade': 'M3',
  'designation': 'General Manager - Finance',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': None,
  'overall employee rating': 5,
  'performance document status': 'In progress'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'email': 'lenins@tataplay.com',
  'manager employee code': 7227,
  'manager name': 'Vinodkumar Anandan',
  'manager email': 'Vinodkumar.BalakrishnanAnand@tataplay.com',
  'region': 'South',
  'sub department': 'Business Intelligence and Forecasting',
  'department': 'Customer Operations',
  'grade level': 'M3b',
  'grade': 'M3',
  'designation': 'Assistant General Manager - Business Intelligence and Forecasting',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 4,
  'overall employee rating': 5,
  'performance document status': 'Completed'},
 {'employee code': 1314,
  'employee name': 'Ponselvam Devasagayam',
  'email': 'ponselvamd@tataplay.com',
  'manager employee code': 2243,
  'manager name': 'Manjunatha J.S.',
  'manager email': 'manjunathaj@tataplay.com',
  'region': 'South',
  'sub department': 'N.V.S.D',
  'department': 'Customer Operations',
  'grade level': 'M5a',
  'grade': 'M5',
  'designation': 'Assistant Manager - NVSD Customer Admin',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 1345,
  'employee name': 'Jaya N.',
  'email': 'jayan@tataplay.com',
  'manager employee code': 2366,
  'manager name': 'Devadas Shenoy K.P.',
  'manager email': 'devadass@tataplay.com',
  'region': 'South',
  'sub department': 'MIS & Reporting-Sales',
  'department': 'Sales',
  'grade level': 'M4b',
  'grade': 'M4',
  'designation': 'Manager - MIS & Reporting-Sales',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'In progress'},
 {'employee code': 1363,
  'employee name': 'Anup P. Lobo',
  'email': 'anupl@tataplay.com',
  'manager employee code': 4127,
  'manager name': 'Ashoka B',
  'manager email': 'ashoka.b@tataplay.com',
  'region': 'South',
  'sub department': 'Service Training - FSD',
  'department': 'Field Service Delivery',
  'grade level': 'M4b',
  'grade': 'M4',
  'designation': 'Manager - Service Training',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 1377,
  'employee name': 'B.P. Tharamani',
  'email': 'tharamanib@tataplay.com',
  'manager employee code': 5007,
  'manager name': 'Shrinidhi DC',
  'manager email': 'Srinidhi.DC@tataplay.com',
  'region': 'South',
  'sub department': 'Budgeting & AOP',
  'department': 'Customer Operations',
  'grade level': 'M5a',
  'grade': 'M5',
  'designation': 'Assistant Manager - Vendor Management & Outbound Billing Operations',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 1382,
  'employee name': 'C. Sheik Mehaboob Basha',
  'email': 'mehaboobb@tataplay.com',
  'manager employee code': 4182,
  'manager name': 'Brij Mohan Singh',
  'manager email': 'brijmohan.singh@tataplay.com',
  'region': 'North',
  'sub department': 'Service Training - FSD',
  'department': 'Field Service Delivery',
  'grade level': 'M4a',
  'grade': 'M4',
  'designation': 'Senior Manager - Service Training',
  'location': 'Noida',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 2,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 1404,
  'employee name': 'Robin Thomas',
  'email': 'robint@tataplay.com',
  'manager employee code': 4182,
  'manager name': 'Brij Mohan Singh',
  'manager email': 'brijmohan.singh@tataplay.com',
  'region': 'North',
  'sub department': 'Service Training - FSD',
  'department': 'Field Service Delivery',
  'grade level': 'M4a',
  'grade': 'M4',
  'designation': 'Senior Manager - Service Training',
  'location': 'Noida',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 2,
  'overall employee rating': 3,
  'performance document status': 'Completed'},
 {'employee code': 1413,
  'employee name': 'Tejbir Singh',
  'email': 'tejbirs@tataplay.com',
  'manager employee code': 2430,
  'manager name': 'Vishal Sethi',
  'manager email': 'vishal.sethi@tataplay.com',
  'region': 'North',
  'sub department': 'Field Engineering and Audit',
  'department': 'Technology',
  'grade level': 'M5b',
  'grade': 'M5',
  'designation': 'Senior Executive - Quality',
  'location': 'Chattarpur',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 1423,
  'employee name': 'Ashok Kumar Thakur',
  'email': 'ashokt@tataplay.com',
  'manager employee code': 1907,
  'manager name': 'Devinder Singh',
  'manager email': 'devenders@tataplay.com',
  'region': 'North',
  'sub department': 'Supply Chain Services',
  'department': 'Finance',
  'grade level': 'M3b',
  'grade': 'M3',
  'designation': 'Assistant General Manager - Supply Chain Services',
  'location': 'Lucknow',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 1434,
  'employee name': 'Abdul Rahim Nazar',
  'email': 'nazara@tataplay.com',
  'manager employee code': 5377,
  'manager name': 'Reema Kukreja',
  'manager email': 'Reema.Kukreja@tataplay.com',
  'region': 'South',
  'sub department': 'COSSG',
  'department': 'Customer Operations',
  'grade level': 'M3b',
  'grade': 'M3',
  'designation': 'Assistant General Manager - Systems Solutions & Design - COSSG',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 3,
  'performance document status': 'Completed'},
 {'employee code': 1449,
  'employee name': 'A. Suresh',
  'email': 'suresha@tataplay.com',
  'manager employee code': 4069,
  'manager name': 'K Satheesh Kumar',
  'manager email': 'k.satheeshk@tataplay.com',
  'region': 'South',
  'sub department': 'Field Service Delivery - General',
  'department': 'Field Service Delivery',
  'grade level': 'M4b',
  'grade': 'M4',
  'designation': 'Manager - Field Service Delivery',
  'location': 'Chennai',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'Completed'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'email': 'monalisab@tataplay.com',
  'manager employee code': 3631,
  'manager name': 'Sujit Mondal',
  'manager email': 'sujit.mondal@tataplay.com',
  'region': 'East',
  'sub department': 'Field Service Delivery - General',
  'department': 'Field Service Delivery',
  'grade level': 'M3b',
  'grade': 'M3',
  'designation': 'Assistant General Manager - Field Service Delivery',
  'location': 'Guwahati',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 2,
  'overall employee rating': 2,
  'performance document status': 'Approved'},
 {'employee code': 1460,
  'employee name': 'Rajkumar Sau',
  'email': 'rajkumars@tataplay.com',
  'manager employee code': 6441,
  'manager name': 'Sanjeev Kumar',
  'manager email': 'Sanjeev.Kumar@tataplay.com',
  'region': 'East',
  'sub department': 'Trade Sales',
  'department': 'Sales',
  'grade level': 'M4b',
  'grade': 'M4',
  'designation': 'Manager - Trade Sales',
  'location': 'Kolkata',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 3,
  'performance document status': 'Completed'},
 {'employee code': 1470,
  'employee name': 'Rajender Sharma',
  'email': 'rajendras@tataplay.com',
  'manager employee code': 4182,
  'manager name': 'Brij Mohan Singh',
  'manager email': 'brijmohan.singh@tataplay.com',
  'region': 'North',
  'sub department': 'Field Service Delivery - General',
  'department': 'Field Service Delivery',
  'grade level': 'M5a',
  'grade': 'M5',
  'designation': 'Assistant Manager - Field Service Delivery',
  'location': 'Noida',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 3,
  'performance document status': 'Completed'},
 {'employee code': 1480,
  'employee name': 'Sanjay Mittal',
  'email': 'sanjaymi@tataplay.com',
  'manager employee code': 293,
  'manager name': 'Bhagat Bisht',
  'manager email': 'bishtb@tataplay.com',
  'region': 'North',
  'sub department': 'Field Service Delivery - General',
  'department': 'Field Service Delivery',
  'grade level': 'M2a',
  'grade': 'M2',
  'designation': 'Senior Vice President - Field Service Delivery',
  'location': 'Noida',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': None,
  'overall employee rating': 3,
  'performance document status': 'In progress'},
 {'employee code': 1503,
  'employee name': 'Thomas George',
  'email': 'thomasg@tataplay.com',
  'manager employee code': 4329,
  'manager name': 'Hemant Bhatkhande',
  'manager email': 'hemant.bhatkhande@tataplay.com',
  'region': 'South',
  'sub department': 'Business Excellence',
  'department': 'Finance',
  'grade level': 'M3a',
  'grade': 'M3',
  'designation': 'General Manager - Business Excellence',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 4,
  'overall employee rating': 3,
  'performance document status': 'Completed'},
 {'employee code': 1518,
  'employee name': 'R. Malarvizhi',
  'email': 'malarvizhir@tataplay.com',
  'manager employee code': 3082,
  'manager name': 'B. Sidharth Varma',
  'manager email': 'bsidharth.varma@tataplay.com',
  'region': 'South',
  'sub department': 'Field Service Delivery Support',
  'department': 'Field Service Delivery',
  'grade level': 'M4a',
  'grade': 'M4',
  'designation': 'Senior Manager - Field Service Delivery Support',
  'location': 'Hebbal',
  'performance document name': '2025-26 – Q2/H1 (Mid Year)',
  'overall manager rating': 3,
  'overall employee rating': 4,
  'performance document status': 'Approved'},
 {'employee code': 1523,
  'employee name': 'T. Shanmugamanivel',
  'email': 'shanmugamanivelt@tataplay.com',
  'manager employee code': 7494,

In [114]:
dst = db[collection]
result = dst.insert_many(normalized_docs)

## Ddata/PMS Task Status Report All.xlsx

In [117]:
path="Ddata/PMS Task Status Report All.xlsx"
collection="pms_task_status_report_all"
df=pd.read_excel(path)

In [118]:
df.columns

Index(['Perosn Number', 'Name', 'Employee Email ID', 'Manager Person Number',
       'Manager Name', 'Manager Email Address', 'Reviewer Number',
       'Reviewer Name', 'Business Unit', 'Parent Department', 'Sub Department',
       'Grade', 'Sub Grade', 'Employee Evaluation',
       'Employee Evaluation Status', 'Manager Evaluation',
       'Manager Evaluation Status', 'Initiate Approval',
       'Initiate Approval Status', 'Share Document', 'Share Document Status',
       'Final Status'],
      dtype='object')

In [119]:
FIELDS = [
    "Perosn Number",
    "Name",
    "Employee Email ID",
    "Manager Person Number",
    "Manager Name",
    "Manager Email Address",
    "Reviewer Number",
    "Reviewer Name",
    "Business Unit",
    "Parent Department",
    "Sub Department",
    "Grade",
    "Sub Grade",
    "Employee Evaluation",
    "Employee Evaluation Status",
    "Manager Evaluation",
    "Manager Evaluation Status",
    "Initiate Approval",
    "Initiate Approval Status",
    "Share Document",
    "Share Document Status",
    "Final Status"
]

KEY_RENAMES = {
    "Perosn Number": "employee code",
    "Name": "employee name",
    "Employee Email ID": "email",

    "Manager Person Number": "manager employee code",
    "Manager Name": "manager name",
    "Manager Email Address": "manager email",

    "Reviewer Number": "reviewer employee code",
    "Reviewer Name": "reviewer name",

    "Business Unit": "region",
    "Parent Department": "department",
    "Sub Department": "sub department",

    "Grade": "grade",
    "Sub Grade": "grade level",

    "Employee Evaluation": "employee evaluation",
    "Employee Evaluation Status": "employee evaluation status",

    "Manager Evaluation": "manager evaluation",
    "Manager Evaluation Status": "manager evaluation status",

    "Initiate Approval": "initiate approval",
    "Initiate Approval Status": "initiate approval status",

    "Share Document": "share document",
    "Share Document Status": "share document status",

    "Final Status": "final status"
}


NUMERIC_FIELDS = [
    "employee code",
    "manager employee code",
    "reviewer employee code",
]

DATE_FIELDS = []

In [122]:
raw_docs = []

# Convert each DF row → raw dict
for idx, row in df.iterrows():
    raw_doc = row.to_dict()


    raw_docs.append(raw_doc)

# Normalize
normalized_docs = [
    normalize_doc_generic(
        doc,
        FIELDS,
        KEY_RENAMES,
        NUMERIC_FIELDS,
        DATE_FIELDS
    )
    for doc in raw_docs
]

In [123]:
normalized_docs

[{'employee code': 1004,
  'employee name': 'Gyanendra Singh',
  'email': 'gyanendras@tataplay.com',
  'manager employee code': 2430,
  'manager name': 'Vishal Sethi',
  'manager email': 'vishal.sethi@tataplay.com',
  'reviewer employee code': 1626,
  'reviewer name': 'Suman Kumar Ghosh',
  'region': 'North',
  'department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'grade': 'M5',
  'grade level': 'M5a',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1034,
  'employee name': 'Monoranjon Dutta',
  'email': 'manoranjand@tataplay.com',
  'manager employee code': 4922,
  'manager name': 'Joydeep Roy',
  'manager email': 'Joydeep.Roy@tataplay.com',
  'reviewer employee code': 3631,
  'reviewer name': 'Sujit Mondal',
  'region': 'East',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4a',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1045,
  'employee name': 'Metilda Molly Thomas',
  'email': 'mollyt@tataplay.com',
  'manager employee code': 5922,
  'manager name': 'Nipun Sharma',
  'manager email': 'Nipun.Sharma@tataplay.com',
  'reviewer employee code': 293,
  'reviewer name': 'Bhagat Bisht',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'READY',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1060,
  'employee name': 'Thangudu Srinivasa Rao',
  'email': 'srinivasar@tataplay.com',
  'manager employee code': 4127,
  'manager name': 'Ashoka B',
  'manager email': 'ashoka.b@tataplay.com',
  'reviewer employee code': 3082,
  'reviewer name': 'B. Sidharth Varma',
  'region': 'South',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 107,
  'employee name': 'Chirag P. Thakar',
  'email': 'chiragt@tataplay.com',
  'manager employee code': 2747,
  'manager name': 'Avinash Kesherwani',
  'manager email': 'avinash.kesherwani@tataplay.com',
  'reviewer employee code': 7955,
  'reviewer name': 'Dinesh Patwari',
  'region': 'Corporate',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'grade': 'M3',
  'grade level': 'M3b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1088,
  'employee name': 'Arun Dharampal',
  'email': 'arund@tataplay.com',
  'manager employee code': 4182,
  'manager name': 'Brij Mohan Singh',
  'manager email': 'brijmohan.singh@tataplay.com',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1107,
  'employee name': 'Ravi Pratap Singh',
  'email': 'raviprataps@tataplay.com',
  'manager employee code': 4182,
  'manager name': 'Brij Mohan Singh',
  'manager email': 'brijmohan.singh@tataplay.com',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5a',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1130,
  'employee name': 'Tanuja S.',
  'email': 'tanujas@tataplay.com',
  'manager employee code': 1045,
  'manager name': 'Metilda Molly Thomas',
  'manager email': 'mollyt@tataplay.com',
  'reviewer employee code': 5922,
  'reviewer name': 'Nipun Sharma',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'grade': 'M5',
  'grade level': 'M5a',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1182,
  'employee name': 'Munesh Singh Jamwal',
  'email': 'muneshs@tataplay.com',
  'manager employee code': 2934,
  'manager name': 'Vikrant Sehgal',
  'manager email': 'vikrant.sehgal@tataplay.com',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1187,
  'employee name': 'Tajinder Pal Singh',
  'email': 'tajinderpals@tataplay.com',
  'manager employee code': 2810,
  'manager name': 'Harit Nagpal',
  'manager email': 'harit.nagpal@tataplay.com',
  'reviewer employee code': None,
  'reviewer name': 'nan',
  'region': 'North',
  'department': 'Technology',
  'sub department': 'Broadcast/OTT Engineering',
  'grade': 'M2',
  'grade level': 'M2a',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'READY',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'NOT COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'NOT COMPLETED',
  'final status': 'PENDING WITH MANAGER'},
 {'employee code': 1192,
  'employee name': 'Jaipal Singh Bhandari',
  'email': 'jaipals@tataplay.com',
  'manager employee code': 1760,
  'manager name': 'Rajaneesh Chaubey',
  'manager email': 'rajneeshc@tataplay.com',
  'reviewer employee code': 2536,
  'reviewer name': 'Kundan Singh',
  'region': 'North',
  'department': 'Technology',
  'sub department': 'Consumer Technology',
  'grade': 'M4',
  'grade level': 'M4b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1205,
  'employee name': 'Vijay Khera',
  'email': 'vijaykh@tataplay.com',
  'manager employee code': 481,
  'manager name': 'Krishan Kansal',
  'manager email': 'krishank@tataplay.com',
  'reviewer employee code': 293,
  'reviewer name': 'Bhagat Bisht',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'MIS & Business Information',
  'grade': 'M3',
  'grade level': 'M3a',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'READY',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1213,
  'employee name': 'Praveen Singh',
  'email': 'praveensi@tataplay.com',
  'manager employee code': 2934,
  'manager name': 'Vikrant Sehgal',
  'manager email': 'vikrant.sehgal@tataplay.com',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1252,
  'employee name': 'Soumya Swamy',
  'email': 'soumyas@tataplay.com',
  'manager employee code': 4127,
  'manager name': 'Ashoka B',
  'manager email': 'ashoka.b@tataplay.com',
  'reviewer employee code': 3082,
  'reviewer name': 'B. Sidharth Varma',
  'region': 'South',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'email': 'lenins@tataplay.com',
  'manager employee code': 7227,
  'manager name': 'Vinodkumar Anandan',
  'manager email': 'Vinodkumar.BalakrishnanAnand@tataplay.com',
  'reviewer employee code': 2039,
  'reviewer name': 'Pavan Kumar Muktapuram',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'grade': 'M3',
  'grade level': 'M3b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1314,
  'employee name': 'Ponselvam Devasagayam',
  'email': 'ponselvamd@tataplay.com',
  'manager employee code': 2243,
  'manager name': 'Manjunatha J.S.',
  'manager email': 'manjunathaj@tataplay.com',
  'reviewer employee code': 4895,
  'reviewer name': 'S Suresh Babu',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'N.V.S.D',
  'grade': 'M5',
  'grade level': 'M5a',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1345,
  'employee name': 'Jaya N.',
  'email': 'jayan@tataplay.com',
  'manager employee code': 2366,
  'manager name': 'Devadas Shenoy K.P.',
  'manager email': 'devadass@tataplay.com',
  'reviewer employee code': 3633,
  'reviewer name': 'Sanil Chawla',
  'region': 'South',
  'department': 'Sales',
  'sub department': 'MIS & Reporting-Sales',
  'grade': 'M4',
  'grade level': 'M4b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'READY',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'NOT COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'NOT COMPLETED',
  'final status': 'PENDING WITH MANAGER'},
 {'employee code': 1363,
  'employee name': 'Anup P. Lobo',
  'email': 'anupl@tataplay.com',
  'manager employee code': 4127,
  'manager name': 'Ashoka B',
  'manager email': 'ashoka.b@tataplay.com',
  'reviewer employee code': 3082,
  'reviewer name': 'B. Sidharth Varma',
  'region': 'South',
  'department': 'Field Service Delivery',
  'sub department': 'Service Training - FSD',
  'grade': 'M4',
  'grade level': 'M4b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1377,
  'employee name': 'B.P. Tharamani',
  'email': 'tharamanib@tataplay.com',
  'manager employee code': 5007,
  'manager name': 'Shrinidhi DC',
  'manager email': 'Srinidhi.DC@tataplay.com',
  'reviewer employee code': 2039,
  'reviewer name': 'Pavan Kumar Muktapuram',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'Budgeting & AOP',
  'grade': 'M5',
  'grade level': 'M5a',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1382,
  'employee name': 'C. Sheik Mehaboob Basha',
  'email': 'mehaboobb@tataplay.com',
  'manager employee code': 4182,
  'manager name': 'Brij Mohan Singh',
  'manager email': 'brijmohan.singh@tataplay.com',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'Service Training - FSD',
  'grade': 'M4',
  'grade level': 'M4a',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1404,
  'employee name': 'Robin Thomas',
  'email': 'robint@tataplay.com',
  'manager employee code': 4182,
  'manager name': 'Brij Mohan Singh',
  'manager email': 'brijmohan.singh@tataplay.com',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'region': 'North',
  'department': 'Field Service Delivery',
  'sub department': 'Service Training - FSD',
  'grade': 'M4',
  'grade level': 'M4a',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1413,
  'employee name': 'Tejbir Singh',
  'email': 'tejbirs@tataplay.com',
  'manager employee code': 2430,
  'manager name': 'Vishal Sethi',
  'manager email': 'vishal.sethi@tataplay.com',
  'reviewer employee code': 1626,
  'reviewer name': 'Suman Kumar Ghosh',
  'region': 'North',
  'department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'grade': 'M5',
  'grade level': 'M5b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1423,
  'employee name': 'Ashok Kumar Thakur',
  'email': 'ashokt@tataplay.com',
  'manager employee code': 1907,
  'manager name': 'Devinder Singh',
  'manager email': 'devenders@tataplay.com',
  'reviewer employee code': 4771,
  'reviewer name': 'Anil Dalvi',
  'region': 'North',
  'department': 'Finance',
  'sub department': 'Supply Chain Services',
  'grade': 'M3',
  'grade level': 'M3b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1434,
  'employee name': 'Abdul Rahim Nazar',
  'email': 'nazara@tataplay.com',
  'manager employee code': 5377,
  'manager name': 'Reema Kukreja',
  'manager email': 'Reema.Kukreja@tataplay.com',
  'reviewer employee code': 5922,
  'reviewer name': 'Nipun Sharma',
  'region': 'South',
  'department': 'Customer Operations',
  'sub department': 'COSSG',
  'grade': 'M3',
  'grade level': 'M3b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1449,
  'employee name': 'A. Suresh',
  'email': 'suresha@tataplay.com',
  'manager employee code': 4069,
  'manager name': 'K Satheesh Kumar',
  'manager email': 'k.satheeshk@tataplay.com',
  'reviewer employee code': 3082,
  'reviewer name': 'B. Sidharth Varma',
  'region': 'South',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'employee evaluation': 'WSEVAL',
  'employee evaluation status': 'COMPLETED',
  'manager evaluation': 'MGREVAL',
  'manager evaluation status': 'COMPLETED',
  'initiate approval': 'FAPPR',
  'initiate approval status': 'COMPLETED',
  'share document': 'SHRPDOC',
  'share document status': 'COMPLETED',
  'final status': 'DOCUMENT APPROVED'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'email': 'monalisab@tataplay.com',
  'manager employee code': 3631,
  'manager name': 'Sujit Mondal',
  'manager email': 'sujit.mondal@tataplay.com',
  'reviewer employee code': 293,
  'reviewer name': 'Bhagat Bisht',
  'region': 'East',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M3',
  'grade level': 'M3b',
  'employee evaluation': 'WSEVAL',

In [124]:
dst = db[collection]
result = dst.insert_many(normalized_docs)

## Ddata/Probation Confirmation Report.xls

In [135]:


path="Ddata/Probation Confirmation Report.xls"
collection="probation_confirmation_report"
df=pd.read_excel(path,engine="xlrd")

XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'MIME-Ver'

## Ddata\8.Leave Transaction With Balance Report_Leave Transaction With Balance Report (3).xlsx

In [22]:
path="Ddata\8.Leave Transaction With Balance Report_Leave Transaction With Balance Report (3).xlsx"
collection="leave_transaction_with_balance_report_leave_transaction_with_balance_report"
df=pd.read_excel(path,skiprows=1)

<>:1: SyntaxWarning: invalid escape sequence '\8'
<>:1: SyntaxWarning: invalid escape sequence '\8'
C:\Users\SaptarshiBanik\AppData\Local\Temp\ipykernel_3332\3302636102.py:1: SyntaxWarning: invalid escape sequence '\8'
  path="Ddata\8.Leave Transaction With Balance Report_Leave Transaction With Balance Report (3).xlsx"

In [23]:
df.columns

Index(['EMPLOYEE_CODE', 'NAME', 'EMPLOYEE_EMAIL_ADDRESS', 'ABSENCE_NAME',
       'START_DATE', 'END_DATE', 'DURATION', 'STATUS_OF_LEAVE',
       'APPROVAL_STATUS', 'MANAGER_EMAIL', 'BALANCE_VAL'],
      dtype='object')

In [24]:
FIELDS = [
    "EMPLOYEE_CODE",
    "NAME",
    "EMPLOYEE_EMAIL_ADDRESS",
    "ABSENCE_NAME",
    "START_DATE",
    "END_DATE",
    "DURATION",
    "STATUS_OF_LEAVE",
    "APPROVAL_STATUS",
    "MANAGER_EMAIL",
    "BALANCE_VAL"
]


KEY_RENAMES = {
    "EMPLOYEE_CODE": "employee code",
    "NAME": "employee name",
    "EMPLOYEE_EMAIL_ADDRESS": "email",
    "ABSENCE_NAME": "absence name",
    "START_DATE": "start date",
    "END_DATE": "end date",
    "DURATION": "duration",
    "STATUS_OF_LEAVE": "status of leave",
    "APPROVAL_STATUS": "approval status",
    "MANAGER_EMAIL": "manager email",
    "BALANCE_VAL": "balance value"
}

NUMERIC_FIELDS = [
    "employee code",
    "duration",
    "balance value"
]

DATE_FIELDS = [
    "start date",
    "end date"
]

In [26]:
raw_docs = []
df = df.where(df.notna(), None)
# Convert each DF row → raw dict
for idx, row in df.iterrows():
    raw_doc = row.to_dict()


    raw_docs.append(raw_doc)

# Normalize
normalized_docs = [
    normalize_doc_generic(
        doc,
        FIELDS,
        KEY_RENAMES,
        NUMERIC_FIELDS,
        DATE_FIELDS
    )
    for doc in raw_docs
]

In [27]:
normalized_docs

[{'employee code': 4598,
  'employee name': 'Bhuvnesh',
  'email': 'Bhuvnesh.Sharma@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 5, 30, 0, 0),
  'end date': datetime.datetime(2025, 5, 30, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'ravinder.tyagi@tataplay.com',
  'balance value': 11},
 {'employee code': 4598,
  'employee name': 'Bhuvnesh',
  'email': 'Bhuvnesh.Sharma@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': datetime.datetime(2025, 5, 9, 0, 0),
  'end date': datetime.datetime(2025, 5, 9, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'ravinder.tyagi@tataplay.com',
  'balance value': 11},
 {'employee code': 4598,
  'employee name': 'Bhuvnesh',
  'email': 'Bhuvnesh.Sharma@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 1, 30, 0, 0),
  'end date': datetime.datetime(2025, 2, 3, 0, 0),
  'duration': 3,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'ravinder.tyagi@tataplay.com',
  'balance value': 45},
 {'employee code': 4606,
  'employee name': 'Jitendra',
  'email': 'Jitendra.Singh@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 8, 22, 0, 0),
  'end date': datetime.datetime(2025, 8, 22, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'himanshu.verma@tataplay.com',
  'balance value': 45},
 {'employee code': 4606,
  'employee name': 'Jitendra',
  'email': 'Jitendra.Singh@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 5, 29, 0, 0),
  'end date': datetime.datetime(2025, 5, 29, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'himanshu.verma@tataplay.com',
  'balance value': 10},
 {'employee code': 4606,
  'employee name': 'Jitendra',
  'email': 'Jitendra.Singh@tataplay.com',
  'absence name': 'Sick Leave',
  'start date': datetime.datetime(2025, 6, 5, 0, 0),
  'end date': datetime.datetime(2025, 6, 5, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'himanshu.verma@tataplay.com',
  'balance value': 29},
 {'employee code': 2761,
  'employee name': 'Sandhya',
  'email': 'sandhya.mulchandani@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': datetime.datetime(2025, 8, 7, 0, 0),
  'end date': datetime.datetime(2025, 8, 7, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'sanil.chawla@tataplay.com',
  'balance value': 10},
 {'employee code': 2761,
  'employee name': 'Sandhya',
  'email': 'sandhya.mulchandani@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2024, 11, 26, 0, 0),
  'end date': datetime.datetime(2024, 11, 29, 0, 0),
  'duration': 4,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'sanil.chawla@tataplay.com',
  'balance value': 45},
 {'employee code': 2761,
  'employee name': 'Sandhya',
  'email': 'sandhya.mulchandani@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 8, 29, 0, 0),
  'end date': datetime.datetime(2025, 8, 29, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'sanil.chawla@tataplay.com',
  'balance value': 7},
 {'employee code': 2461,
  'employee name': 'Dillip Kumar',
  'email': 'dillip.samantaray@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 8, 25, 0, 0),
  'end date': datetime.datetime(2025, 8, 25, 0, 0),
  'duration': 0,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'vijay.sharma@tataplay.com',
  'balance value': 7},
 {'employee code': 2461,
  'employee name': 'Dillip Kumar',
  'email': 'dillip.samantaray@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': datetime.datetime(2025, 4, 29, 0, 0),
  'end date': datetime.datetime(2025, 4, 30, 0, 0),
  'duration': 2,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'vijay.sharma@tataplay.com',
  'balance value': 10},
 {'employee code': 2461,
  'employee name': 'Dillip Kumar',
  'email': 'dillip.samantaray@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 9, 29, 0, 0),
  'end date': datetime.datetime(2025, 10, 3, 0, 0),
  'duration': 4,
  'status of leave': 'SUBMITTED',
  'approval status': 'AWAITING',
  'manager email': 'vijay.sharma@tataplay.com',
  'balance value': 41},
 {'employee code': 4036,
  'employee name': 'Gautam',
  'email': 'gautam.sah@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': None,
  'end date': None,
  'duration': None,
  'status of leave': 'NA',
  'approval status': 'NA',
  'manager email': 'sandeep.mann@tataplay.com',
  'balance value': 12},
 {'employee code': 4036,
  'employee name': 'Gautam',
  'email': 'gautam.sah@tataplay.com',
  'absence name': 'Sick Leave',
  'start date': None,
  'end date': None,
  'duration': None,
  'status of leave': 'NA',
  'approval status': 'NA',
  'manager email': 'sandeep.mann@tataplay.com',
  'balance value': 30},
 {'employee code': 4036,
  'employee name': 'Gautam',
  'email': 'gautam.sah@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 9, 17, 0, 0),
  'end date': datetime.datetime(2025, 9, 17, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'sandeep.mann@tataplay.com',
  'balance value': 39},
 {'employee code': 2335,
  'employee name': 'Mini',
  'email': 'miniv@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 9, 24, 0, 0),
  'end date': datetime.datetime(2025, 9, 26, 0, 0),
  'duration': 3,
  'status of leave': 'SUBMITTED',
  'approval status': 'AWAITING',
  'manager email': 'manjunathaj@tataplay.com',
  'balance value': 37},
 {'employee code': 2335,
  'employee name': 'Mini',
  'email': 'miniv@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': datetime.datetime(2025, 9, 2, 0, 0),
  'end date': datetime.datetime(2025, 9, 2, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'manjunathaj@tataplay.com',
  'balance value': 8},
 {'employee code': 2335,
  'employee name': 'Mini',
  'email': 'miniv@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 8, 1, 0, 0),
  'end date': datetime.datetime(2025, 8, 1, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'manjunathaj@tataplay.com',
  'balance value': 10},
 {'employee code': 2353,
  'employee name': 'Arun',
  'email': 'arunsa@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 9, 10, 0, 0),
  'end date': datetime.datetime(2025, 9, 10, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'jobys@tataplay.com',
  'balance value': 11},
 {'employee code': 2353,
  'employee name': 'Arun',
  'email': 'arunsa@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': datetime.datetime(2025, 2, 27, 0, 0),
  'end date': datetime.datetime(2025, 2, 28, 0, 0),
  'duration': 2,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'jobys@tataplay.com',
  'balance value': 10},
 {'employee code': 2353,
  'employee name': 'Arun',
  'email': 'arunsa@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 5, 2, 0, 0),
  'end date': datetime.datetime(2025, 5, 2, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'jobys@tataplay.com',
  'balance value': 45},
 {'employee code': 3122,
  'employee name': 'Dilip Kumar',
  'email': 'dilipkumar.mandal@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 10, 1, 0, 0),
  'end date': datetime.datetime(2025, 10, 3, 0, 0),
  'duration': 2,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'krishank@tataplay.com',
  'balance value': 7},
 {'employee code': 3122,
  'employee name': 'Dilip Kumar',
  'email': 'dilipkumar.mandal@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': None,
  'end date': None,
  'duration': None,
  'status of leave': 'NA',
  'approval status': 'NA',
  'manager email': 'krishank@tataplay.com',
  'balance value': 15},
 {'employee code': 3122,
  'employee name': 'Dilip Kumar',
  'email': 'dilipkumar.mandal@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 6, 11, 0, 0),
  'end date': datetime.datetime(2025, 6, 13, 0, 0),
  'duration': 3,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'krishank@tataplay.com',
  'balance value': 45},
 {'employee code': 2214,
  'employee name': 'Aftab',
  'email': 'aftabk@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': None,
  'end date': None,
  'duration': None,
  'status of leave': 'NA',
  'approval status': 'NA',
  'manager email': 'lokeshk@tataplay.com',
  'balance value': 12},
 {'employee code': 2214,
  'employee name': 'Aftab',
  'email': 'aftabk@tataplay.com',
  'absence name': 'Sick Leave',
  'start date': datetime.datetime(2025, 8, 5, 0, 0),
  'end date': datetime.datetime(2025, 8, 5, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'lokeshk@tataplay.com',
  'balance value': 29},
 {'employee code': 2214,
  'employee name': 'Aftab',
  'email': 'aftabk@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 7, 7, 0, 0),
  'end date': datetime.datetime(2025, 7, 8, 0, 0),
  'duration': 2,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'lokeshk@tataplay.com',
  'balance value': 45},
 {'employee code': 4247,
  'employee name': 'B Kiran',
  'email': 'bkiran.kumar@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 9, 10, 0, 0),
  'end date': datetime.datetime(2025, 9, 10, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'AWAITING',
  'manager email': 'harinath.kotwal@tataplay.com',
  'balance value': 5},
 {'employee code': 4247,
  'employee name': 'B Kiran',
  'email': 'bkiran.kumar@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': datetime.datetime(2024, 5, 20, 0, 0),
  'end date': datetime.datetime(2024, 5, 21, 0, 0),
  'duration': 2,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'harinath.kotwal@tataplay.com',
  'balance value': 12},
 {'employee code': 4247,
  'employee name': 'B Kiran',
  'email': 'bkiran.kumar@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2024, 1, 22, 0, 0),
  'end date': datetime.datetime(2024, 1, 22, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'harinath.kotwal@tataplay.com',
  'balance value': 60},
 {'employee code': 2963,
  'employee name': 'Mahendra Singh',
  'email': 'mahendra.jadaun@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 4, 15, 0, 0),
  'end date': datetime.datetime(2025, 4, 15, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'jobys@tataplay.com',
  'balance value': 9},
 {'employee code': 2963,
  'employee name': 'Mahendra Singh',
  'email': 'mahendra.jadaun@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': datetime.datetime(2025, 8, 25, 0, 0),
  'end date': datetime.datetime(2025, 8, 25, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'jobys@tataplay.com',
  'balance value': 5},
 {'employee code': 2963,
  'employee name': 'Mahendra Singh',
  'email': 'mahendra.jadaun@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 7, 14, 0, 0),
  'end date': datetime.datetime(2025, 7, 18, 0, 0),
  'duration': 5,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'jobys@tataplay.com',
  'balance value': 28},
 {'employee code': 3978,
  'employee name': 'Ajay',
  'email': 'ajay.kumar@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 6, 10, 0, 0),
  'end date': datetime.datetime(2025, 6, 10, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'deepakna@tataplay.com',
  'balance value': 9},
 {'employee code': 3978,
  'employee name': 'Ajay',
  'email': 'ajay.kumar@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': None,
  'end date': None,
  'duration': None,
  'status of leave': 'NA',
  'approval status': 'NA',
  'manager email': 'deepakna@tataplay.com',
  'balance value': 12},
 {'employee code': 3978,
  'employee name': 'Ajay',
  'email': 'ajay.kumar@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2023, 5, 18, 0, 0),
  'end date': datetime.datetime(2023, 5, 19, 0, 0),
  'duration': 2,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'deepakna@tataplay.com',
  'balance value': 45},
 {'employee code': 796,
  'employee name': 'Pintoo',
  'email': 'pintook@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': None,
  'end date': None,
  'duration': None,
  'status of leave': 'NA',
  'approval status': 'NA',
  'manager email': 'brijmohan.singh@tataplay.com',
  'balance value': 12},
 {'employee code': 796,
  'employee name': 'Pintoo',
  'email': 'pintook@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': datetime.datetime(2025, 7, 21, 0, 0),
  'end date': datetime.datetime(2025, 7, 22, 0, 0),
  'duration': 2,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'brijmohan.singh@tataplay.com',
  'balance value': 6},
 {'employee code': 796,
  'employee name': 'Pintoo',
  'email': 'pintook@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 6, 27, 0, 0),
  'end date': datetime.datetime(2025, 6, 27, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'brijmohan.singh@tataplay.com',
  'balance value': 45},
 {'employee code': 3332,
  'employee name': 'Pintulal',
  'email': 'pintulal.halder@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 9, 29, 0, 0),
  'end date': datetime.datetime(2025, 9, 29, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'Joydeep.Roy@tataplay.com',
  'balance value': 52},
 {'employee code': 3332,
  'employee name': 'Pintulal',
  'email': 'pintulal.halder@tataplay.com',
  'absence name': 'Sick Leave',
  'start date': datetime.datetime(2025, 6, 26, 0, 0),
  'end date': datetime.datetime(2025, 6, 27, 0, 0),
  'duration': 2,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'Joydeep.Roy@tataplay.com',
  'balance value': 27},
 {'employee code': 3332,
  'employee name': 'Pintulal',
  'email': 'pintulal.halder@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 10, 6, 0, 0),
  'end date': datetime.datetime(2025, 10, 6, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'Joydeep.Roy@tataplay.com',
  'balance value': 45},
 {'employee code': 2690,
  'employee name': 'Mohit',
  'email': 'mohit.ghai@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2025, 9, 15, 0, 0),
  'end date': datetime.datetime(2025, 9, 15, 0, 0),
  'duration': 0,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'sanil.chawla@tataplay.com',
  'balance value': 1},
 {'employee code': 2690,
  'employee name': 'Mohit',
  'email': 'mohit.ghai@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': datetime.datetime(2024, 5, 3, 0, 0),
  'end date': datetime.datetime(2024, 5, 3, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'sanil.chawla@tataplay.com',
  'balance value': 15},
 {'employee code': 2690,
  'employee name': 'Mohit',
  'email': 'mohit.ghai@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 1, 31, 0, 0),
  'end date': datetime.datetime(2025, 1, 31, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'sanil.chawla@tataplay.com',
  'balance value': 45},
 {'employee code': 630,
  'employee name': 'Jayeeta',
  'email': 'jayeetac@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2024, 5, 13, 0, 0),
  'end date': datetime.datetime(2024, 5, 13, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'sujit.mondal@tataplay.com',
  'balance value': 56},
 {'employee code': 630,
  'employee name': 'Jayeeta',
  'email': 'jayeetac@tataplay.com',
  'absence name': 'Sick Leave   .',
  'start date': None,
  'end date': None,
  'duration': None,
  'status of leave': 'NA',
  'approval status': 'NA',
  'manager email': 'sujit.mondal@tataplay.com',
  'balance value': 14},
 {'employee code': 630,
  'employee name': 'Jayeeta',
  'email': 'jayeetac@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 9, 5, 0, 0),
  'end date': datetime.datetime(2025, 9, 15, 0, 0),
  'duration': 7,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'sujit.mondal@tataplay.com',
  'balance value': 38},
 {'employee code': 3447,
  'employee name': 'Narayanan',
  'email': 'narayananp@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': datetime.datetime(2024, 9, 18, 0, 0),
  'end date': datetime.datetime(2024, 9, 19, 0, 0),
  'duration': 2,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'rabiyas@tataplay.com',
  'balance value': 12},
 {'employee code': 3447,
  'employee name': 'Narayanan',
  'email': 'narayananp@tataplay.com',
  'absence name': 'Sick Leave',
  'start date': datetime.datetime(2025, 7, 21, 0, 0),
  'end date': datetime.datetime(2025, 7, 22, 0, 0),
  'duration': 2,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'rabiyas@tataplay.com',
  'balance value': 26},
 {'employee code': 3447,
  'employee name': 'Narayanan',
  'email': 'narayananp@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 5, 19, 0, 0),
  'end date': datetime.datetime(2025, 5, 30, 0, 0),
  'duration': 10,
  'status of leave': 'SUBMITTED',
  'approval status': 'NA',
  'manager email': 'rabiyas@tataplay.com',
  'balance value': 45},
 {'employee code': 3951,
  'employee name': 'Manisha',
  'email': 'manisha.vasaikar@tataplay.com',
  'absence name': 'Annual -Leave',
  'start date': datetime.datetime(2025, 8, 28, 0, 0),
  'end date': datetime.datetime(2025, 8, 28, 0, 0),
  'duration': 1,
  'status of leave': 'SUBMITTED',
  'approval status': 'AWAITING',
  'manager email': 'lalitg@tataplay.com',
  'balance value': 45},
 {'employee code': 3951,
  'employee name': 'Manisha',
  'email': 'manisha.vasaikar@tataplay.com',
  'absence name': 'Casual Leave',
  'start date': None,
  'end date': None,
  'duration': None,
  'status of leave': 'NA',
  'approval status': 'NA',
  'manager email': 'lalitg@tataplay.com',
  'balance value': 12},
 {'employee code': 3951,
  'employee name': 'Manisha',
  'email': 'manisha.vasaikar@tataplay.com',
  'absence name': 'Sick Leave',
  'start date': datetime.datetime(2025, 6, 19, 0, 0),

In [28]:
dst = db[collection]
result = dst.insert_many(normalized_docs)

## Ddata\Goal Detail Report.xlsx

In [43]:
path="Ddata\Goal Detail Report.xlsx"
collection="goal_detail_report"
df=pd.read_excel(path,skiprows=1)

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\SaptarshiBanik\AppData\Local\Temp\ipykernel_3332\3362400384.py:1: SyntaxWarning: invalid escape sequence '\G'
  path="Ddata\Goal Detail Report.xlsx"

In [44]:
df.columns

Index(['Person Number', 'First Name', 'Last Name', 'Department',
       'Sub Department', 'Grade', 'Sub Grade', 'Business Unit', 'Goal Type',
       'Goal Name', 'Goal Desciption', 'Start Date', 'Target Completion Date',
       'Creation Date', 'Development Goal Status', 'Category',
       'Manager_Approval_Date'],
      dtype='object')

In [45]:
FIELDS = [
    "Person Number",
    "First Name",
    "Last Name",
    "Department",
    "Sub Department",
    "Grade",
    "Sub Grade",
    "Business Unit",
    "Goal Type",
    "Goal Name",
    "Goal Desciption",
    "Start Date",
    "Target Completion Date",
    "Creation Date",
    "Development Goal Status",
    "Category",
    "Manager_Approval_Date"
]

KEY_RENAMES = {
    "Person Number": "employee code",
    "First Name": "first name",
    "Last Name": "last name",
    "Department": "department",
    "Sub Department": "sub department",
    "Grade": "grade",
    "Sub Grade": "grade level",
    "Business Unit": "region",
    "Goal Type": "goal type",
    "Goal Name": "goal name",
    "Goal Desciption": "goal description",
    "Start Date": "start date",
    "Target Completion Date": "target completion date",
    "Creation Date": "creation date",
    "Development Goal Status": "development goal status",
    "Category": "category",
    "Manager_Approval_Date": "manager approval date"
}

NUMERIC_FIELDS = [
    "employee code",
]

DATE_FIELDS = [
    "start date",
    "target completion date",
    "creation date",
    "manager approval date"
]

In [46]:
raw_docs = []
df = df.where(df.notna(), None)
# Convert each DF row → raw dict
for idx, row in df.iterrows():
    raw_doc = row.to_dict()


    raw_docs.append(raw_doc)

# Normalize
normalized_docs = [
    normalize_doc_generic(
        doc,
        FIELDS,
        KEY_RENAMES,
        NUMERIC_FIELDS,
        DATE_FIELDS
    )
    for doc in raw_docs
]

In [47]:
normalized_docs

[{'employee code': 1004,
  'first name': 'Gyanendra',
  'last name': 'Singh',
  'department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Chase Result',
  'goal description': 'Improvement will be seen in 3P audit reports as wrong reporting cases will be decreased',
  'start date': datetime.datetime(2020, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2021, 3, 31, 0, 0),
  'creation date': datetime.datetime(2020, 10, 14, 5, 54, 27, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1034,
  'first name': 'Monoranjon',
  'last name': 'Dutta',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4a',
  'region': 'East',
  'goal type': 'DEVELOPMENT',
  'goal name': 'FSD - Inventory Management',
  'goal description': 'ISP get debited for un necessary block the high ageing defective without collecting from TSRA & no doing RIT on time for which ISP got huge amount debited , Here Non ESN box got major impact. Awarness programme , repeated follow up ,publish Ageing wise details, put pressure on RIT,  Also un used materials lying with ISP , non sereialised Defective also not sending regularly. We have to make a habit to do RIT timr to time.',
  'start date': datetime.datetime(2020, 10, 1, 0, 0),
  'target completion date': None,
  'creation date': datetime.datetime(2020, 10, 19, 17, 17, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1034,
  'first name': 'Monoranjon',
  'last name': 'Dutta',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4a',
  'region': 'East',
  'goal type': 'DEVELOPMENT',
  'goal name': 'FSD - Partner Management',
  'goal description': 'Will have to Educate all TSRA benefit of mService , This tools will empowered our TSRA to great extend',
  'start date': datetime.datetime(2020, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2021, 12, 31, 0, 0),
  'creation date': datetime.datetime(2021, 10, 8, 17, 37, 33, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1034,
  'first name': 'Monoranjon',
  'last name': 'Dutta',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4a',
  'region': 'East',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Deliver Results',
  'goal description': 'Proper Training to field team',
  'start date': datetime.datetime(2022, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2023, 3, 31, 0, 0),
  'creation date': datetime.datetime(2022, 11, 30, 6, 27, 22, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1045,
  'first name': 'Metilda Molly',
  'last name': 'Thomas',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Partner Well',
  'goal description': 'NA',
  'start date': datetime.datetime(2020, 11, 2, 0, 0),
  'target completion date': datetime.datetime(2021, 3, 30, 0, 0),
  'creation date': datetime.datetime(2020, 10, 19, 12, 0, 56, 620000, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': '20% - Social learning',
  'manager approval date': None},
 {'employee code': 1045,
  'first name': 'Metilda Molly',
  'last name': 'Thomas',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Analyze',
  'goal description': 'NA',
  'start date': datetime.datetime(2020, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2020, 11, 1, 0, 0),
  'creation date': datetime.datetime(2020, 10, 19, 11, 57, 10, 908000, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': '10% - Formal learning',
  'manager approval date': None},
 {'employee code': 1045,
  'first name': 'Metilda Molly',
  'last name': 'Thomas',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Put Customer First',
  'goal description': 'Have started on call listening for NPS project',
  'start date': datetime.datetime(2020, 7, 20, 0, 0),
  'target completion date': datetime.datetime(2021, 3, 31, 0, 0),
  'creation date': datetime.datetime(2020, 10, 19, 11, 53, 54, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1060,
  'first name': 'Thangudu',
  'last name': 'Srinivasa Rao',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Chase Results',
  'goal description': 'Started From 1st October 2021 and target on 31st Mar-22.',
  'start date': datetime.datetime(2021, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2022, 3, 31, 0, 0),
  'creation date': datetime.datetime(2020, 10, 14, 9, 8, 56, 666000, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1060,
  'first name': 'Thangudu',
  'last name': 'Srinivasa Rao',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Chase Results',
  'goal description': 'will focus on making 3 to 6 months material zero over a benchmark of >6months Material zero.',
  'start date': datetime.datetime(2021, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2022, 3, 31, 0, 0),
  'creation date': datetime.datetime(2020, 10, 14, 9, 5, 58, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 107,
  'first name': 'Chirag P.',
  'last name': 'Thakar',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'grade': 'M3',
  'grade level': 'M3b',
  'region': 'Corporate',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Finance - Financial IT & Data Management',
  'goal description': 'End to End learning of the new system.',
  'start date': datetime.datetime(2020, 7, 1, 0, 0),
  'target completion date': datetime.datetime(2021, 1, 31, 0, 0),
  'creation date': datetime.datetime(2020, 10, 30, 11, 25, 15, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 107,
  'first name': 'Chirag P.',
  'last name': 'Thakar',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'grade': 'M3',
  'grade level': 'M3b',
  'region': 'Corporate',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Change with Agility',
  'goal description': 'Dash board on SOD prepared in Tableau using SAP dumps',
  'start date': datetime.datetime(2021, 12, 23, 0, 0),
  'target completion date': datetime.datetime(2022, 3, 31, 0, 0),
  'creation date': datetime.datetime(2022, 1, 10, 6, 48, 22, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1088,
  'first name': 'Arun',
  'last name': 'Dharampal',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5b',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor competency - put customer First',
  'goal description': 'reduced ETA IMA - < 0.5,',
  'start date': datetime.datetime(2024, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2025, 3, 31, 0, 0),
  'creation date': datetime.datetime(2020, 10, 8, 3, 48, 54, 736000, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1088,
  'first name': 'Arun',
  'last name': 'Dharampal',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5b',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Analyze',
  'goal description': 'Achieve binge pack - more then 15 %Achieve Recharge - More then 18%',
  'start date': datetime.datetime(2024, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2025, 3, 31, 0, 0),
  'creation date': datetime.datetime(2020, 10, 8, 3, 43, 19, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1107,
  'first name': 'Ravi Pratap',
  'last name': 'Singh',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Put Customer First',
  'goal description': 'completed NPS score > 92',
  'start date': datetime.datetime(2022, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2023, 3, 31, 0, 0),
  'creation date': datetime.datetime(2020, 10, 14, 13, 30, 7, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1107,
  'first name': 'Ravi Pratap',
  'last name': 'Singh',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Think Digital',
  'goal description': '100% QR capture in Installation by using mService',
  'start date': datetime.datetime(2023, 11, 3, 0, 0),
  'target completion date': datetime.datetime(2024, 3, 31, 0, 0),
  'creation date': datetime.datetime(2023, 11, 3, 13, 29, 55, 288000, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1130,
  'first name': 'Tanuja',
  'last name': 'S.',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'South',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Put Customer First',
  'goal description': 'NA',
  'start date': datetime.datetime(2022, 12, 1, 0, 0),
  'target completion date': datetime.datetime(2023, 12, 31, 0, 0),
  'creation date': datetime.datetime(2022, 12, 2, 14, 31, 56, 732000, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': '20% - Social learning',
  'manager approval date': None},
 {'employee code': 1130,
  'first name': 'Tanuja',
  'last name': 'S.',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'South',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Operations Excellence',
  'goal description': 'NA',
  'start date': datetime.datetime(2022, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2023, 12, 31, 0, 0),
  'creation date': datetime.datetime(2022, 12, 2, 14, 36, 16, 69000, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1130,
  'first name': 'Tanuja',
  'last name': 'S.',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'South',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Put Customer First',
  'goal description': 'Called subs. identified the painpoints and issues faced during their attempts, shared and co- ordinated with IT and Process owners in getting the needful changes implemented',
  'start date': datetime.datetime(2020, 5, 15, 0, 0),
  'target completion date': datetime.datetime(2021, 3, 31, 0, 0),
  'creation date': datetime.datetime(2020, 10, 15, 14, 5, 54, tzinfo=datetime.timezone.utc),
  'development goal status': 'COMPLETED',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1130,
  'first name': 'Tanuja',
  'last name': 'S.',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'South',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Customer Operations - Project Management & Deployment',
  'goal description': 'NA',
  'start date': datetime.datetime(2022, 10, 1, 0, 0),
  'target completion date': None,
  'creation date': datetime.datetime(2022, 12, 2, 15, 27, 34, 617000, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': 'NA',
  'manager approval date': None},
 {'employee code': 1182,
  'first name': 'Munesh',
  'last name': 'Singh Jamwal',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Put Customer First',
  'goal description': "In order to enhance fruitful results for better ROE of the Partner, below are the key steps follow to acheive the same.  1) Briefing with both ISP owner and staff on initative part and decide the targets to achieve  2) Follow SAKSHAM training for both service and sales module to acheive desired percentage  3) Daily follow up and publish report on acheivment twice a week  4) Appricate the teammate who acheived highest % every week so that others may also get motivate and start delivery the desired no's.  5) Will organise a small R&R at ISP level and award the best performance.",
  'start date': datetime.datetime(2020, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2022, 2, 28, 0, 0),
  'creation date': datetime.datetime(2021, 10, 8, 15, 4, 3, 797000, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1182,
  'first name': 'Munesh',
  'last name': 'Singh Jamwal',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Partner Well',
  'goal description': "In order to enhance fruitful results for better ROE of the Partner, below are the key steps follow to acheive the same.  1) Briefing with both ISP owner and staff on initative part and decide the targets to achieve  2) Follow SAKSHAM training for both service and sales module to acheive desired percentage  3) Daily follow up and publish report on acheivment twice a week  4) Appricate the teammate who acheived highest % every week so that others may also get motivate and start delivery the desired no's.  5) Will organise a small R&R at ISP level and award the best performance.",
  'start date': datetime.datetime(2020, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2021, 2, 28, 0, 0),
  'creation date': datetime.datetime(2020, 10, 15, 14, 40, 59, 989000, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1187,
  'first name': 'Tajinder Pal',
  'last name': 'Singh',
  'department': 'Technology',
  'sub department': 'Broadcast/OTT Engineering',
  'grade': 'M2',
  'grade level': 'M2a',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Chase Results',
  'goal description': 'Project need to be completed and deployed with agressive timelines with bringing local languages support to app. To be traget within 6 months effort.',
  'start date': datetime.datetime(2020, 11, 1, 0, 0),
  'target completion date': datetime.datetime(2021, 5, 1, 0, 0),
  'creation date': datetime.datetime(2020, 10, 26, 8, 47, 11, tzinfo=datetime.timezone.utc),
  'development goal status': 'NOT_STARTED',
  'category': 'NA',
  'manager approval date': None},
 {'employee code': 1192,
  'first name': 'Jaipal',
  'last name': 'Singh Bhandari',
  'department': 'Technology',
  'sub department': 'Consumer Technology',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Deliver Results',
  'goal description': 'HD Yield should be more than 60%  Android yield should be more than 70%',
  'start date': datetime.datetime(2022, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2023, 3, 31, 0, 0),
  'creation date': datetime.datetime(2022, 10, 12, 11, 22, 26, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '70% - On the Job learning',
  'manager approval date': None},
 {'employee code': 1192,
  'first name': 'Jaipal',
  'last name': 'Singh Bhandari',
  'department': 'Technology',
  'sub department': 'Consumer Technology',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Challenge Status Quo',
  'goal description': 'Zero failures of spares / mismatch of spares.',
  'start date': datetime.datetime(2020, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2021, 3, 31, 0, 0),
  'creation date': datetime.datetime(2020, 10, 13, 5, 18, 33, 173000, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '20% - Social learning',
  'manager approval date': None},
 {'employee code': 1192,
  'first name': 'Jaipal',
  'last name': 'Singh Bhandari',
  'department': 'Technology',
  'sub department': 'Consumer Technology',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Put Customer First',
  'goal description': 'Zero escalations from finance for uneven consumption posting.',
  'start date': datetime.datetime(2020, 10, 1, 0, 0),
  'target completion date': datetime.datetime(2020, 10, 30, 0, 0),
  'creation date': datetime.datetime(2020, 10, 13, 5, 15, 0, 557000, tzinfo=datetime.timezone.utc),
  'development goal status': 'IN_PROGRESS',
  'category': '10% - Formal learning',
  'manager approval date': None},
 {'employee code': 1192,
  'first name': 'Jaipal',
  'last name': 'Singh Bhandari',
  'department': 'Technology',
  'sub department': 'Consumer Technology',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'goal type': 'DEVELOPMENT',
  'goal name': 'Anchor Competency - Deliver Results',
  'goal description': 'Setting up new RC siteAchieving Yield as per KRA',

In [48]:
dst = db[collection]
result = dst.insert_many(normalized_docs)

## Ddata/Output1.xls
### Offboarding Checklist

In [77]:
path="Ddata/Output1.xls"
collection="offboarding_checklist2"
df = pd.read_excel(path, header=[0, 1])

In [78]:
for i in df.columns:
    print(i)

('Core HR', 'Employee ID')
('Core HR', 'Employee name')
('Core HR', 'Grade')
('Core HR', 'Grade Level')
('Core HR', 'Designation')
('Core HR', 'Department')
('Core HR', 'Sub Department')
('Core HR', 'Region')
('Core HR', 'Employee Status')
('Core HR', 'Reporting Manager')
('Core HR', 'Date of  Joining')
('Core HR', 'Date of Resignation')
('Core HR', 'Date of Leaving')
('Status', ' Exit Checklist - Employee')
('Status', 'Exit Checklist - Reporting Manager')
('Status', 'Exit Checklist - Customer Operations')
('Status', 'Exit Checklist - Facilities')
('Status', 'Exit Checklist - IT')
('Status', 'Exit Checklist - Finance Accounts')
('Status', 'Exit Checklist - Finance Assets')
('Status', 'Exit Checklist - RHR Ops')
('Status', 'Exit Checklist - Payroll')
('Status', 'Exit Checklist - RHR')
('Status', 'Exit Checklist - CHR Ops')
('Status', 'Exit Checklist - CHR')
('Status', 'All Task Status')
(' Exit Checklist - Employee', 'Pending Flexi pay Claims sent to payroll')
(' Exit Checklist - Employee', 'Proof of Investements sent to Payroll')
(' Exit Checklist - Employee', 'Travel claims raised and Manager has approved it in system')
(' Exit Checklist - Employee', 'Pending Hotel bills sent to Osource')
(' Exit Checklist - Employee', 'Personal Email ID/Address')
('Exit Checklist - Reporting Manager', 'Outstanding matters completed')
('Exit Checklist - Reporting Manager', 'Material Returned')
('Exit Checklist - Reporting Manager', 'Password and documents handed over')
('Exit Checklist - Reporting Manager', 'All expenses and Claims approved')
('Exit Checklist - Reporting Manager', 'Comments')
('Exit Checklist - Customer Operations', 'Employee Account Disabled')
('Exit Checklist - Facilities', 'Employee ID Card returned')
('Exit Checklist - Facilities', 'Access Card Returned')
('Exit Checklist - Facilities', 'Mention the Amount in case of recovery for Employee')
('Exit Checklist - Facilities', 'Stationary Returned')
('Exit Checklist - Facilities', 'Keys to workstation/locker returned')
('Exit Checklist - Facilities', 'Business card returned')
('Exit Checklist - Facilities', 'Corporate CC Returned')
('Exit Checklist - Facilities', 'COCP Recovery Amount (Mobile)')
('Exit Checklist - Facilities', 'COCP Recovery Amount (Broadband)')
('Exit Checklist - Facilities', 'Comments')
('Exit Checklist - IT', 'PC/Laptop Returned')
('Exit Checklist - IT', 'Amount of Recovery for PC/Laptop')
('Exit Checklist - IT', 'Cosummables/Accossories returned')
('Exit Checklist - IT', 'Amount of recovery for consumables/accessories')
('Exit Checklist - IT', 'Account Ids (login id.,email id.)/SIEBEL/SAP/ESS password disabled')
('Exit Checklist - IT', 'Temp Network folders deleted')
('Exit Checklist - IT', 'CRM(SSO)/PRM/Kenan/VMS/EVD/Victory/BO/SAP IDs Disabled')
('Exit Checklist - IT', 'NAS Folder Name with Access Details/Other disabled')
('Exit Checklist - IT', 'Comments')
('Exit Checklist - Finance Accounts', 'Outstanding Travel Advance/Imprest amount to be recovered')
('Exit Checklist - Finance Accounts', 'Outstanding relocation amount to be recovered')
('Exit Checklist - Finance Accounts', 'Travel claim bill received')
('Exit Checklist - Finance Accounts', 'Amount of recovery for Travel')
('Exit Checklist - Finance Accounts', 'Personal Expense')
('Exit Checklist - Finance Accounts', 'Comments')
('Exit Checklist - Finance Assets', 'Assets submitted by employee')
('Exit Checklist - Finance Assets', 'Amount to be recovered against asset')
('Exit Checklist - Finance Assets', 'Comments')
('Exit Checklist - RHR Ops', 'Notice Period Recovery')
('Exit Checklist - RHR Ops', 'Verified all checklist data submitted by respective department')
('Exit Checklist - RHR Ops', 'DD received Notice recovery')
('Exit Checklist - RHR Ops', 'Any leave without pay not applied in the system')
('Exit Checklist - RHR Ops', 'Recovery Amount (except -JB,NP,Relocation)')
('Exit Checklist - RHR Ops', 'Comments')
('Exit Checklist - RHR', 'Employee Status')
('Exit Checklist - RHR', 'Comments')
('Exit Checklist - CHR Ops', 'Amount of Training Cost to be recovered')
('Exit Checklist - CHR Ops', 'Notice Buy-Out Reimbursement Cost to be Recovered')
('Exit Checklist - CHR Ops', 'Joining Bonus to be recovered')
('Exit Checklist - CHR Ops', 'Annual Leave Balance (In days)')
('Exit Checklist - CHR Ops', 'Encashable Sick Leave Balance (In days)')
('Exit Checklist - CHR Ops', 'Encashable Casual Leave Balance (In days)')
('Exit Checklist - CHR Ops', 'Special Leave Deduction')
('Exit Checklist - CHR Ops', 'Group Transfer')
('Exit Checklist - CHR Ops', 'Group Compnay Name')
('Exit Checklist - CHR Ops', 'DoJ in Group Company')
('Exit Checklist - CHR Ops', 'Gratuity Processed from the Group Company, if any')
('Exit Checklist - CHR Ops', 'Tata Group DoJ (If different from date mentioned earlier)')
('Exit Checklist - CHR Ops', 'Name of the Point of Contact  of the new Group Company')
('Exit Checklist - CHR Ops', 'Designation of the POC')
('Exit Checklist - CHR Ops', 'Department of the POC')
('Exit Checklist - CHR Ops', 'Email ID of the POC')
('Exit Checklist - CHR Ops', 'Contact Number of the POC')
('Exit Checklist - CHR Ops', 'Annual Leave Transfer to new Group Company')
('Exit Checklist - CHR Ops', 'Number of days of leaves to be transferred')
('Exit Checklist - CHR', 'Comments')
('Exit Checklist - Payroll', 'Gratuity Eligibility')
('Exit Checklist - Payroll', 'Gratuity Payable')
('Exit Checklist - Payroll', 'TataPlay Subscription')
('Exit Checklist - Payroll', 'Performance linked Incentive (Sales Incentive)')
('Exit Checklist - Payroll', 'Performance Linked Incentive (Bonus)')
('Exit Checklist - Payroll', 'Any other payout (LTIP / Special allowance /other)')
('Exit Checklist - Payroll', 'Rewards')
('Exit Checklist - Payroll', 'Statutory Bonus')
('Exit Checklist - Payroll', 'Relocation reimbursement')
('Exit Checklist - Payroll', 'City Compensatory Allowance')
('Exit Checklist - Payroll', 'MIP Deduct/Refund')
('Exit Checklist - Payroll', 'MIP Top up Deduction/Refund')
('Exit Checklist - Payroll', 'NPS Recovery')
('Exit Checklist - Payroll', 'PF Recovery')

In [ ]:
FIELDS = {
    "Core HR": [
        "Employee ID",
        "Employee name",
        "Grade",
        "Grade Level",
        "Designation",
        "Department",
        "Sub Department",
        "Region",
        "Employee Status",
        "Reporting Manager",
        "Date of  Joining",
        "Date of Resignation",
        "Date of Leaving",
    ],

    "Status": [
        " Exit Checklist - Employee",
        "Exit Checklist - Reporting Manager",
        "Exit Checklist - Customer Operations",
        "Exit Checklist - Facilities",
        "Exit Checklist - IT",
        "Exit Checklist - Finance Accounts",
        "Exit Checklist - Finance Assets",
        "Exit Checklist - RHR Ops",
        "Exit Checklist - Payroll",
        "Exit Checklist - RHR",
        "Exit Checklist - CHR Ops",
        "Exit Checklist - CHR",
        "All Task Status",
    ],

    "Exit Checklist - Employee": [
        "Pending Flexi pay Claims sent to payroll",
        "Proof of Investements sent to Payroll",
        "Travel claims raised and Manager has approved it in system",
        "Pending Hotel bills sent to Osource",
        "Personal Email ID/Address",
    ],

    "Exit Checklist - Reporting Manager": [
        "Outstanding matters completed",
        "Material Returned",
        "Password and documents handed over",
        "All expenses and Claims approved",
        "Comments",
    ],

    "Exit Checklist - Customer Operations": [
        "Employee Account Disabled",
    ],

    "Exit Checklist - Facilities": [
        "Employee ID Card returned",
        "Access Card Returned",
        "Mention the Amount in case of recovery for Employee",
        "Stationary Returned",
        "Keys to workstation/locker returned",
        "Business card returned",
        "Corporate CC Returned",
        "COCP Recovery Amount (Mobile)",
        "COCP Recovery Amount (Broadband)",
        "Comments",
    ],

    "Exit Checklist - IT": [
        "PC/Laptop Returned",
        "Amount of Recovery for PC/Laptop",
        "Cosummables/Accossories returned",
        "Amount of recovery for consumables/accessories",
        "Account Ids (login id.,email id.)/SIEBEL/SAP/ESS password disabled",
        "Temp Network folders deleted",
        "CRM(SSO)/PRM/Kenan/VMS/EVD/Victory/BO/SAP IDs Disabled",
        "NAS Folder Name with Access Details/Other disabled",
        "Comments",
    ],

    "Exit Checklist - Finance Accounts": [
        "Outstanding Travel Advance/Imprest amount to be recovered",
        "Outstanding relocation amount to be recovered",
        "Travel claim bill received",
        "Amount of recovery for Travel",
        "Personal Expense",
        "Comments",
    ],

    "Exit Checklist - Finance Assets": [
        "Assets submitted by employee",
        "Amount to be recovered against asset",
        "Comments",
    ],

    "Exit Checklist - RHR Ops": [
        "Notice Period Recovery",
        "Verified all checklist data submitted by respective department",
        "DD received Notice recovery",
        "Any leave without pay not applied in the system",
        "Recovery Amount (except -JB,NP,Relocation)",
        "Comments",
    ],

    "Exit Checklist - RHR": [
        "Employee Status",
        "Comments",
    ],

    "Exit Checklist - CHR Ops": [
        "Amount of Training Cost to be recovered",
        "Notice Buy-Out Reimbursement Cost to be Recovered",
        "Joining Bonus to be recovered",
        "Annual Leave Balance (In days)",
        "Encashable Sick Leave Balance (In days)",
        "Encashable Casual Leave Balance (In days)",
        "Special Leave Deduction",
        "Group Transfer",
        "Group Compnay Name",
        "DoJ in Group Company",
        "Gratuity Processed from the Group Company, if any",
        "Tata Group DoJ (If different from date mentioned earlier)",
        "Name of the Point of Contact  of the new Group Company",
        "Designation of the POC",
        "Department of the POC",
        "Email ID of the POC",
        "Contact Number of the POC",
        "Annual Leave Transfer to new Group Company",
        "Number of days of leaves to be transferred",
    ],

    "Exit Checklist - CHR": [
        "Comments",
    ],

    "Exit Checklist - Payroll": [
        "Gratuity Eligibility",
        "Gratuity Payable",
        "TataPlay Subscription",
        "Performance linked Incentive (Sales Incentive)",
        "Performance Linked Incentive (Bonus)",
        "Any other payout (LTIP / Special allowance /other)",
        "Rewards",
        "Statutory Bonus",
        "Relocation reimbursement",
        "City Compensatory Allowance",
        "MIP Deduct/Refund",
        "MIP Top up Deduction/Refund",
        "NPS Recovery",
        "PF Recovery",
    ]
}


KEY_RENAMES = {

    "Core HR": {
        "Employee ID": "employee code",
        "Employee name": "employee name",
        "Grade": "grade",
        "Grade Level": "grade level",
        "Designation": "designation",
        "Department": "department",
        "Sub Department": "sub department",
        "Region": "region",
        "Employee Status": "employee status",
        "Reporting Manager": "manager name",
        "Date of  Joining": "date of joining",
        "Date of Resignation": "date of resignation",
        "Date of Leaving": "date of leaving",
    },

    "Status": {
        " Exit Checklist - Employee": "exit checklist employee",
        "Exit Checklist - Reporting Manager": "exit checklist reporting manager",
        "Exit Checklist - Customer Operations": "exit checklist customer operations",
        "Exit Checklist - Facilities": "exit checklist facilities",
        "Exit Checklist - IT": "exit checklist it",
        "Exit Checklist - Finance Accounts": "exit checklist finance accounts",
        "Exit Checklist - Finance Assets": "exit checklist finance assets",
        "Exit Checklist - RHR Ops": "exit checklist rhr ops",
        "Exit Checklist - Payroll": "exit checklist payroll",
        "Exit Checklist - RHR": "exit checklist rhr",
        "Exit Checklist - CHR Ops": "exit checklist chr ops",
        "Exit Checklist - CHR": "exit checklist chr",
        "All Task Status": "all task status",
    },

    "Exit Checklist - Employee": {
        "Pending Flexi pay Claims sent to payroll": "pending flexi pay claims sent to payroll",
        "Proof of Investements sent to Payroll": "proof of investments sent to payroll",
        "Travel claims raised and Manager has approved it in system": "travel claims approved by manager",
        "Pending Hotel bills sent to Osource": "pending hotel bills sent to osource",
        "Personal Email ID/Address": "personal email",
    },

    "Exit Checklist - Reporting Manager": {
        "Outstanding matters completed": "outstanding matters completed",
        "Material Returned": "material returned",
        "Password and documents handed over": "password and documents handed over",
        "All expenses and Claims approved": "all expenses and claims approved",
        "Comments": "comments",
    },

    "Exit Checklist - Customer Operations": {
        "Employee Account Disabled": "employee account disabled",
    },

    "Exit Checklist - Facilities": {
        "Employee ID Card returned": "employee id card returned",
        "Access Card Returned": "access card returned",
        "Mention the Amount in case of recovery for Employee": "recovery amount employee",
        "Stationary Returned": "stationary returned",
        "Keys to workstation/locker returned": "keys workstation/locker returned",
        "Business card returned": "business card returned",
        "Corporate CC Returned": "corporate cc returned",
        "COCP Recovery Amount (Mobile)": "cocp recovery amount mobile",
        "COCP Recovery Amount (Broadband)": "cocp recovery amount broadband",
        "Comments": "comments",
    },

    "Exit Checklist - IT": {
        "PC/Laptop Returned": "pc/laptop returned",
        "Amount of Recovery for PC/Laptop": "amount recovery pc/laptop",
        "Cosummables/Accossories returned": "consumables accessories returned",
        "Amount of recovery for consumables/accessories": "amount recovery consumables/accessories",
        "Account Ids (login id.,email id.)/SIEBEL/SAP/ESS password disabled": "account ids (login id.,email id.)/siebel/sap/ess password disabled",
        "Temp Network folders deleted": "temp network folders deleted",
        "CRM(SSO)/PRM/Kenan/VMS/EVD/Victory/BO/SAP IDs Disabled": "crm(sso)/prm/kenan/vms/evd/victory/bo/sap ids disabled",
        "NAS Folder Name with Access Details/Other disabled": "nas folder access disabled",
        "Comments": "comments",
    },

    "Exit Checklist - Finance Accounts": {
        "Outstanding Travel Advance/Imprest amount to be recovered": "outstanding travel advance/imprest recovered",
        "Outstanding relocation amount to be recovered": "outstanding relocation amount recovered",
        "Travel claim bill received": "travel claim bill received",
        "Amount of recovery for Travel": "amount recovery travel",
        "Personal Expense": "personal expense",
        "Comments": "comments",
    },

    "Exit Checklist - Finance Assets": {
        "Assets submitted by employee": "assets submitted employee",
        "Amount to be recovered against asset": "amount to be recovered against asset",
        "Comments": "comments",
    },

    "Exit Checklist - RHR Ops": {
        "Notice Period Recovery": "notice period recovery",
        "Verified all checklist data submitted by respective department": "verified all checklist data submitted by respective department",
        "DD received Notice recovery": "dd received notice recovery",
        "Any leave without pay not applied in the system": "any leave without pay not applied in the system",
        "Recovery Amount (except -JB,NP,Relocation)": "recovery amount general except jb np relocation",
        "Comments": "comments",
    },

    "Exit Checklist - RHR": {
        "Employee Status": "employee status",
        "Comments": "comments",
    },

    "Exit Checklist - CHR Ops": {
        "Amount of Training Cost to be recovered": "training cost recovered",
        "Notice Buy-Out Reimbursement Cost to be Recovered": "notice buyout reimbursement recovered",
        "Joining Bonus to be recovered": "joining bonus recovered",
        "Annual Leave Balance (In days)": "annual leave balance days",
        "Encashable Sick Leave Balance (In days)": "sick leave balance encashable in days",
        "Encashable Casual Leave Balance (In days)": "casual leave balance encashable in days",
        "Special Leave Deduction": "special leave deduction",
        "Group Transfer": "group transfer",
        "Group Compnay Name": "group company name",
        "DoJ in Group Company": "date of joining group company",
        "Gratuity Processed from the Group Company, if any": "gratuity processed group company",
        "Tata Group DoJ (If different from date mentioned earlier)": "tata group date of joining",
        "Name of the Point of Contact  of the new Group Company": "poc name group company",
        "Designation of the POC": "poc designation",
        "Department of the POC": "poc department",
        "Email ID of the POC": "poc email",
        "Contact Number of the POC": "poc contact number",
        "Annual Leave Transfer to new Group Company": "annual leave transfer group company",
        "Number of days of leaves to be transferred": "leave transfer days",
    },

    "Exit Checklist - CHR": {
        "Comments": "comments",
    },

    "Exit Checklist - Payroll": {
        "Gratuity Eligibility": "gratuity eligibility",
        "Gratuity Payable": "gratuity payable",
        "TataPlay Subscription": "tataplay subscription",
        "Performance linked Incentive (Sales Incentive)": "performance linked incentive sales incentive",
        "Performance Linked Incentive (Bonus)": "performance linked incentive bonus incentive",
        "Any other payout (LTIP / Special allowance /other)": "other payout",
        "Rewards": "rewards",
        "Statutory Bonus": "statutory bonus",
        "Relocation reimbursement": "relocation reimbursement",
        "City Compensatory Allowance": "city compensatory allowance",
        "MIP Deduct/Refund": "mip deduct/refund",
        "MIP Top up Deduction/Refund": "mip topup deduct/refund",
        "NPS Recovery": "nps recovery",
        "PF Recovery": "pf recovery",
    }
}



NUMERIC_FIELDS = {
    "Core HR": ["employee code"],
    "Exit Checklist - Facilities": [
        "cocp recovery amount mobile",
        "cocp recovery amount broadband"
    ],
    "Exit Checklist - IT": [
        "amount recovery pc/laptop",
        "amount recovery consumables/accessories"
    ],
    "Exit Checklist - Finance Accounts": [
        "outstanding travel advance/imprest recovered",
        "outstanding relocation amount recovered",
        "amount recovery travel",
        "personal expense"
    ],
    "Exit Checklist - Finance Assets": [
        "amount to be recovered against asset"
    ],
    "Exit Checklist - RHR Ops": [
        "dd received notice recovery",
        "Recovery Amount (except -JB,NP,Relocation)"
    ],
    "Exit Checklist - CHR Ops": [
        "annual leave balance days",
        "sick leave balance encashable in days",
        "casual leave balance encashable in days",
        "leave transfer days"
    ],
    "Exit Checklist - Payroll": [
        "gratuity payable",
        "tataplay subscription",
        "performance linked incentive sales incentive",
        "performance linked incentive bonus incentive",
        "other payout",
        "rewards",
        "statutory bonus",
        "relocation reimbursement",
        "city compensatory allowance",
        "mip deduct/refund",
        "mip topup deduct/refund",
        "nps recovery",
        "pf recovery",
    ]
}

DATE_FIELDS = {
    "Core HR": [
        "date of joining",
        "date of resignation",
        "date of leaving"
    ],
    "Exit Checklist - CHR Ops": [
        "date of joining group company",
        "tata group date of joining"
    ]
}

In [80]:
def normalize_nested_row(row, fields, key_renames, numeric_fields, date_fields):
    """
    row: pandas Series where row[key] is accessed with multi-level keys
         e.g., row["Core HR"]["Grade"]
    fields: dict of section → list of fields
    key_renames: dict of section → dict of old→new names
    numeric_fields: dict of section → set of numeric field names
    date_fields: dict of section → set of date field names
    """

    cleaned_sections = {}

    for section, field_list in fields.items():
        section_cleaned = {}

        for field in field_list:
            raw_value = None

            # Retrieve nested value if section exists
            try:
                raw_value = row[(section, field)]
            except Exception:
                raw_value = None

            # Rename field inside the section
            new_field = key_renames.get(section, {}).get(field, field)

            # Determine numeric/date membership
            section_numeric = numeric_fields.get(section, set())
            section_dates = date_fields.get(section, set())

            # Build a fake 1D raw_doc to reuse normalize_doc_generic
            fake_raw = {field: raw_value}

            cleaned_value = normalize_doc_generic(
                fake_raw,
                fields=[field],
                key_renames={field: new_field},
                numeric_fields=section_numeric,
                date_fields=section_dates
            )[new_field]

            section_cleaned[new_field] = cleaned_value

        cleaned_sections[section] = section_cleaned

    return cleaned_sections

In [81]:
# Ensure pandas sees missing values as None
df = df.where(df.notna(), None)

normalized_docs = []

for _, row in df.iterrows():
    nested_cleaned = normalize_nested_row(
        row=row,
        fields=FIELDS,
        key_renames=KEY_RENAMES,
        numeric_fields=NUMERIC_FIELDS,
        date_fields=DATE_FIELDS
    )
    normalized_docs.append(nested_cleaned)

In [82]:
normalized_docs

[{'Core HR': {'employee code': 2220,
   'employee name': 'Anshul Kapoor',
   'grade': 'M3',
   'grade level': 'M3b',
   'designation': 'Assistant General Manager - Facilities',
   'department': 'Facilities',
   'sub department': 'Facilities - General',
   'region': 'North',
   'employee status': 'Active',
   'manager name': 'Chanmeet Singh',
   'date of joining': datetime.datetime(2007, 1, 2, 0, 0),
   'date of resignation': datetime.datetime(2025, 8, 4, 0, 0),
   'date of leaving': datetime.datetime(2025, 11, 3, 0, 0)},
  'Status': {'exit checklist employee': 'Pending',
   'exit checklist reporting manager': 'Pending',
   'exit checklist customer operations': 'Pending',
   'exit checklist facilities': 'Pending',
   'exit checklist it': 'Pending',
   'exit checklist finance accounts': 'Pending',
   'exit checklist finance assets': 'Pending',
   'exit checklist rhr ops': 'Pending',
   'exit checklist payroll': 'Pending',
   'exit checklist rhr': 'Pending',
   'exit checklist chr ops': 'Pending',
   'exit checklist chr': 'Pending',
   'all task status': 'Pending'},
  'Exit Checklist - Employee': {'pending flexi pay claims sent to payroll': 'NA',
   'proof of investments sent to payroll': 'NA',
   'travel claims approved by manager': 'NA',
   'pending hotel bills sent to osource': 'NA',
   'personal email': 'NA'},
  'Exit Checklist - Reporting Manager': {'outstanding matters completed': 'NA',
   'material returned': 'NA',
   'password and documents handed over': 'NA',
   'all expenses and claims approved': 'NA',
   'comments': 'NA'},
  'Exit Checklist - Customer Operations': {'employee account disabled': 'NA'},
  'Exit Checklist - Facilities': {'employee id card returned': 'NA',
   'access card returned': 'NA',
   'recovery amount employee': 'nan',
   'stationary returned': 'NA',
   'keys workstation/locker returned': 'NA',
   'business card returned': 'NA',
   'corporate cc returned': 'NA',
   'cocp recovery amount mobile': None,
   'cocp recovery amount broadband': None,
   'comments': 'NA'},
  'Exit Checklist - IT': {'pc/laptop returned': 'NA',
   'amount recovery pc/laptop': None,
   'consumables accessories returned': 'NA',
   'amount recovery consumables/accessories': None,
   'account ids (login id.,email id.)/siebel/sap/ess password disabled': 'NA',
   'temp network folders deleted': 'NA',
   'crm(sso)/prm/kenan/vms/evd/victory/bo/sap ids disabled': 'NA',
   'nas folder access disabled': 'NA',
   'comments': 'NA'},
  'Exit Checklist - Finance Accounts': {'outstanding travel advance/imprest recovered': None,
   'outstanding relocation amount recovered': None,
   'travel claim bill received': 'NA',
   'amount recovery travel': None,
   'personal expense': None,
   'comments': 'nan'},
  'Exit Checklist - Finance Assets': {'assets submitted employee': 'NA',
   'amount to be recovered against asset': None,
   'comments': 'NA'},
  'Exit Checklist - RHR Ops': {'notice period recovery': 'NA',
   'verified all checklist data submitted by respective department': 'NA',
   'dd received notice recovery': None,
   'any leave without pay not applied in the system': 'NA',
   'recovery amount general except jb np relocation': 'nan',
   'comments': 'NA'},
  'Exit Checklist - RHR': {'employee status': 'NA', 'comments': 'NA'},
  'Exit Checklist - CHR Ops': {'training cost recovered': 'NA',
   'notice buyout reimbursement recovered': 'NA',
   'joining bonus recovered': 'NA',
   'annual leave balance days': None,
   'sick leave balance encashable in days': None,
   'casual leave balance encashable in days': None,
   'special leave deduction': 'NA',
   'group transfer': 'NA',
   'group company name': 'nan',
   'date of joining group company': None,
   'gratuity processed group company': 'nan',
   'tata group date of joining': None,
   'poc name group company': 'nan',
   'poc designation': 'nan',
   'poc department': 'nan',
   'poc email': 'nan',
   'poc contact number': 'nan',
   'annual leave transfer group company': 'nan',
   'leave transfer days': None},
  'Exit Checklist - CHR': {'comments': 'NA'},
  'Exit Checklist - Payroll': {'gratuity eligibility': 'NA',
   'gratuity payable': None,
   'tataplay subscription': None,
   'performance linked incentive sales incentive': None,
   'performance linked incentive bonus incentive': None,
   'other payout': None,
   'rewards': None,
   'statutory bonus': None,
   'relocation reimbursement': None,
   'city compensatory allowance': None,
   'mip deduct/refund': None,
   'mip topup deduct/refund': None,
   'nps recovery': None,
   'pf recovery': None}},
 {'Core HR': {'employee code': 245,
   'employee name': 'Donthamsetti Venkata Subbarao',
   'grade': 'M4',
   'grade level': 'M4a',
   'designation': 'Senior Manager - Service Training',
   'department': 'Field Service Delivery',
   'sub department': 'Service Training - FSD',
   'region': 'South',
   'employee status': 'Inactive',
   'manager name': 'NA',
   'date of joining': datetime.datetime(2005, 12, 19, 0, 0),
   'date of resignation': datetime.datetime(2025, 6, 18, 0, 0),
   'date of leaving': datetime.datetime(2025, 6, 30, 0, 0)},
  'Status': {'exit checklist employee': 'Completed',
   'exit checklist reporting manager': 'Completed',
   'exit checklist customer operations': 'Completed',
   'exit checklist facilities': 'Completed',
   'exit checklist it': 'Completed',
   'exit checklist finance accounts': 'Completed',
   'exit checklist finance assets': 'Completed',
   'exit checklist rhr ops': 'Completed',
   'exit checklist payroll': 'Completed',
   'exit checklist rhr': 'Completed',
   'exit checklist chr ops': 'Completed',
   'exit checklist chr': 'Completed',
   'all task status': 'Completed'},
  'Exit Checklist - Employee': {'pending flexi pay claims sent to payroll': 'NA',
   'proof of investments sent to payroll': 'NA',
   'travel claims approved by manager': 'NA',
   'pending hotel bills sent to osource': 'NA',
   'personal email': 'NA'},
  'Exit Checklist - Reporting Manager': {'outstanding matters completed': 'Yes',
   'material returned': 'Yes',
   'password and documents handed over': 'Yes',
   'all expenses and claims approved': 'Yes',
   'comments': 'Laptop and ID Card Handed over to IT'},
  'Exit Checklist - Customer Operations': {'employee account disabled': 'Not Applicable'},
  'Exit Checklist - Facilities': {'employee id card returned': 'Yes',
   'access card returned': 'Not Applicable',
   'recovery amount employee': '0.0',
   'stationary returned': 'Not Applicable',
   'keys workstation/locker returned': 'Not Applicable',
   'business card returned': 'No',
   'corporate cc returned': 'Not Applicable',
   'cocp recovery amount mobile': 0,
   'cocp recovery amount broadband': 0,
   'comments': 'NA'},
  'Exit Checklist - IT': {'pc/laptop returned': 'Yes',
   'amount recovery pc/laptop': 0,
   'consumables accessories returned': 'Yes',
   'amount recovery consumables/accessories': 0,
   'account ids (login id.,email id.)/siebel/sap/ess password disabled': 'Yes',
   'temp network folders deleted': 'Yes',
   'crm(sso)/prm/kenan/vms/evd/victory/bo/sap ids disabled': 'Yes',
   'nas folder access disabled': 'Yes',
   'comments': 'User has submitted the laptop and the laptop is in good condition.'},
  'Exit Checklist - Finance Accounts': {'outstanding travel advance/imprest recovered': 10000,
   'outstanding relocation amount recovered': 0,
   'travel claim bill received': 'Not Applicable',
   'amount recovery travel': 0,
   'personal expense': 0,
   'comments': 'nan'},
  'Exit Checklist - Finance Assets': {'assets submitted employee': 'Not Applicable',
   'amount to be recovered against asset': 0,
   'comments': 'NIL'},
  'Exit Checklist - RHR Ops': {'notice period recovery': 'No',
   'verified all checklist data submitted by respective department': 'Yes',
   'dd received notice recovery': 0,
   'any leave without pay not applied in the system': 'NA',
   'recovery amount general except jb np relocation': 'nan',
   'comments': 'Retirement employee'},
  'Exit Checklist - RHR': {'employee status': 'Retirement',
   'comments': 'there is a finance related recovery, which the finance checklist will highlight.'},
  'Exit Checklist - CHR Ops': {'training cost recovered': '0',
   'notice buyout reimbursement recovered': '0',
   'joining bonus recovered': '0',
   'annual leave balance days': 42,
   'sick leave balance encashable in days': 0,
   'casual leave balance encashable in days': 0,
   'special leave deduction': '0',
   'group transfer': 'Not Applicable',
   'group company name': 'nan',
   'date of joining group company': None,
   'gratuity processed group company': 'nan',
   'tata group date of joining': None,
   'poc name group company': 'nan',
   'poc designation': 'nan',
   'poc department': 'nan',
   'poc email': 'nan',
   'poc contact number': 'nan',
   'annual leave transfer group company': 'nan',
   'leave transfer days': None},
  'Exit Checklist - CHR': {'comments': 'Good to go'},
  'Exit Checklist - Payroll': {'gratuity eligibility': 'Yes',
   'gratuity payable': 677019,
   'tataplay subscription': 0,
   'performance linked incentive sales incentive': 0,
   'performance linked incentive bonus incentive': 0,
   'other payout': 0,
   'rewards': 0,
   'statutory bonus': 0,
   'relocation reimbursement': 0,
   'city compensatory allowance': 0,
   'mip deduct/refund': 1256,
   'mip topup deduct/refund': 0,
   'nps recovery': 0,
   'pf recovery': 0}},
 {'Core HR': {'employee code': 3893,
   'employee name': 'Amit Paralkar',
   'grade': 'M3',
   'grade level': 'M3a',
   'designation': 'General Manager – Corporate and Direct Sales',
   'department': 'Sales',
   'sub department': 'Corporate Sales',
   'region': 'North',
   'employee status': 'Inactive',
   'manager name': 'NA',
   'date of joining': datetime.datetime(2013, 3, 4, 0, 0),
   'date of resignation': datetime.datetime(2025, 9, 1, 0, 0),
   'date of leaving': datetime.datetime(2025, 9, 1, 0, 0)},
  'Status': {'exit checklist employee': 'Completed',
   'exit checklist reporting manager': 'Completed',
   'exit checklist customer operations': 'Completed',
   'exit checklist facilities': 'Completed',
   'exit checklist it': 'Completed',
   'exit checklist finance accounts': 'Completed',
   'exit checklist finance assets': 'Completed',
   'exit checklist rhr ops': 'Completed',
   'exit checklist payroll': 'Pending',
   'exit checklist rhr': 'Completed',
   'exit checklist chr ops': 'Pending',
   'exit checklist chr': 'Pending',
   'all task status': 'Pending'},
  'Exit Checklist - Employee': {'pending flexi pay claims sent to payroll': 'NA',
   'proof of investments sent to payroll': 'NA',
   'travel claims approved by manager': 'NA',
   'pending hotel bills sent to osource': 'NA',
   'personal email': 'NA'},
  'Exit Checklist - Reporting Manager': {'outstanding matters completed': 'Yes',
   'material returned': 'Yes',
   'password and documents handed over': 'Yes',
   'all expenses and claims approved': 'Yes',
   'comments': 'Late travel expense were submitted, to be considered basis policy guidelines.'},
  'Exit Checklist - Customer Operations': {'employee account disabled': 'Not Applicable'},
  'Exit Checklist - Facilities': {'employee id card returned': 'Yes',
   'access card returned': 'Yes',
   'recovery amount employee': '0.0',
   'stationary returned': 'Yes',
   'keys workstation/locker returned': 'Yes',
   'business card returned': 'Not Applicable',
   'corporate cc returned': 'Not Applicable',
   'cocp recovery amount mobile': 0,
   'cocp recovery amount broadband': 0,
   'comments': 'NA'},
  'Exit Checklist - IT': {'pc/laptop returned': 'Yes',
   'amount recovery pc/laptop': 0,
   'consumables accessories returned': 'Yes',
   'amount recovery consumables/accessories': 0,
   'account ids (login id.,email id.)/siebel/sap/ess password disabled': 'Yes',
   'temp network folders deleted': 'Yes',
   'crm(sso)/prm/kenan/vms/evd/victory/bo/sap ids disabled': 'Yes',
   'nas folder access disabled': 'Yes',
   'comments': 'User has submitted the laptop and the laptop is in good condition.'},
  'Exit Checklist - Finance Accounts': {'outstanding travel advance/imprest recovered': 0,
   'outstanding relocation amount recovered': 0,
   'travel claim bill received': 'Not Applicable',
   'amount recovery travel': 0,
   'personal expense': 0,
   'comments': 'nan'},
  'Exit Checklist - Finance Assets': {'assets submitted employee': 'Not Applicable',
   'amount to be recovered against asset': 0,
   'comments': 'NIL'},
  'Exit Checklist - RHR Ops': {'notice period recovery': 'No',
   'verified all checklist data submitted by respective department': 'Yes',
   'dd received notice recovery': 0,
   'any leave without pay not applied in the system': '0',
   'recovery amount general except jb np relocation': '0.0',
   'comments': 'No recovery. All dept okay.'},
  'Exit Checklist - RHR': {'employee status': 'Confirmed',
   'comments': 'Full and Final to be processed .  Notice Period Deduction to be waived off  Regards  Atul Singh'},
  'Exit Checklist - CHR Ops': {'training cost recovered': 'NA',
   'notice buyout reimbursement recovered': 'NA',
   'joining bonus recovered': 'NA',
   'annual leave balance days': None,
   'sick leave balance encashable in days': None,
   'casual leave balance encashable in days': None,
   'special leave deduction': 'NA',
   'group transfer': 'NA',
   'group company name': 'nan',
   'date of joining group company': None,
   'gratuity processed group company': 'nan',
   'tata group date of joining': None,
   'poc name group company': 'nan',
   'poc designation': 'nan',
   'poc department': 'nan',
   'poc email': 'nan',
   'poc contact number': 'nan',
   'annual leave transfer group company': 'nan',
   'leave transfer days': None},
  'Exit Checklist - CHR': {'comments': 'NA'},
  'Exit Checklist - Payroll': {'gratuity eligibility': 'NA',
   'gratuity payable': None,
   'tataplay subscription': None,
   'performance linked incentive sales incentive': None,
   'performance linked incentive bonus incentive': None,
   'other payout': None,
   'rewards': None,
   'statutory bonus': None,
   'relocation reimbursement': None,
   'city compensatory allowance': None,
   'mip deduct/refund': None,
   'mip topup deduct/refund': None,
   'nps recovery': None,
   'pf recovery': None}},
 {'Core HR': {'employee code': 3558,
   'employee name': 'Seshadri Manivannan',
   'grade': 'M2',
   'grade level': 'M2a',
   'designation': 'Senior Vice President - Head IT Architecture',
   'department': 'IT',
   'sub department': 'IT Architecture',
   'region': 'South',
   'employee status': 'Active',
   'manager name': 'Vijay Sharma',
   'date of joining': datetime.datetime(2012, 5, 28, 0, 0),
   'date of resignation': datetime.datetime(2025, 7, 23, 0, 0),
   'date of leaving': datetime.datetime(2025, 10, 6, 0, 0)},
  'Status': {'exit checklist employee': 'Pending',
   'exit checklist reporting manager': 'Pending',
   'exit checklist customer operations': 'Pending',
   'exit checklist facilities': 'Pending',
   'exit checklist it': 'Pending',
   'exit checklist finance accounts': 'Pending',
   'exit checklist finance assets': 'Pending',
   'exit checklist rhr ops': 'Pending',
   'exit checklist payroll': 'Pending',
   'exit checklist rhr': 'Pending',
   'exit checklist chr ops': 'Pending',
   'exit checklist chr': 'Pending',
   'all task status': 'Pending'},
  'Exit Checklist - Employee': {'pending flexi pay claims sent to payroll': 'NA',
   'proof of investments sent to payroll': 'NA',
   'travel claims approved by manager': 'NA',
   'pending hotel bills sent to osource': 'NA',
   'personal email': 'NA'},
  'Exit Checklist - Reporting Manager': {'outstanding matters completed': 'NA',
   'material returned': 'NA',
   'password and documents handed over': 'NA',
   'all expenses and claims approved': 'NA',
   'comments': 'NA'},
  'Exit Checklist - Customer Operations': {'employee account disabled': 'NA'},
  'Exit Checklist - Facilities': {'employee id card returned': 'NA',
   'access card returned': 'NA',
   'recovery amount employee': 'nan',
   'stationary returned': 'NA',
   'keys workstation/locker returned': 'NA',
   'business card returned': 'NA',
   'corporate cc returned': 'NA',
   'cocp recovery amount mobile': None,
   'cocp recovery amount broadband': None,
   'comments': 'NA'},
  'Exit Checklist - IT': {'pc/laptop returned': 'NA',
   'amount recovery pc/laptop': None,
   'consumables accessories returned': 'NA',
   'amount recovery consumables/accessories': None,
   'account ids (login id.,email id.)/siebel/sap/ess password disabled': 'NA',
   'temp network folders deleted': 'NA',
   'crm(sso)/prm/kenan/vms/evd/victory/bo/sap ids disabled': 'NA',
   'nas folder access disabled': 'NA',
   'comments': 'NA'},
  'Exit Checklist - Finance Accounts': {'outstanding travel advance/imprest recovered': None,
   'outstanding relocation amount recovered': None,
   'travel claim bill received': 'NA',
   'amount recovery travel': None,
   'personal expense': None,
   'comments': 'nan'},
  'Exit Checklist - Finance Assets': {'assets submitted employee': 'NA',
   'amount to be recovered against asset': None,
   'comments': 'NA'},
  'Exit Checklist - RHR Ops': {'notice period recovery': 'NA',
   'verified all checklist data submitted by respective department': 'NA',
   'dd received notice recovery': None,
   'any leave without pay not applied in the system': 'NA',
   'recovery amount general except jb np relocation': 'nan',
   'comments': 'NA'},
  'Exit Checklist - RHR': {'employee status': 'NA', 'comments': 'NA'},
  'Exit Checklist - CHR Ops': {'training cost recovered': 'NA',
   'notice buyout reimbursement recovered': 'NA',
   'joining bonus recovered': 'NA',
   'annual leave balance days': None,
   'sick leave balance encashable in days': None,
   'casual leave balance encashable in days': None,
   'special leave deduction': 'NA',
   'group transfer': 'NA',
   'group company name': 'nan',
   'date of joining group company': None,
   'gratuity processed group company': 'nan',
   'tata group date of joining': None,
   'poc name group company': 'nan',
   'poc designation': 'nan',
   'poc department': 'nan',
   'poc email': 'nan',
   'poc contact number': 'nan',
   'annual leave transfer group company': 'nan',
   'leave transfer days': None},
  'Exit Checklist - CHR': {'comments': 'NA'},
  'Exit Checklist - Payroll': {'gratuity eligibility': 'NA',
   'gratuity payable': None,
   'tataplay subscription': None,
   'performance linked incentive sales incentive': None,
   'performance linked incentive bonus incentive': None,
   'other payout': None,
   'rewards': None,
   'statutory bonus': None,
   'relocation reimbursement': None,
   'city compensatory allowance': None,
   'mip deduct/refund': None,
   'mip topup deduct/refund': None,
   'nps recovery': None,
   'pf recovery': None}},
 {'Core HR': {'employee code': 1361,
   'employee name': 'Ashok Kumar M.K.',
   'grade': 'M4',
   'grade level': 'M4b',
   'designation': 'Manager - Field Service Delivery',
   'department': 'Field Service Delivery',
   'sub department': 'Field Service Delivery - General',
   'region': 'South',
   'employee status': 'Inactive',
   'manager name': 'NA',
   'date of joining': datetime.datetime(2006, 5, 8, 0, 0),
   'date of resignation': datetime.datetime(2025, 6, 9, 0, 0),
   'date of leaving': datetime.datetime(2025, 6, 13, 0, 0)},
  'Status': {'exit checklist employee': 'Completed',
   'exit checklist reporting manager': 'Completed',
   'exit checklist customer operations': 'Completed',
   'exit checklist facilities': 'Completed',
   'exit checklist it': 'Completed',
   'exit checklist finance accounts': 'Completed',
   'exit checklist finance assets': 'Completed',
   'exit checklist rhr ops': 'Completed',
   'exit checklist payroll': 'Completed',
   'exit checklist rhr': 'Completed',
   'exit checklist chr ops': 'Completed',
   'exit checklist chr': 'Completed',
   'all task status': 'Completed'},

In [71]:
df.head

<bound method NDFrame.head of        Core HR                                                   \
   Employee ID                  Employee name Grade Grade Level
0         2220                  Anshul Kapoor    M3         M3b
1          245  Donthamsetti Venkata Subbarao    M4         M4a
2         3893                  Amit Paralkar    M3         M3a
3         3558            Seshadri Manivannan    M2         M2a
4         1361               Ashok Kumar M.K.    M4         M4b
..         ...                            ...   ...         ...
72        7966                  Somesh Sharma    M4         M4b
73        7987                Swapnil Bhosale    M3         M3a
74        7989                    Vimal Kumar    M4         M4b
75        8000             Harshvardhan Verma    M5         M5a
76        8035                 Keshav Kaushik    M5         M5a

                                                                          \
                                     Designation              Department
0         Assistant General Manager - Facilities              Facilities
1              Senior Manager - Service Training  Field Service Delivery
2   General Manager – Corporate and Direct Sales                   Sales
3   Senior Vice President - Head IT Architecture                      IT
4               Manager - Field Service Delivery  Field Service Delivery
..                                           ...                     ...
72                         Manager - Trade Sales                   Sales
73        General Manager - Subscriber Analytics              Commercial
74                        Manager - Direct Sales                   Sales
75              Assistant Manager - Direct Sales                   Sales
76                             Executive Trainee                   Sales

                                                                 \
                      Sub Department     Region Employee Status
0               Facilities - General      North          Active
1             Service Training - FSD      South        Inactive
2                    Corporate Sales      North        Inactive
3                    IT Architecture      South          Active
4   Field Service Delivery - General      South        Inactive
..                               ...        ...             ...
72                       Trade Sales       West        Inactive
73              Subscriber Analytics  Corporate        Inactive
74                      Direct Sales      North        Inactive
75                      Direct Sales       East        Inactive
76                   Sales - General      North        Inactive

                      ...             Exit Checklist - Payroll  \
   Reporting Manager  ... Performance Linked Incentive (Bonus)
0     Chanmeet Singh  ...                                  NaN
1               None  ...                                  0.0
2               None  ...                                  NaN
3       Vijay Sharma  ...                                  NaN
4               None  ...                                  0.0
..               ...  ...                                  ...
72              None  ...                                  NaN
73              None  ...                                  0.0
74              None  ...                                  0.0
75              None  ...                                  NaN
76              None  ...                                  NaN

                                                                               \
   Any other payout (LTIP / Special allowance /other) Rewards Statutory Bonus
0                                                 NaN     NaN             NaN
1                                                 0.0     0.0             0.0
2                                                 NaN     NaN             NaN
3                                                 NaN     NaN             NaN
4                                                 0.0     0.0             0.0
..                                                ...     ...             ...
72                                                NaN     NaN             NaN
73                                                0.0     0.0             0.0
74                                                0.0     0.0             0.0
75                                                NaN     NaN             NaN
76                                                NaN     NaN             NaN

                                                                           \
   Relocation reimbursement City Compensatory Allowance MIP Deduct/Refund
0                       NaN                         NaN               NaN
1                       0.0                         0.0            1256.0
2                       NaN                         NaN               NaN
3                       NaN                         NaN               NaN
4                       0.0                         0.0               0.0
..                      ...                         ...               ...
72                      NaN                         NaN               NaN
73                      0.0                         0.0               0.0
74                      0.0                         0.0               0.0
75                      NaN                         NaN               NaN
76                      NaN                         NaN               NaN


   MIP Top up Deduction/Refund NPS Recovery PF Recovery
0                          NaN          NaN         NaN
1                          0.0          0.0         0.0
2                          NaN          NaN         NaN
3                          NaN          NaN         NaN
4                        286.0          0.0         0.0
..                         ...          ...         ...
72                         NaN          NaN         NaN
73                         0.0          0.0         0.0
74                         0.0          0.0         0.0
75                         NaN          NaN         NaN
76                         NaN          NaN         NaN

[77 rows x 107 columns]>

In [83]:
dst = db[collection]
result = dst.insert_many(normalized_docs)

# Old Files Data Cleaning Pipeline Generation

## Goal Status Report 2025-26 All.xlsx aka Goal Setting Status

In [22]:
path="../Ddata/Goal Status Report 2025-26 All.xlsx"
collection="goal_setting_status"
df=pd.read_excel(path,skiprows=1)

In [23]:
df.columns

Index(['PERSON_NUMBER', 'EMP_NAME', 'Department', 'SUB_DEPARTMENT',
       'Designation', 'Office_Location', 'Work_location', 'Parent_Grade',
       'Sub_grade', 'Region', 'DOJ', 'Manager_Number', 'Reporting_To',
       'REVIEWER_NUMBER', 'REVIEWER_NAME', 'STATUS'],
      dtype='object')

In [ ]:
FIELDS = [
    'PERSON_NUMBER', 
    'EMP_NAME', 
    'Department', 
    'SUB_DEPARTMENT',
    'Designation', 
    'Office_Location', 
    'Work_location', 
    'Parent_Grade',
    'Sub_grade', 
    'Region', 
    'DOJ', 
    'Manager_Number',
    'Reporting_To',
    'REVIEWER_NUMBER', 
    'REVIEWER_NAME', 
    'STATUS']


KEY_RENAMES = {
    "PERSON_NUMBER" : "employee code", 
    "EMP_NAME" : "employee name", 
    "Department" : "department", 
    "SUB_DEPARTMENT" : "sub department",
    "Designation" : "designation", 
    "Office_Location" : "office", 
    "Work_location" : "location", 
    "Parent_Grade" : "grade",
    "Sub_grade" : "grade level", 
    "Region" : "region", 
    "DOJ" : "date of joining", 
    "Manager_Number" : "manager employee code",
    "Reporting_To" : "reporting to",
    "REVIEWER_NUMBER" : "reviewer employee code", 
    "REVIEWER_NAME" : "reviewer name", 
    "STATUS":"status"
}

NUMERIC_FIELDS = [
    "employee code",
    "manager employee code",
    "reviewer employee code"
]

DATE_FIELDS = ["date of joining"]

In [25]:
raw_docs = []
df = df.where(df.notna(), None)
# Convert each DF row → raw dict
for idx, row in df.iterrows():
    raw_doc = row.to_dict()


    raw_docs.append(raw_doc)

# Normalize
normalized_docs = [
    normalize_doc_generic(
        doc,
        FIELDS,
        KEY_RENAMES,
        NUMERIC_FIELDS,
        DATE_FIELDS
    )
    for doc in raw_docs
]

In [28]:
normalized_docs

[{'employee code': 1004,
  'employee name': 'Gyanendra Singh',
  'department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'designation': 'Assistant Manager - Quality',
  'office': 'Lucknow',
  'location': 'Lucknow',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': 2430,
  'reporting to': 'Vishal Sethi',
  'reviewer employee code': 1626,
  'reviewer name': 'Suman Kumar Ghosh',
  'STATUS': 'APPROVED'},
 {'employee code': 1034,
  'employee name': 'Monoranjon Dutta',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'designation': 'Senior Manager - Field Service Delivery',
  'office': 'Kolkata',
  'location': 'Kolkata',
  'grade': 'M4',
  'grade level': 'M4a',
  'region': 'East',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'manager employee code': 4922,
  'reporting to': 'Joydeep Roy',
  'reviewer employee code': 3631,
  'reviewer name': 'Sujit Mondal',
  'STATUS': 'APPROVED'},
 {'employee code': 1045,
  'employee name': 'Metilda Molly Thomas',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'designation': 'Manager - Customer Operations',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'manager employee code': 293,
  'reporting to': 'Bhagat Bisht',
  'reviewer employee code': 2810,
  'reviewer name': 'Harit Nagpal',
  'STATUS': 'APPROVED'},
 {'employee code': 1060,
  'employee name': 'Thangudu Srinivasa Rao',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'designation': 'Manager - Field Service Delivery',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'manager employee code': 4127,
  'reporting to': 'Ashoka B',
  'reviewer employee code': 3082,
  'reviewer name': 'B. Sidharth Varma',
  'STATUS': 'APPROVED'},
 {'employee code': 107,
  'employee name': 'Chirag P. Thakar',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'designation': 'Assistant General Manager - Finance',
  'office': 'Corporate',
  'location': 'Mumbai',
  'grade': 'M3',
  'grade level': 'M3b',
  'region': 'Corporate',
  'date of joining': datetime.datetime(2005, 9, 20, 0, 0),
  'manager employee code': 2747,
  'reporting to': 'Avinash Kesherwani',
  'reviewer employee code': 7955,
  'reviewer name': 'Dinesh Patwari',
  'STATUS': 'APPROVED'},
 {'employee code': 1088,
  'employee name': 'Arun Dharampal',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'designation': 'Senior Executive - Field Service Delivery',
  'office': 'Noida',
  'location': 'Delhi',
  'grade': 'M5',
  'grade level': 'M5b',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'manager employee code': 4182,
  'reporting to': 'Brij Mohan Singh',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'STATUS': 'APPROVED'},
 {'employee code': 1107,
  'employee name': 'Ravi Pratap Singh',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'designation': 'Assistant Manager - Field Service Delivery',
  'office': 'Noida',
  'location': 'Delhi',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'manager employee code': 4182,
  'reporting to': 'Brij Mohan Singh',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'STATUS': 'APPROVED'},
 {'employee code': 1130,
  'employee name': 'Tanuja S.',
  'department': 'Customer Operations',
  'sub department': 'Customer Operations - General',
  'designation': 'Assistant Manager - Customer Operations',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 4, 17, 0, 0),
  'manager employee code': 1045,
  'reporting to': 'Metilda Molly Thomas',
  'reviewer employee code': 293,
  'reviewer name': 'Bhagat Bisht',
  'STATUS': 'APPROVED'},
 {'employee code': 1182,
  'employee name': 'Munesh Singh Jamwal',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'designation': 'Manager - Field Service Delivery',
  'office': 'Mohali',
  'location': 'Jalandhar',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'manager employee code': 2934,
  'reporting to': 'Vikrant Sehgal',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'STATUS': 'APPROVED'},
 {'employee code': 1187,
  'employee name': 'Tajinder Pal Singh',
  'department': 'Technology',
  'sub department': 'Broadcast/OTT Engineering',
  'designation': 'Senior Vice President - Head Broadcast Engineering',
  'office': 'Chattarpur',
  'location': 'Delhi',
  'grade': 'M2',
  'grade level': 'M2a',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'manager employee code': 2810,
  'reporting to': 'Harit Nagpal',
  'reviewer employee code': None,
  'reviewer name': 'NA',
  'STATUS': 'APPROVED'},
 {'employee code': 1192,
  'employee name': 'Jaipal Singh Bhandari',
  'department': 'Technology',
  'sub department': 'Consumer Technology',
  'designation': 'Manager - Repair Centre',
  'office': 'Chattarpur',
  'location': 'Delhi',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'manager employee code': 1760,
  'reporting to': 'Rajaneesh Chaubey',
  'reviewer employee code': 2536,
  'reviewer name': 'Kundan Singh',
  'STATUS': 'APPROVED'},
 {'employee code': 1205,
  'employee name': 'Vijay Khera',
  'department': 'Field Service Delivery',
  'sub department': 'MIS & Business Information',
  'designation': 'General Manager - MIS & Business Information',
  'office': 'Noida',
  'location': 'Noida',
  'grade': 'M3',
  'grade level': 'M3a',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'manager employee code': 481,
  'reporting to': 'Krishan Kansal',
  'reviewer employee code': 293,
  'reviewer name': 'Bhagat Bisht',
  'STATUS': 'APPROVED'},
 {'employee code': 1213,
  'employee name': 'Praveen Singh',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'designation': 'Manager - Field Service Delivery',
  'office': 'Mohali',
  'location': 'Ludhiana',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'manager employee code': 2934,
  'reporting to': 'Vikrant Sehgal',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'STATUS': 'APPROVED'},
 {'employee code': 1252,
  'employee name': 'Soumya Swamy',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'designation': 'Manager - Field Service Delivery',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 4, 24, 0, 0),
  'manager employee code': 4127,
  'reporting to': 'Ashoka B',
  'reviewer employee code': 3082,
  'reviewer name': 'B. Sidharth Varma',
  'STATUS': 'APPROVED'},
 {'employee code': 1308,
  'employee name': 'R. Jayaprakash',
  'department': 'Finance',
  'sub department': 'Finance - General',
  'designation': 'General Manager - Finance',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M3',
  'grade level': 'M3a',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 2, 0, 0),
  'manager employee code': 7955,
  'reporting to': 'Dinesh Patwari',
  'reviewer employee code': 4044,
  'reviewer name': 'Sambasivan G.',
  'STATUS': 'APPROVED'},
 {'employee code': 1313,
  'employee name': 'Lenin Suresh Raj',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'designation': 'Assistant General Manager - Business Intelligence and Forecasting',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M3',
  'grade level': 'M3b',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 2, 0, 0),
  'manager employee code': 7227,
  'reporting to': 'Vinodkumar Anandan',
  'reviewer employee code': 2039,
  'reviewer name': 'Pavan Kumar Muktapuram',
  'STATUS': 'APPROVED'},
 {'employee code': 1314,
  'employee name': 'Ponselvam Devasagayam',
  'department': 'Customer Operations',
  'sub department': 'N.V.S.D',
  'designation': 'Assistant Manager - NVSD Customer Admin',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 2, 0, 0),
  'manager employee code': 2243,
  'reporting to': 'Manjunatha J.S.',
  'reviewer employee code': 4895,
  'reviewer name': 'S Suresh Babu',
  'STATUS': 'APPROVED'},
 {'employee code': 1345,
  'employee name': 'Jaya N.',
  'department': 'Sales',
  'sub department': 'MIS & Reporting-Sales',
  'designation': 'Manager - MIS & Reporting-Sales',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 2, 0, 0),
  'manager employee code': 2366,
  'reporting to': 'Devadas Shenoy K.P.',
  'reviewer employee code': 293,
  'reviewer name': 'Bhagat Bisht',
  'STATUS': 'APPROVED'},
 {'employee code': 1363,
  'employee name': 'Anup P. Lobo',
  'department': 'Field Service Delivery',
  'sub department': 'Service Training - FSD',
  'designation': 'Manager - Service Training',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 8, 0, 0),
  'manager employee code': 4127,
  'reporting to': 'Ashoka B',
  'reviewer employee code': 3082,
  'reviewer name': 'B. Sidharth Varma',
  'STATUS': 'APPROVED'},
 {'employee code': 1377,
  'employee name': 'B.P. Tharamani',
  'department': 'Customer Operations',
  'sub department': 'Budgeting & AOP',
  'designation': 'Assistant Manager - Vendor Management & Outbound Billing Operations',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 8, 0, 0),
  'manager employee code': 5007,
  'reporting to': 'Shrinidhi DC',
  'reviewer employee code': 2039,
  'reviewer name': 'Pavan Kumar Muktapuram',
  'STATUS': 'APPROVED'},
 {'employee code': 1382,
  'employee name': 'C. Sheik Mehaboob Basha',
  'department': 'Field Service Delivery',
  'sub department': 'Service Training - FSD',
  'designation': 'Senior Manager - Service Training',
  'office': 'Noida',
  'location': 'Delhi',
  'grade': 'M4',
  'grade level': 'M4a',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 5, 8, 0, 0),
  'manager employee code': 4182,
  'reporting to': 'Brij Mohan Singh',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'STATUS': 'APPROVED'},
 {'employee code': 1404,
  'employee name': 'Robin Thomas',
  'department': 'Field Service Delivery',
  'sub department': 'Service Training - FSD',
  'designation': 'Senior Manager - Service Training',
  'office': 'Noida',
  'location': 'Delhi',
  'grade': 'M4',
  'grade level': 'M4a',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 5, 15, 0, 0),
  'manager employee code': 4182,
  'reporting to': 'Brij Mohan Singh',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'STATUS': 'APPROVED'},
 {'employee code': 1413,
  'employee name': 'Tejbir Singh',
  'department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'designation': 'Senior Executive - Quality',
  'office': 'Chattarpur',
  'location': 'Delhi',
  'grade': 'M5',
  'grade level': 'M5b',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 5, 15, 0, 0),
  'manager employee code': 2430,
  'reporting to': 'Vishal Sethi',
  'reviewer employee code': 1626,
  'reviewer name': 'Suman Kumar Ghosh',
  'STATUS': 'APPROVED'},
 {'employee code': 1423,
  'employee name': 'Ashok Kumar Thakur',
  'department': 'Finance',
  'sub department': 'Supply Chain Services',
  'designation': 'Assistant General Manager - Supply Chain Services',
  'office': 'Lucknow',
  'location': 'Lucknow',
  'grade': 'M3',
  'grade level': 'M3b',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 5, 15, 0, 0),
  'manager employee code': 1907,
  'reporting to': 'Devinder Singh',
  'reviewer employee code': 4771,
  'reviewer name': 'Anil Dalvi',
  'STATUS': 'APPROVED'},
 {'employee code': 1434,
  'employee name': 'Abdul Rahim Nazar',
  'department': 'Customer Operations',
  'sub department': 'COSSG',
  'designation': 'Assistant General Manager - Systems Solutions & Design - COSSG',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M3',
  'grade level': 'M3b',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 15, 0, 0),
  'manager employee code': 5377,
  'reporting to': 'Reema Kukreja',
  'reviewer employee code': 5034,
  'reviewer name': 'Abhijeet Banerji',
  'STATUS': 'APPROVED'},
 {'employee code': 1449,
  'employee name': 'A. Suresh',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'designation': 'Manager - Field Service Delivery',
  'office': 'Chennai',
  'location': 'Chennai',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 15, 0, 0),
  'manager employee code': 4069,
  'reporting to': 'K Satheesh Kumar',
  'reviewer employee code': 3082,
  'reviewer name': 'B. Sidharth Varma',
  'STATUS': 'APPROVED'},
 {'employee code': 1458,
  'employee name': 'Monalisa Boruah',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'designation': 'Assistant General Manager - Field Service Delivery',
  'office': 'Guwahati',
  'location': 'Guwahati',
  'grade': 'M3',
  'grade level': 'M3b',
  'region': 'East',
  'date of joining': datetime.datetime(2006, 5, 22, 0, 0),
  'manager employee code': 3631,
  'reporting to': 'Sujit Mondal',
  'reviewer employee code': 293,
  'reviewer name': 'Bhagat Bisht',
  'STATUS': 'APPROVED'},
 {'employee code': 1460,
  'employee name': 'Rajkumar Sau',
  'department': 'Sales',
  'sub department': 'Trade Sales',
  'designation': 'Manager - Trade Sales',
  'office': 'Kolkata',
  'location': 'Kolkata',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'East',
  'date of joining': datetime.datetime(2006, 5, 22, 0, 0),
  'manager employee code': 6441,
  'reporting to': 'Sanjeev Kumar',
  'reviewer employee code': 3921,
  'reviewer name': 'Sanjay Gotimukul',
  'STATUS': 'APPROVED'},
 {'employee code': 1470,
  'employee name': 'Rajender Sharma',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'designation': 'Assistant Manager - Field Service Delivery',
  'office': 'Noida',
  'location': 'Delhi',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 5, 22, 0, 0),
  'manager employee code': 4182,
  'reporting to': 'Brij Mohan Singh',
  'reviewer employee code': 1480,
  'reviewer name': 'Sanjay Mittal',
  'STATUS': 'APPROVED'},
 {'employee code': 1480,
  'employee name': 'Sanjay Mittal',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'designation': 'Senior Vice President - Field Service Delivery',
  'office': 'Noida',
  'location': 'Noida',
  'grade': 'M2',
  'grade level': 'M2a',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 5, 22, 0, 0),
  'manager employee code': 293,
  'reporting to': 'Bhagat Bisht',
  'reviewer employee code': 2810,
  'reviewer name': 'Harit Nagpal',
  'STATUS': 'APPROVED'},
 {'employee code': 1503,
  'employee name': 'Thomas George',
  'department': 'Finance',
  'sub department': 'Business Excellence',
  'designation': 'General Manager - Business Excellence',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M3',
  'grade level': 'M3a',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 22, 0, 0),
  'manager employee code': 4329,
  'reporting to': 'Hemant Bhatkhande',
  'reviewer employee code': 4044,
  'reviewer name': 'Sambasivan G.',
  'STATUS': 'APPROVED'},
 {'employee code': 1518,
  'employee name': 'R. Malarvizhi',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery Support',
  'designation': 'Senior Manager - Field Service Delivery Support',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M4',
  'grade level': 'M4a',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 22, 0, 0),
  'manager employee code': 3082,
  'reporting to': 'B. Sidharth Varma',
  'reviewer employee code': 293,
  'reviewer name': 'Bhagat Bisht',
  'STATUS': 'APPROVED'},
 {'employee code': 1523,
  'employee name': 'T. Shanmugamanivel',
  'department': 'Sales',
  'sub department': 'Sales - General',
  'designation': 'General Manager - Sales',
  'office': 'Chennai',
  'location': 'Chennai',
  'grade': 'M3',
  'grade level': 'M3a',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 22, 0, 0),
  'manager employee code': 7494,
  'reporting to': 'Vivek Damodaran E',
  'reviewer employee code': 293,
  'reviewer name': 'Bhagat Bisht',
  'STATUS': 'APPROVED'},
 {'employee code': 1530,
  'employee name': 'Ritesh Jain',
  'department': 'Finance',
  'sub department': 'Supply Chain Services',
  'designation': 'Assistant General Manager - Supply Chain Services',
  'office': 'Pune',
  'location': 'Pune',
  'grade': 'M3',
  'grade level': 'M3b',
  'region': 'West',
  'date of joining': datetime.datetime(2006, 5, 22, 0, 0),
  'manager employee code': 2073,
  'reporting to': 'Suresh Menon',
  'reviewer employee code': 4771,
  'reviewer name': 'Anil Dalvi',
  'STATUS': 'APPROVED'},
 {'employee code': 1576,
  'employee name': 'Vasanth Kumar S.P.',
  'department': 'Customer Operations',
  'sub department': 'N.V.S.D',
  'designation': 'Manager - NVSD Customer Admin',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 29, 0, 0),
  'manager employee code': 2222,
  'reporting to': 'Amala Rani',
  'reviewer employee code': 4895,
  'reviewer name': 'S Suresh Babu',
  'STATUS': 'APPROVED'},
 {'employee code': 1582,
  'employee name': 'Vijaya Mary A.',
  'department': 'Customer Operations',
  'sub department': 'N.V.S.D',
  'designation': 'Manager - NVSD Quality',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 29, 0, 0),
  'manager employee code': 5267,
  'reporting to': 'Gurpreet Singh',
  'reviewer employee code': 4895,
  'reviewer name': 'S Suresh Babu',
  'STATUS': 'APPROVED'},
 {'employee code': 1583,
  'employee name': 'Roopa S. Hiremath',
  'department': 'Customer Operations',
  'sub department': 'Business Intelligence and Forecasting',
  'designation': 'Senior Manager - Business Intelligence and Forecasting',
  'office': 'Hebbal',
  'location': 'Bangalore',
  'grade': 'M4',
  'grade level': 'M4a',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 5, 29, 0, 0),
  'manager employee code': 1313,
  'reporting to': 'Lenin Suresh Raj',
  'reviewer employee code': 7227,
  'reviewer name': 'Vinodkumar Anandan',
  'STATUS': 'APPROVED'},
 {'employee code': 1585,

## Performance Goal Report 25-26.xlsx

In [35]:
path="../Ddata/Performance Goal Report 25-26.xlsx"
collection="goal_setting_status"
df=pd.read_excel(path,skiprows=2)

In [39]:
df.columns

Index(['Person Number', 'Name', 'Department', 'Sub Department', 'Grade',
       'Sub Grade', 'Region', 'Review Period Name', 'Goal Plan Name',
       'Goal Name', 'Weight', 'Description'],
      dtype='object')

In [40]:
FIELDS = ['Person Number', 'Name', 'Department', 'Sub Department', 'Grade',
       'Sub Grade', 'Region', 'Review Period Name', 'Goal Plan Name',
       'Goal Name', 'Weight', 'Description']


KEY_RENAMES = {
        "Person Number" : "employee code",
        "Name" : "employee name",
        "Department" : "Department",
        "Sub Department" : "sub department",
        "Grade" : "grade",
        "Sub Grade" : "grade level",
        "Region" : "region",
        "Review Period Name" : "review period name",
        "Goal Plan Name" : "goal plan name",
        "Goal Name" : "goal name",
        "Weight" : "weight",
        "Description" : "description"
}

NUMERIC_FIELDS = [
    "employee code",
    "weight"
]

DATE_FIELDS = []

In [41]:
raw_docs = []
df = df.where(df.notna(), None)
# Convert each DF row → raw dict
for idx, row in df.iterrows():
    raw_doc = row.to_dict()


    raw_docs.append(raw_doc)

# Normalize
normalized_docs = [
    normalize_doc_generic(
        doc,
        FIELDS,
        KEY_RENAMES,
        NUMERIC_FIELDS,
        DATE_FIELDS
    )
    for doc in raw_docs
]

In [42]:
normalized_docs

[{'employee code': 1004,
  'employee name': 'Gyanendra Singh',
  'Department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Buddy Ride, Competiton Audit & Field Trial Audits',
  'weight': 20,
  'description': '* Buddy Ride Activity of Third Party Auditors - Each Auditor Should be covered every month in base city * Special Task as per requirement * Audit of Field Trial Material as per requirement'},
 {'employee code': 1004,
  'employee name': 'Gyanendra Singh',
  'Department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'MDU Audits',
  'weight': 10,
  'description': '* Conducting MDU Capex Audits (>=60 %) within 5 working days for base city & within 10 working days for others * Accuracy of the report (MDU) * Timely reporting (MDU) * MDU Report with supporting documents online & excel by Friday/Saturday'},
 {'employee code': 1004,
  'employee name': 'Gyanendra Singh',
  'Department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Producitivity (ODU Audits & Engineer Audits)',
  'weight': 45,
  'description': '* Productivity * 30 Engineer Audit per Month covering 8 ISPs per month * One new ISP per month which is not covered in last six months * 3P Data Validation'},
 {'employee code': 1004,
  'employee name': 'Gyanendra Singh',
  'Department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Timely reporting & Accuracy (ODU)',
  'weight': 25,
  'description': '* Timely reporting (100%) * Accuracy of reports (100%) * Accuracy of 3P Data Validation'},
 {'employee code': 1034,
  'employee name': 'Monoranjon Dutta',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4a',
  'region': 'East',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Business Support',
  'weight': 32,
  'description': 'Binge Paid Pack eligible upsell % Overall (DTH + Non-DTH) >=10% 10.0% Recharge, LDP & other offers as per business need >=15% 10.0% Live TV Download+ 1st Transacting %\xa0 from overall eligible Base >=50% 2.0% Overall activations vs Sales target >=100% 10.0%'},
 {'employee code': 1034,
  'employee name': 'Monoranjon Dutta',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4a',
  'region': 'East',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Control & Compliance',
  'weight': 25,
  'description': "Net exposure of Inactive ISPs (< 10 Payable WO's) > 180 Days 0.0 5.0% M2 deactive target vs ach % As per grid 5.0% As per Hygiene report Logic As per grid 10.0% QR code capture vs overall Install completed >=75% 5.0%"},
 {'employee code': 1034,
  'employee name': 'Monoranjon Dutta',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4a',
  'region': 'East',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Customer & Quality',
  'weight': 43,
  'description': 'Definition Top 8 ASM "Non OCS : Retail Install - 4 Hrs. TAT OCS : All WO:s Slot adherence excl. Projects & WO\'s part of Completion" >=92% 5.0% All WO\'s excluding Projects & WO\'s part of completion % >=94% 8.0% TSA/Web WO\'s + Relocation + Retail COD WOs >=77% 5.0% ETA* / IMA Total calls % + Escalation 5 (> 2 Hrs.) + Escalation 6 (Complaint) <=2.0% 5.0% NPS Score : WO Completed >=95 5.0% NPS Score : WO Cancelled >=95 5.0% Repeat FR on FR creation to creation within 30 days <=10% 5.0% Repeat FR on FR & FR in Install (@ Box level Including Swap) on completion <=2.5% 3.0% <=0.3% No fault found % in swap boxes <=5% 2.0%'},
 {'employee code': 1060,
  'employee name': 'Thangudu Srinivasa Rao',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Compliance & Control',
  'weight': 35,
  'description': 'RnM Preventive Maintenance (RnM) (RnM required vs done within month) >=90% NDC - Records Monthly Record submission from MDU vendors 100% MDU Material Ageing MDU material lying with Contractors > 6 months old <=4.0% MDU Material Exposure SD /MDU Exposure As per norm MDU Cost Variance MDU building Projected Cost Vs Actual Cost variance <=5%'},
 {'employee code': 1060,
  'employee name': 'Thangudu Srinivasa Rao',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Customer & Quality',
  'weight': 65,
  'description': 'Installation WO TAT Completion % of MDU Install WOs within 15 days (Except New Build) >=80% FR WO TAT Completion % of MDU FR WOs within 24 hrs >=90% RnM WO TAT Completion % of MDU RnM WOs within 48 hrs >=90% Survery WO TAT Completion % of MDU Survey WOs within 5 days >=80% IO/PO to RFS IO/PO to RFS time <= 15 days (Except New Build) >=90% MDU Backbone Repeat MDU Backbone repeat FR Within 30 days on RnM or MDU FR<=1.5% Subs FR per MDU Field repair WO from subscribers latched to MDU building <=15% MDU TG Audit NC Technology audit NC% (Both Technical & Material) <=0.5%'},
 {'employee code': 1088,
  'employee name': 'Arun Dharampal',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Business Support',
  'weight': 32,
  'description': 'RoCE Binge Paid packs - Overall Binge Paid Pack eligible upsell % Overall (DTH + Non-DTH) >=10% Rech n LDP Recharge, LDP & other offers as per business need >=15% LTV DL + 1st Transacting Live TV Download+ 1st Transacting %\xa0 from overall eligible Base >=50% Activations Activations Overall activations vs Sales target >=100%'},
 {'employee code': 1088,
  'employee name': 'Arun Dharampal',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Control & Compliance',
  'weight': 25,
  'description': "Control FnF Net exposure of Inactive ISPs (< 10 Payable WO's) > 180 Days 0.0 M2 Deact Ach M2 deactive target vs ach % Compliance Hygiene Score As per Hygiene report Logic QR code capture in Install QR code capture vs overall Install completed >=75%"},
 {'employee code': 1088,
  'employee name': 'Arun Dharampal',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Customer & Quality',
  'weight': 43,
  'description': 'Speed 4 Hrs TAT Retail Install & OCS slot adherence "Non OCS : Retail Install - 4 Hrs. TAT OCS : All WO:s Slot adherence excl. Projects & WO\'s part of Completion" >=92% 24 Hrs TAT All WO\'s excluding Projects & WO\'s part of completion % >=94% WO Completion TSA/Web WO\'s + Relocation + Retail COD WOs >=77% Customer Experience Escalations ETA* / IMA Total calls % + Escalation 5 (> 2 Hrs.) + Escalation 6 (Complaint) <=2.0% NPS Completed NPS Score : WO Completed >=95 NPS Cancelled NPS Score : WO Cancelled >=95 Quality Repeat FR Creation Repeat FR on FR creation to creation within 30 days <=10% Repeat FR on FR/ Install Repeat FR on FR & FR in Install (@ Box level Including Swap) on completion <=2.5% <=0.3% NFF No fault found % in swap boxes <=5%'},
 {'employee code': 1107,
  'employee name': 'Ravi Pratap Singh',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Business Support',
  'weight': 32,
  'description': 'Goal Objective KPI Definition Top 8 Business Support RoCE Binge Paid packs - Overall Binge Paid Pack eligible upsell % Overall (DTH + Non-DTH) >=10% Rech n LDP Recharge, LDP & other offers as per business need >=15% LTV DL + 1st Transacting Live TV Download+ 1st Transacting %\xa0 from overall eligible Base >=50% Activations Activations Overall activations vs Sales target >=100%'},
 {'employee code': 1107,
  'employee name': 'Ravi Pratap Singh',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Control & Compliance',
  'weight': 25,
  'description': "Goal Objective KPI Definition Top 8 Control & Compliance Control FnF Net exposure of Inactive ISPs (< 10 Payable WO's) > 180 Days 0.0 M2 Deact Ach M2 deactive target vs ach % Compliance Hygiene Score As per Hygiene report Logic QR code capture in Install QR code capture vs overall Install completed >=75%"},
 {'employee code': 1107,
  'employee name': 'Ravi Pratap Singh',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M5',
  'grade level': 'M5a',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Customer & Quality',
  'weight': 43,
  'description': 'Goal Objective KPI Definition Top 8 Customer & Quality Speed 4 Hrs TAT Retail Install & OCS slot adherence "Non OCS : Retail Install - 4 Hrs. TAT OCS : All WO:s Slot adherence excl. Projects & WO\'s part of Completion" >=92% 24 Hrs TAT All WO\'s excluding Projects & WO\'s part of completion % >=94% WO Completion TSA/Web WO\'s + Relocation + Retail COD WOs >=77% Customer Experience Escalations ETA* / IMA Total calls % + Escalation 5 (> 2 Hrs.) + Escalation 6 (Complaint) <=2.0% NPS Completed NPS Score : WO Completed >=95 NPS Cancelled NPS Score : WO Cancelled >=95 Quality Repeat FR Creation Repeat FR on FR creation to creation within 30 days <=10% Repeat FR on FR/ Install Repeat FR on FR & FR in Install (@ Box level Including Swap) on completion <=2.5% <=0.3% NFF No fault found % in swap boxes <=5%'},
 {'employee code': 1182,
  'employee name': 'Munesh Singh Jamwal',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Business Support',
  'weight': 32,
  'description': 'Binge Paid packs - Overall Binge Paid Pack eligible upsell % Overall (DTH + Non-DTH) >=10% Rech n LDP Recharge, LDP & other offers as per business need >=15% LTV DL + 1st Transacting Live TV Download+ 1st Transacting %\xa0 from overall eligible Base >=50% Activations Overall activations vs Sales target >=100%'},
 {'employee code': 1182,
  'employee name': 'Munesh Singh Jamwal',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Control & Compliance',
  'weight': 25,
  'description': "FnF Net exposure of Inactive ISPs (< 10 Payable WO's) > 180 Days 0.0 M2 Deact Ach M2 deactive target vs ach % As per grid Hygiene Score As per Hygiene report Logic As per grid QR code capture in Install QR code capture vs overall Install completed >=65%"},
 {'employee code': 1182,
  'employee name': 'Munesh Singh Jamwal',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Customer & Quality',
  'weight': 43,
  'description': '4 Hrs TAT Retail Install & OCS slot adherence "Non OCS : Retail Install - 4 Hrs. TAT OCS : All WO:s Slot adherence excl. Projects & WO\'s part of Completion" >=94% 24 Hrs TAT All WO\'s excluding Projects & WO\'s part of completion % >=95% WO Completion TSA/Web WO\'s + Relocation + Retail COD WOs >=76% Escalations ETA* / IMA Total calls % + Escalation 5 (> 2 Hrs.) + Escalation 6 (Complaint) <=2.5% NPS Completed NPS Score : WO Completed >=95 NPS Cancelled NPS Score : WO Cancelled >=95 Repeat FR Creation Repeat FR on FR creation to creation within 30 days <=10% Repeat FR on FR Repeat FR on FR (@ Box level Including Swap) on completion <=2.0% Repeat FR on Install Repeat FR on Install (@ Box level Including Swap) on completion <=0.3% NFF No fault found % in swap boxes <=5%'},
 {'employee code': 1192,
  'employee name': 'Jaipal Singh Bhandari',
  'Department': 'Technology',
  'sub department': 'Consumer Technology',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': '1. Goal: Output / TAT',
  'weight': 35,
  'description': 'Repair Yield: - HD: -58% Android :75% (Considering BGA availability) Partner Target Dispatch Yield: - HD: -65% Android: -80% (Considering BGA availability) TAT: - HD/4K: -7 working days Android: -7 working days HD BER: - 15 days (Considering BGA availability) Android: -15 days (Considering BGA availability) SAT Meter: -7 days'},
 {'employee code': 1192,
  'employee name': 'Jaipal Singh Bhandari',
  'Department': 'Technology',
  'sub department': 'Consumer Technology',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Audit & Reports',
  'weight': 10,
  'description': 'Delay in ZMAN acknowledgement: -0 days GRN of def STB: - ≤ 5 days (1K qty) Notification closure pendency (After 48 hrs. dispatch): -0 Audit NC closure: -3 weeks from audit report BER & IR ageing: -≤ 90days Notification creation: -≤ 3 days Stock in transit: -≤ 30days Factbook reports (Monthly Reports):-Before 2nd of every month NFF report: -Every Saturday Impedance report: -Before 5th of every month Soak temp: -Every Monday Signal & Earthing: -Daily Environment Control (Store): -Daily BB Analysis: -Before 5th of every month'},
 {'employee code': 1192,
  'employee name': 'Jaipal Singh Bhandari',
  'Department': 'Technology',
  'sub department': 'Consumer Technology',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Bounce back / Quality',
  'weight': 35,
  'description': '90 days BB (STB): -≤ 3.75% DOA (STB): - ≤ 0.5% (180 days from dispatch) LAR (PDI): -≥ 85%'},
 {'employee code': 1192,
  'employee name': 'Jaipal Singh Bhandari',
  'Department': 'Technology',
  'sub department': 'Consumer Technology',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Spares & Inventory Management',
  'weight': 10,
  'description': 'Monthly PI (Spares): -Before 2nd of every month Monthly PI (STB): -Before 2nd of every month Spare dashboard: -Before 2nd of every month Maintaining Spare MSL: -6 months Spare consumption posting (after dispatch): -≤ 2 days Pending for spares/cosmetics: -0 RC to RC location spare movement: -≤ 15 days'},
 {'employee code': 1192,
  'employee name': 'Jaipal Singh Bhandari',
  'Department': 'Technology',
  'sub department': 'Consumer Technology',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Training & Grooming',
  'weight': 10,
  'description': 'Regular training for RC staff, monitoring efficiency of training as below: - Pre-Soak: - ≤ 2% Soak: - ≤ 5% FT: -≤ 10% Impedance: -≤ 2% QC: -≤ 1% TPL PDI: -≤ 0.1%'},
 {'employee code': 1213,
  'employee name': 'Praveen Singh',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Business Support',
  'weight': 32,
  'description': 'RoCE :- Binge Paid packs - Overall >=10% Rech n LDP >=15% LTV DL + 1st Transacting >=50% Activations :- Activations >=100%'},
 {'employee code': 1213,
  'employee name': 'Praveen Singh',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Control & Compliance',
  'weight': 25,
  'description': 'Control :- FnF 0 M2 Deact Ach As per grid Compliance :- Hygiene Score As per grid QR code capture in Install >=65%'},
 {'employee code': 1213,
  'employee name': 'Praveen Singh',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'North',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Customer & Quality',
  'weight': 43,
  'description': 'Speed :- 4 Hrs TAT Retail Install & OCS slot adherence >=94% 24 Hrs TAT >=95% WO Completion >=76% Customer Experience :- Escalations <=2.5% NPS Completed >=95 NPS Cancelled >95 Quality :- Repeat FR Creation <=10% Repeat FR on FR/ Install <=2.0%/0.3% NFF <=5%'},
 {'employee code': 1252,
  'employee name': 'Soumya Swamy',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',
  'review period name': 'Performance Review 2025-26',
  'goal plan name': 'Goal Plan for 2025-26',
  'goal name': 'Business Support',
  'weight': 32,
  'description': 'Binge Paid packs - Overall : Binge Paid Pack eligible upsell % Overall (DTH + Non-DTH) - >=10% 10% Rech n LDP : Recharge, LDP & other offers as per business need - >=15% 10% LTV DL + 1st Transacting : Live TV Download+ 1st Transacting %\xa0 from overall eligible Base - >=50% 2% Activations : Overall activations vs Sales target - >=100% 10%'},
 {'employee code': 1252,
  'employee name': 'Soumya Swamy',
  'Department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'grade': 'M4',
  'grade level': 'M4b',
  'region': 'South',

## 1.DatabaseReport_Rpt_Data base Report_for Kreeda Labs.xlsx aka Base Report

In [50]:
path="../Ddata/1.DatabaseReport_Rpt_Data base Report_for Kreeda Labs.xlsx"
collection="goal_setting_status"
df=pd.read_excel(path,skiprows=0)

In [51]:
df.columns

Index(['Employee Code', 'FIRST NAME', 'LAST NAME', 'GRADE', 'Grade Level',
       'Designation', 'DEPARTMENT', 'SUB-DEPT', 'Location', 'Office', 'Region',
       'DOJ', 'Manager Code', 'Reporting To', 'State', 'Circle', 'DOB', 'M/F',
       'Primary Email', 'Assignment Status Type', 'DOR', 'DOL', 'Role',
       'Last year Rating', 'Reason for Resignation'],
      dtype='object')

In [52]:
FIELDS = ['Employee Code', 'FIRST NAME', 'LAST NAME', 'GRADE', 'Grade Level',
       'Designation', 'DEPARTMENT', 'SUB-DEPT', 'Location', 'Office', 'Region',
       'DOJ', 'Manager Code', 'Reporting To', 'State', 'Circle', 'DOB', 'M/F',
       'Primary Email', 'Assignment Status Type', 'DOR', 'DOL', 'Role',
       'Last year Rating', 'Reason for Resignation']

KEY_RENAMES = {
        "Employee Code" : "employee code",
        "FIRST NAME" : "first name",
        "LAST NAME" : "last name",
        "GRADE" : "grade",
        "Grade Level" : "grade level",
        "Designation" : "Designation",
        "DEPARTMENT" : "department",
        "SUB-DEPT" : "sub department",
        "Location" : "location",
        "Office" : "office",
        "Region" : "region",
        "DOJ" : "date of joining",
        "Manager Code" : "manager employee code",
        "Reporting To" : "reporting to",
        "State" : "state",
        "Circle" : "circle",
        "DOB" : "date of birth",
        "M/F" : "gender",
        "Primary Email" : "email",
        "Assignment Status Type" : "assignment status type",
        "DOR" : "date of resignation",
        "DOL" : "date of leaving",
        "Role" : "role",
        "Last year Rating" : "last year rating",
        "Reason for Resignation" : "reason for resignation"
}

NUMERIC_FIELDS = [
    "employee code",
    "manager employee code",
    "last year rating"
]

DATE_FIELDS = ["date of birth","date of joining","date of resignation","date of leaving",]

In [53]:
raw_docs = []
df = df.where(df.notna(), None)
# Convert each DF row → raw dict
for idx, row in df.iterrows():
    raw_doc = row.to_dict()


    raw_docs.append(raw_doc)

# Normalize
normalized_docs = [
    normalize_doc_generic(
        doc,
        FIELDS,
        KEY_RENAMES,
        NUMERIC_FIELDS,
        DATE_FIELDS
    )
    for doc in raw_docs
]

In [54]:
normalized_docs

[{'employee code': 1,
  'first name': 'Vikram',
  'last name': 'Kaushik',
  'grade': 'M0',
  'grade level': 'M.0',
  'Designation': 'Managing Director and CEO',
  'department': 'Executive Office',
  'sub department': 'Executive Office - General',
  'location': 'Mumbai',
  'office': 'Corporate',
  'region': 'Corporate',
  'date of joining': datetime.datetime(2004, 3, 22, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1950, 9, 17, 0, 0),
  'gender': 'Male',
  'email': 'vikramk@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2010, 12, 31, 0, 0),
  'date of leaving': datetime.datetime(2010, 12, 31, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 10,
  'first name': 'Irene',
  'last name': "D'Cunha",
  'grade': 'M4',
  'grade level': 'M4b',
  'Designation': "Manager CEO's Office",
  'department': 'Executive Office',
  'sub department': 'Executive Office - General',
  'location': 'Mumbai',
  'office': 'Corporate',
  'region': 'Corporate',
  'date of joining': datetime.datetime(2005, 6, 6, 0, 0),
  'manager employee code': 2810,
  'reporting to': 'Harit Nagpal',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1960, 1, 10, 0, 0),
  'gender': 'Female',
  'email': 'irened@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2021, 1, 1, 0, 0),
  'date of leaving': datetime.datetime(2021, 1, 31, 0, 0),
  'role': 'NA',
  'last year rating': 4,
  'reason for resignation': 'Voluntary'},
 {'employee code': 100,
  'first name': 'Sajan',
  'last name': 'David',
  'grade': 'M5',
  'grade level': 'M5a',
  'Designation': 'Senior Executive - Quality',
  'department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'location': 'Chennai',
  'office': 'Chennai',
  'region': 'South',
  'date of joining': datetime.datetime(2005, 9, 19, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Tamil Nadu',
  'circle': 'NA',
  'date of birth': datetime.datetime(1963, 3, 8, 0, 0),
  'gender': 'Male',
  'email': 'sajand@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2013, 7, 10, 0, 0),
  'date of leaving': datetime.datetime(2013, 7, 10, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1000,
  'first name': 'Vipin',
  'last name': 'Yadav',
  'grade': 'M5',
  'grade level': 'M5a',
  'Designation': 'Senior Area Trade Sales Incharge - Jaipur',
  'department': 'Sales',
  'sub department': 'Trade Sales',
  'location': 'Jaipur',
  'office': 'Jaipur',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Rajasthan',
  'circle': 'NA',
  'date of birth': datetime.datetime(1977, 5, 16, 0, 0),
  'gender': 'Male',
  'email': 'vipiny@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2011, 10, 18, 0, 0),
  'date of leaving': datetime.datetime(2011, 10, 18, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1001,
  'first name': 'Bhanu',
  'last name': 'Pareek',
  'grade': 'M3',
  'grade level': 'M3z',
  'Designation': 'Assistant General Manager Direct Sales - North',
  'department': 'Sales & Service',
  'sub department': 'Sales & Service - Direct Sales',
  'location': 'Delhi',
  'office': 'Chattarpur',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Delhi',
  'circle': 'NA',
  'date of birth': datetime.datetime(1971, 1, 4, 0, 0),
  'gender': 'Male',
  'email': 'bhanup@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2011, 1, 7, 0, 0),
  'date of leaving': datetime.datetime(2011, 1, 7, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1002,
  'first name': 'Vimal',
  'last name': 'Bhatt',
  'grade': 'M5',
  'grade level': 'M5z',
  'Designation': 'Senior Field Services Team Leader - Karnal',
  'department': 'Field Services',
  'sub department': 'Installation',
  'location': 'Karnal',
  'office': 'Okhla',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'New Delhi',
  'circle': 'NA',
  'date of birth': datetime.datetime(1979, 5, 1, 0, 0),
  'gender': 'Male',
  'email': 'vimalb@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2007, 12, 1, 0, 0),
  'date of leaving': datetime.datetime(2007, 12, 1, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1003,
  'first name': 'Vishal',
  'last name': 'Bhardwaj',
  'grade': 'M6',
  'grade level': 'M6z',
  'Designation': 'Senior Field Services Engineer - Delhi',
  'department': 'Field Services',
  'sub department': 'Installation',
  'location': 'Delhi',
  'office': 'Okhla',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'New Delhi',
  'circle': 'NA',
  'date of birth': datetime.datetime(1982, 12, 6, 0, 0),
  'gender': 'Male',
  'email': 'Vishalb@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2008, 4, 1, 0, 0),
  'date of leaving': datetime.datetime(2008, 4, 1, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1004,
  'first name': 'Gyanendra',
  'last name': 'Singh',
  'grade': 'M5',
  'grade level': 'M5a',
  'Designation': 'Assistant Manager - Quality',
  'department': 'Technology',
  'sub department': 'Field Engineering and Audit',
  'location': 'Lucknow',
  'office': 'Lucknow',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': 2430,
  'reporting to': 'Vishal Sethi',
  'state': 'Uttar Pradesh',
  'circle': 'NA',
  'date of birth': datetime.datetime(1970, 12, 20, 0, 0),
  'gender': 'Male',
  'email': 'gyanendras@tataplay.com',
  'assignment status type': 'ACTIVE',
  'date of resignation': None,
  'date of leaving': None,
  'role': 'NA',
  'last year rating': 3,
  'reason for resignation': 'NA'},
 {'employee code': 1005,
  'first name': 'Vineet',
  'last name': 'Kumar Tomar',
  'grade': 'M6',
  'grade level': 'M6z',
  'Designation': 'Senior Service Engineer - Delhi',
  'department': 'Service',
  'sub department': 'Service - Service',
  'location': 'Delhi',
  'office': 'Okhla',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'New Delhi',
  'circle': 'NA',
  'date of birth': datetime.datetime(1983, 5, 10, 0, 0),
  'gender': 'Male',
  'email': 'vineetk@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2008, 6, 3, 0, 0),
  'date of leaving': datetime.datetime(2008, 6, 3, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1006,
  'first name': 'Manoj',
  'last name': 'Sharma',
  'grade': 'M4',
  'grade level': 'M4z',
  'Designation': 'Manager IT - North',
  'department': 'IT',
  'sub department': 'IT_Ops',
  'location': 'Delhi',
  'office': 'Okhla',
  'region': 'North',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'New Delhi',
  'circle': 'NA',
  'date of birth': datetime.datetime(1968, 9, 28, 0, 0),
  'gender': 'Male',
  'email': 'manojsh@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2007, 8, 3, 0, 0),
  'date of leaving': datetime.datetime(2007, 8, 3, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1007,
  'first name': 'Lynette',
  'last name': "D' Cunha",
  'grade': 'M4',
  'grade level': 'M4a',
  'Designation': 'Senior Manager - Legal & Secretarial',
  'department': 'Legal',
  'sub department': 'Legal - General',
  'location': 'Mumbai',
  'office': 'Corporate',
  'region': 'Corporate',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': 4204,
  'reporting to': 'Jasmine Vidhani',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1965, 3, 16, 0, 0),
  'gender': 'Female',
  'email': 'lynetted@tataplay.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2025, 3, 4, 0, 0),
  'date of leaving': datetime.datetime(2025, 3, 31, 0, 0),
  'role': 'NA',
  'last year rating': 4,
  'reason for resignation': 'Involuntary'},
 {'employee code': 1008,
  'first name': 'Prakash',
  'last name': 'Gore',
  'grade': 'M6',
  'grade level': 'M6z',
  'Designation': 'Market Development Executive - Trade',
  'department': 'Sales & Service',
  'sub department': 'Operations',
  'location': 'Dhule',
  'office': 'Pune',
  'region': 'West',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1971, 10, 18, 0, 0),
  'gender': 'Male',
  'email': 'prakashg@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2010, 7, 1, 0, 0),
  'date of leaving': datetime.datetime(2010, 7, 1, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1009,
  'first name': 'Kuppa Srinivasa',
  'last name': 'Sastry',
  'grade': 'M3',
  'grade level': 'M3d',
  'Designation': 'Senior Manager - Field Service Delivery',
  'department': 'Field Service Delivery',
  'sub department': 'Field Service Delivery - General',
  'location': 'Hyderabad',
  'office': 'Hyderabad',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 4, 4, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Telangana',
  'circle': 'NA',
  'date of birth': datetime.datetime(1963, 7, 7, 0, 0),
  'gender': 'Male',
  'email': 'srinivasas@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2015, 4, 6, 0, 0),
  'date of leaving': datetime.datetime(2015, 4, 6, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 101,
  'first name': 'G Muraleedharan',
  'last name': 'Unni',
  'grade': 'M6',
  'grade level': 'M6z',
  'Designation': 'MDU Specialist - Mumbai',
  'department': 'Field Services',
  'sub department': 'Installation',
  'location': 'Mumbai II',
  'office': 'Mumbai',
  'region': 'West',
  'date of joining': datetime.datetime(2005, 9, 19, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1962, 7, 9, 0, 0),
  'gender': 'Male',
  'email': 'gmuraleedharan@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2007, 11, 1, 0, 0),
  'date of leaving': datetime.datetime(2007, 11, 1, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1010,
  'first name': 'Karen',
  'last name': 'Rebello',
  'grade': 'M5',
  'grade level': 'M5z',
  'Designation': 'Facilities Executive',
  'department': 'Facilities',
  'sub department': 'Facilities - General',
  'location': 'Mumbai',
  'office': 'Corporate',
  'region': 'Corporate',
  'date of joining': datetime.datetime(2006, 4, 5, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1981, 4, 28, 0, 0),
  'gender': 'Female',
  'email': 'karenr@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2009, 3, 13, 0, 0),
  'date of leaving': datetime.datetime(2009, 3, 13, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1011,
  'first name': 'Jeffry',
  'last name': 'A. Paul',
  'grade': 'M5',
  'grade level': 'M5z',
  'Designation': 'Senior Sales Executive MDU - Hyderabad',
  'department': 'Sales',
  'sub department': 'MDU Sales',
  'location': 'Hyderabad',
  'office': 'Hyderabad',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Telangana',
  'circle': 'NA',
  'date of birth': datetime.datetime(1979, 6, 30, 0, 0),
  'gender': 'Male',
  'email': 'jeffryp@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2007, 11, 1, 0, 0),
  'date of leaving': datetime.datetime(2007, 11, 1, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1012,
  'first name': 'Pradeep',
  'last name': 'P.N.',
  'grade': 'M6',
  'grade level': 'M6a',
  'Designation': 'Executive - IT Governance',
  'department': 'IT',
  'sub department': 'IT Governance',
  'location': 'Bangalore',
  'office': 'Hebbal',
  'region': 'South',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Karnataka',
  'circle': 'NA',
  'date of birth': datetime.datetime(1971, 2, 14, 0, 0),
  'gender': 'Male',
  'email': 'pradeepp@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2013, 10, 3, 0, 0),
  'date of leaving': datetime.datetime(2013, 10, 3, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1013,
  'first name': 'Shrikrishna',
  'last name': 'Kulkarni',
  'grade': 'M5',
  'grade level': 'M5z',
  'Designation': 'Senior Field Services Coordinator - Pune',
  'department': 'Service',
  'sub department': 'Service - Serv_Support',
  'location': 'Pune',
  'office': 'Pune',
  'region': 'West',
  'date of joining': datetime.datetime(2006, 4, 3, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1966, 12, 5, 0, 0),
  'gender': 'Male',
  'email': 'kulkarnis@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2008, 5, 16, 0, 0),
  'date of leaving': datetime.datetime(2008, 5, 16, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1014,
  'first name': 'Rekha Mohanlal',
  'last name': 'Shivani',
  'grade': 'M4',
  'grade level': 'M4z',
  'Designation': 'Assistant Manager - Finance & Accounts',
  'department': 'Finance',
  'sub department': 'Finance Old',
  'location': 'Mumbai',
  'office': 'Corporate',
  'region': 'Corporate',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1975, 1, 6, 0, 0),
  'gender': 'Female',
  'email': 'rekhas@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2007, 1, 1, 0, 0),
  'date of leaving': datetime.datetime(2007, 1, 1, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1015,
  'first name': 'Silveria',
  'last name': "D'Souza",
  'grade': 'M3',
  'grade level': 'M3z',
  'Designation': 'Senior Manager Tax',
  'department': 'Finance',
  'sub department': 'Finance Old',
  'location': 'Mumbai',
  'office': 'Corporate',
  'region': 'Corporate',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1972, 9, 30, 0, 0),
  'gender': 'Female',
  'email': 'silveriad@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2008, 5, 30, 0, 0),
  'date of leaving': datetime.datetime(2008, 5, 30, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1016,
  'first name': 'Kumar',
  'last name': 'Chandnani',
  'grade': 'M3',
  'grade level': 'M3z',
  'Designation': 'National Program Manager - IT&IS',
  'department': 'IT',
  'sub department': 'Gen_IT&IS',
  'location': 'Mumbai',
  'office': 'Corporate',
  'region': 'Corporate',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1969, 4, 22, 0, 0),
  'gender': 'Male',
  'email': 'kumarc@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2007, 7, 1, 0, 0),
  'date of leaving': datetime.datetime(2007, 7, 1, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1017,
  'first name': 'Rasika',
  'last name': 'Prabhu',
  'grade': 'M6',
  'grade level': 'M6z',
  'Designation': 'Field Services Coordinator - Mumbai',
  'department': 'Field Services',
  'sub department': 'FS Support',
  'location': 'Mumbai II',
  'office': 'Mumbai',
  'region': 'West',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1983, 12, 25, 0, 0),
  'gender': 'Female',
  'email': 'rasikap@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2007, 1, 12, 0, 0),
  'date of leaving': datetime.datetime(2007, 1, 12, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1018,
  'first name': 'Mohammed Shamshunisha',
  'last name': 'Iqbal',
  'grade': 'M5',
  'grade level': 'M5z',
  'Designation': 'Senior Area Service Incharge',
  'department': 'Service',
  'sub department': 'Service - Field Service Delivery',
  'location': 'Mumbai',
  'office': 'Kalina',
  'region': 'West',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1974, 6, 5, 0, 0),
  'gender': 'Female',
  'email': 'shamshunishai@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2011, 8, 10, 0, 0),
  'date of leaving': datetime.datetime(2011, 8, 10, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 1019,
  'first name': 'Rajnath',
  'last name': 'Patel',
  'grade': 'M6',
  'grade level': 'M6z',
  'Designation': 'Field Services Coordinator - Mumbai',
  'department': 'Service',
  'sub department': 'Service - Serv_Support',
  'location': 'Mumbai IV',
  'office': 'Mumbai',
  'region': 'West',
  'date of joining': datetime.datetime(2006, 4, 10, 0, 0),
  'manager employee code': None,
  'reporting to': 'NA',
  'state': 'Maharashtra',
  'circle': 'NA',
  'date of birth': datetime.datetime(1982, 8, 24, 0, 0),
  'gender': 'Male',
  'email': 'rajnathp@tatasky.com',
  'assignment status type': 'INACTIVE',
  'date of resignation': datetime.datetime(2008, 5, 17, 0, 0),
  'date of leaving': datetime.datetime(2008, 5, 17, 0, 0),
  'role': 'NA',
  'last year rating': None,
  'reason for resignation': 'NA'},
 {'employee code': 102,
  'first name': 'Ashish',
  'last name': 'Desai',
  'grade': 'M5',
  'grade level': 'M5z',
  'Designation': 'Senior Field Services Team Leader - Baroda',
  'department': 'Field Services',
  'sub department': 'Installation',